# Generated by Django 6.0.7 — adds SyncConflict and SyncQueueItem models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_refactor_devicetoken_to_basedevicetoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(db_index=True, max_length=100)),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type discriminator (products, inventory, prices, …)",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="The local (cloud-side) entity ID that conflicted",
                        max_length=100,
                    ),
                ),
                (
                    "local_data",
                    models.JSONField(
                        default=dict, help_text="Cloud-side version of the data"
                    ),
                ),
                (
                    "remote_data",
                    models.JSONField(
                        default=dict, help_text="Incoming branch version of the data"
                    ),
                ),
                (
                    "conflict_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of field-level conflicts [{field, local_value, remote_value}, …]",
                    ),
                ),
                (
                    "resolver_used",
                    models.CharField(
                        default="auto",
                        help_text="Which resolver detected this conflict",
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved_use_local", "Resolved — Use Local"),
                            ("resolved_use_remote", "Resolved — Use Remote"),
                            ("resolved_merge", "Resolved — Merged"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to="auth.user",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_conflicts",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync conflict",
                "verbose_name_plural": "sync conflicts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["branch", "entity_type"],
                        name="core_syncconflict_branch_entity_type_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_syncconflict_status_created_at_idx",
                    ),
                    models.Index(
                        fields=["node_id"],
                        name="core_syncconflict_node_id_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(db_index=True, max_length=100)),
                ("entity_type", models.CharField(max_length=50)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("sync_request", "Sync Request"),
                            ("config_update", "Config Update"),
                            ("approval", "Approval Notification"),
                        ],
                        default="update",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Data to sync to the branch"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Unique key for idempotent processing on the branch side",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_queue_items",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "sync queue item",
                "verbose_name_plural": "sync queue items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="core_syncqueueitem_status_retry_idx",
                    ),
                    models.Index(
                        fields=["branch", "status"],
                        name="core_syncqueueitem_branch_status_idx",
                    ),
                ],
            },
        ),
    ]
