# Generated by Django 5.2.15 on 2026-08-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_alter_certificate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('ar', 'Arabic'), ('pt-br', 'Portuguese (Brazil)')], max_length=10, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='Translated event title. Empty uses the canonical title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Translated event description. Empty uses the canonical description.')),
                ('location', models.CharField(blank=True, help_text='Translated venue or meeting location. Empty uses the canonical location.', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='handlers.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event translation',
                'verbose_name_plural': 'Event translations',
                'ordering': ['event_id', 'language'],
                'constraints': [models.UniqueConstraint(fields=('event', 'language'), name='unique_handlers_event_translation')],
            },
        ),
    ]
