# Generated by Django 5.2.16 on 2026-08-06

# Projects merged into Products: the repo project grid lives on the Products
# page (StreamField ``projects``) and the legacy /projects/ URL permanently
# redirects (apps/handlers/urls.py). Mirroring the CompanyPage merge
# (0009_delete_companypage), the now-unused ProjectsPage model is removed.
# Any leftover page instances are deleted first so the Wagtail tree stays
# consistent (the specific table is dropped right after).
from django.db import migrations


def delete_stale_projectspages(apps, schema_editor):
    ProjectsPage = apps.get_model("pages", "ProjectsPage")
    for page in ProjectsPage.objects.all():
        page.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_productpage_category_alter_productspage_projects_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_stale_projectspages, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="ProjectsPage",
        ),
    ]
