# Generated by Django 5.2.16 on 2026-08-07 13:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_productpage_display_mode_teampage_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandpage',
            name='palette_overrides',
            field=wagtail.fields.StreamField([('palette', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'The product whose system palette this overrides.', 'label': 'Product', 'page_type': ['pages.ProductPage'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hex colour, e.g. #0B57D0.', 'label': 'Colour', 'max_length': 9}), 2: ('wagtail.blocks.ListBlock', (1,), {'help_text': 'Up to 5 swatches, accent first. Empty list falls back to the system palette.', 'label': 'Swatches', 'max_num': 5, 'min_num': 1}), 3: ('wagtail.blocks.StructBlock', [[('product', 0), ('swatches', 2)]], {})}, help_text="One block per product: pick the product and enter up to 5 hex swatches (accent first). An override replaces that product's default system palette on the /brand/ page and in the brand modal; products without an override keep the hardcoded BRAND_SPEC palette.", verbose_name='Palette overrides'),
        ),
    ]
