# Generated by Django 5.2.16 on 2026-08-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(blank=True, default='#FFE14D', help_text='Accent color for highlights (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='analytics_provider',
            field=models.CharField(blank=True, choices=[('', 'None'), ('gtm', 'Google Tag Manager'), ('ga4', 'Google Analytics 4'), ('plausible', 'Plausible'), ('umami', 'Umami')], default='', help_text='Analytics provider for the frontend', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='apple_store_url',
            field=models.URLField(blank=True, default='', help_text='Apple App Store link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_enabled',
            field=models.BooleanField(default=False, help_text='Enable live chat / contact widget'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_provider',
            field=models.CharField(blank=True, choices=[('', 'None'), ('crisp', 'Crisp'), ('intercom', 'Intercom'), ('tawk', 'Tawk.to')], default='', help_text='Chat widget provider', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chat_widget_id',
            field=models.CharField(blank=True, default='', help_text='Chat widget ID / website ID', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Favicon (auto-sized to 32x32)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='GA4 measurement ID (e.g., G-XXXXXXXX)', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_play_url',
            field=models.URLField(blank=True, default='', help_text='Google Play store link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, default='', help_text='GTM container ID (e.g., GTM-XXXXXXX)', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_author',
            field=models.CharField(blank=True, default='Mahmoud Ezzat Moustafa', help_text='Default meta author', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Default meta description for pages without one'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, default='', help_text='Comma-separated keywords', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_cta_label',
            field=models.CharField(blank=True, default='Get Started', help_text='CTA button label in header', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_cta_url',
            field=models.CharField(blank=True, default='/#cta', help_text='CTA button link in header', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_show_contact',
            field=models.BooleanField(default=True, help_text='Show contact link in header CTA area'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_show_home',
            field=models.BooleanField(default=True, help_text='Include Home in the main navigation'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_prompt',
            field=models.TextField(blank=True, default='', help_text='Text above the newsletter signup in footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Default Open Graph image (1200x630 recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#0B57D0', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', help_text='Twitter/X handle (without @)', max_length=50),
        ),
    ]
