# Generated by Django 5.2.16 on 2026-08-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_update_sitesettings_nav_cta_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelanguage',
            name='code',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], help_text='BCP-47 language tag, for example en, ar, sv.', max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
