# Generated by Django 5.2.16 on 2026-08-12 15:23

import apps.content.models.products
import django.utils.timezone
import modelsearch.index
import wagtail.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('detail_slug', models.SlugField(blank=True, default='', help_text="Slug of the Wagtail product page this catalog row links to. Leave empty to use this row's own slug (language variants point at the canonical page here).", max_length=220, verbose_name='Detail page slug')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Short description')),
                ('description', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Description')),
                ('category', models.CharField(choices=[('application', 'Application'), ('platform', 'Platform'), ('library', 'Library')], default='application', max_length=20, verbose_name='Category')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', help_text="Primary language of this product's catalog copy.", max_length=10, verbose_name='Language')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base price in the unified catalog currency (0 = free/open source).', max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default=apps.content.models.products.default_currency, help_text='ISO 4217 code — defaults to FUSION_DEFAULT_CURRENCY.', max_length=3, verbose_name='Currency')),
                ('version', models.CharField(blank=True, default='', max_length=40, verbose_name='Version')),
                ('status', models.CharField(choices=[('live', 'Live / released'), ('development', 'Under development')], default='live', max_length=20, verbose_name='Status')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-is_featured', 'title'],
                'indexes': [models.Index(fields=['language', 'is_published'], name='content_pro_languag_444ef7_idx')],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
