# Generated by Django 5.2.16 on 2026-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_author',
            field=models.CharField(blank=True, default='Mahmoud Ezzat', help_text='Default meta author', max_length=200),
        ),
    ]
