-- =============================================================================
-- Gaming Center Seed Migration — Rollback
-- Reverts: gaming center data → restaurant defaults
-- =============================================================================

-- 1. Revert business settings to restaurant defaults
UPDATE settings SET
    restaurant_name  = 'POS KO',
    address          = '123 Main Street, Food District',
    phone            = '+1-555-0123',
    email            = 'hello@pos.com',
    tax_rate         = '10.0',
    currency         = 'USD',
    opening_time     = '08:00',
    closing_time     = '23:00',
    receipt_footer   = 'Thank you for your visit! Come again!',
    dine_in_tables   = 10,
    delivery_fee     = 5.0,
    delivery_fee_per_km = 1.5
WHERE id = 1;

-- 2. Remove gaming center sale items
DELETE FROM sale_items WHERE sale_id BETWEEN 13 AND 32;

-- 3. Remove gaming center sales
DELETE FROM sales WHERE id BETWEEN 13 AND 32;

-- 4. Restore delivery types (remove gaming center types, restore restaurant types)
DELETE FROM delivery_types WHERE id BETWEEN 4 AND 5;

INSERT OR IGNORE INTO delivery_types (id, name, description, fee_multiplier) VALUES
    (1, 'Standard',   'Standard delivery',    1.0),
    (2, 'Express',    'Express delivery',     1.5),
    (3, 'Pickup',     'Customer pickup only', 0.0);

-- 5. Remove gaming center employees
DELETE FROM employees WHERE id BETWEEN 13 AND 19;

-- 6. Restore restaurant employee types
DELETE FROM employee_types WHERE id BETWEEN 8 AND 12;

INSERT OR IGNORE INTO employee_types (id, name, description) VALUES
    (1, 'Chef',          'Head chef / cook'),
    (2, 'Waiter',        'Serves customers'),
    (3, 'Cashier',       'Handles payments'),
    (4, 'Kitchen Staff', 'Kitchen helper'),
    (5, 'Manager',       'Restaurant manager'),
    (6, 'Delivery Boy',  'Delivery driver'),
    (7, 'Security',      'Security guard');

-- 7. Remove gaming center products
DELETE FROM products WHERE id BETWEEN 51 AND 76;

-- 8. Remove gaming center categories
DELETE FROM categories WHERE id BETWEEN 11 AND 16;

-- 9. Restore food categories
INSERT OR IGNORE INTO categories (id, name) VALUES
    (1, 'Burgers'),
    (2, 'Fast Food'),
    (3, 'BBQ'),
    (4, 'Desserts'),
    (5, 'Drinks'),
    (6, 'Salads'),
    (7, 'Appetizers'),
    (8, 'Seafood'),
    (9, 'Soups'),
    (10, 'Specials');

-- 10. Restore restaurant products (clean image field — will be regenerated by seed)
INSERT OR IGNORE INTO products (id, name, price, unit, category_id) VALUES
    (1,  'Chicken Burger',      8.99,  'piece', 1),
    (2,  'Beef Burger',         10.99, 'piece', 1),
    (3,  'Veggie Burger',       7.99,  'piece', 1),
    (4,  'French Fries',        3.99,  'plate', 2),
    (5,  'Chicken Nuggets',     5.99,  'plate', 2),
    (6,  'Fish & Chips',        12.99, 'plate', 2),
    (7,  'Chicken Tikka',       14.99, 'plate', 3),
    (8,  'Beef BBQ Platter',    18.99, 'plate', 3),
    (9,  'Seekh Kebab',         12.99, 'plate', 3),
    (10, 'Chocolate Cake',      5.99,  'slice', 4),
    (11, 'Ice Cream',           3.99,  'scoop', 4),
    (12, 'Cheesecake',          6.99,  'slice', 4),
    (13, 'Cola',                1.99,  'can',   5),
    (14, 'Orange Juice',        2.99,  'glass', 5),
    (15, 'Water',               1.50,  'bottle',5);

-- 11. Restore restaurant employees
INSERT OR IGNORE INTO employees (id, name, phone, email, employee_type_id, salary, joined_at) VALUES
    (1,  'Ahmed Hassan',    '+1-555-0201', 'ahmed@pos.com',    1, 1200.00, '2025-01-15'),
    (2,  'Fatima Ali',      '+1-555-0202', 'fatima@pos.com',   2, 800.00,  '2025-02-01'),
    (3,  'Omar Khan',       '+1-555-0203', 'omar@pos.com',     2, 800.00,  '2025-02-15'),
    (4,  'Layla Hassan',    '+1-555-0204', 'layla@pos.com',    3, 900.00,  '2025-03-01'),
    (5,  'Yusuf Rahman',    '+1-555-0205', 'yusuf@pos.com',    4, 700.00,  '2025-03-15'),
    (6,  'Zara Malik',      '+1-555-0206', 'zara@pos.com',     2, 800.00,  '2025-04-01'),
    (7,  'Khalid Othman',   '+1-555-0207', 'khalid@pos.com',   5, 1500.00, '2025-01-01'),
    (8,  'Nadia Farid',     '+1-555-0208', 'nadia@pos.com',    2, 800.00,  '2025-04-15'),
    (9,  'Hassan Abbas',    '+1-555-0209', 'hassan@pos.com',   4, 700.00,  '2025-05-01'),
    (10, 'Mona Adel',       '+1-555-0210', 'mona@pos.com',     3, 900.00,  '2025-05-15');

-- 12. Restore deleted food inventory transactions
INSERT OR IGNORE INTO inventory_transactions (id, ingredient_id, transaction_type, quantity_change, note) VALUES
    (1,  1,  'purchase',  30.0,  'Initial stock - Chicken Breast'),
    (2,  2,  'purchase',  20.0,  'Initial stock - Beef Mince'),
    (3,  3,  'purchase',  10.0,  'Initial stock - Mutton'),
    (4,  4,  'purchase',  25.0,  'Initial stock - Basmati Rice'),
    (5,  5,  'purchase',  35.0,  'Initial stock - Wheat Flour'),
    (6,  6,  'purchase',  30.0,  'Initial stock - Cooking Oil'),
    (7,  7,  'purchase',  20.0,  'Initial stock - Tomato'),
    (8,  8,  'purchase',  25.0,  'Initial stock - Onion'),
    (9,  9,  'purchase',  15.0,  'Initial stock - Yogurt'),
    (10, 10, 'purchase',  10.0,  'Initial stock - Mozzarella Cheese'),
    (11, 1,  'purchase',  20.0,  'Weekly restock - Chicken Breast'),
    (12, 6,  'purchase',  15.0,  'Weekly restock - Cooking Oil'),
    (13, 7,  'purchase',  12.0,  'Weekly restock - Tomato'),
    (14, 8,  'purchase',  15.0,  'Weekly restock - Onion'),
    (15, 14, 'purchase',  10.0,  'Weekly restock - Soda Crates'),
    (16, 15, 'purchase',  12.0,  'Weekly restock - Water Bottles'),
    (17, 1,  'usage',     -5.0,  'Usage: Week 1 sales - Chicken items'),
    (18, 2,  'usage',     -3.0,  'Usage: Week 1 sales - Beef items'),
    (19, 4,  'usage',     -4.0,  'Usage: Week 1 sales - Rice dishes'),
    (20, 6,  'usage',     -8.0,  'Usage: Week 1 - Cooking'),
    (21, 7,  'usage',     -5.0,  'Usage: Week 1 - Vegetable prep'),
    (22, 8,  'usage',     -6.0,  'Usage: Week 1 - Vegetable prep'),
    (23, 10, 'usage',     -2.0,  'Usage: Week 1 - Pizza prep'),
    (24, 12, 'usage',     -3.0,  'Usage: Week 1 - Fries orders'),
    (25, 14, 'usage',     -4.0,  'Usage: Week 1 - Soda sales'),
    (26, 15, 'usage',     -5.0,  'Usage: Week 1 - Water sales'),
    (27, 7,  'waste',     -0.5,  'Spoiled tomatoes'),
    (28, 17, 'waste',     -1.0,  'Expired milk'),
    (29, 22, 'waste',     -0.8,  'Spoiled potatoes'),
    (30, 1,  'adjustment', -0.5, 'Adjustment: Count variance on chicken breast'),
    (31, 8,  'adjustment', -1.0, 'Adjustment: Weight discrepancy on onions');

-- 13. Restore inventory adjustments
INSERT OR IGNORE INTO inventory_adjustments (id, ingredient_id, previous_quantity, new_quantity, reason, created_by) VALUES
    (1, 1, 25.0, 24.5, 'Count correction - found 0.5kg less chicken',       'Ali Ahmed'),
    (2, 8, 20.0, 19.0, 'Count correction - weight discrepancy in onions',   'Usman Khan');

-- 14. Restore food ingredients (all 55)
INSERT OR IGNORE INTO ingredients (id, name, unit, current_quantity, reorder_level, reorder_quantity, cost_per_unit) VALUES
    (1,  'Chicken Breast',         'kg',    25.0,  10.0,  20.0,  450.00),
    (2,  'Beef Mince',             'kg',    15.0,  8.0,   15.0,  550.00),
    (3,  'Mutton',                 'kg',    8.0,   5.0,   10.0,  1100.00),
    (4,  'Basmati Rice',           'kg',    20.0,  10.0,  20.0,  180.00),
    (5,  'Wheat Flour',            'kg',    30.0,  15.0,  20.0,  70.00),
    (6,  'Cooking Oil',            'liter', 25.0,  10.0,  20.0,  320.00),
    (7,  'Tomato',                 'kg',    15.0,  8.0,   12.0,  90.00),
    (8,  'Onion',                  'kg',    20.0,  10.0,  15.0,  70.00),
    (9,  'Yogurt',                 'kg',    12.0,  5.0,   10.0,  130.00),
    (10, 'Mozzarella Cheese',      'kg',    8.0,   4.0,   8.0,   750.00),
    (11, 'Pizza Sauce',           'kg',    5.0,   3.0,   5.0,   380.00),
    (12, 'Frozen French Fries',    'kg',    12.0,  5.0,   10.0,  220.00),
    (13, 'Frozen Chicken Nuggets', 'kg',    8.0,   4.0,   6.0,   550.00),
    (14, 'Soda Cans (Crate)',      'crate', 15.0,  5.0,   10.0,  480.00),
    (15, 'Water Bottles (Case)',   'case',  20.0,  8.0,   12.0,  360.00),
    (16, 'Sugar',                  'kg',    15.0,  5.0,   10.0,  110.00),
    (17, 'Milk',                   'liter', 18.0,  8.0,   12.0,  180.00),
    (18, 'Cream',                  'liter', 5.0,   3.0,   5.0,   330.00),
    (19, 'Vanilla Ice Cream',      'kg',    6.0,   3.0,   5.0,   450.00),
    (20, 'Spices Mix (Garam Masala)', 'kg', 3.0,   2.0,   3.0,   240.00),
    (21, 'Eggs',                   'dozen', 12.0,  5.0,   10.0,  220.00),
    (22, 'Potato',                 'kg',    20.0,  10.0,  15.0,  50.00),
    (23, 'Cabbage',                'kg',    5.0,   3.0,   5.0,   45.00),
    (24, 'Capsicum',               'kg',    6.0,   3.0,   5.0,   110.00),
    (25, 'Ginger Garlic Paste',    'kg',    4.0,   2.0,   3.0,   280.00),
    (26, 'Green Chilies',          'kg',    3.0,   1.5,   2.5,   130.00),
    (27, 'Salt',                   'kg',    8.0,   3.0,   5.0,   25.00),
    (28, 'Tea Leaves',             'kg',    2.0,   1.0,   2.0,   550.00),
    (29, 'Coffee Beans',           'kg',    1.5,   0.5,   1.5,   1100.00),
    (30, 'Pizza Dough Flour',     'kg',    10.0,  5.0,   10.0,  90.00),
    (31, 'Ketchup',                'kg',    5.0,   2.5,   5.0,   150.00),
    (32, 'Mayonnaise',             'kg',    4.0,   2.0,   3.0,   200.00),
    (33, 'Burger Buns',            'dozen', 8.0,   4.0,   6.0,   240.00),
    (34, 'Chicken Wings',          'kg',    10.0,  5.0,   10.0,  480.00),
    (35, 'Noodles',                'kg',    6.0,   3.0,   5.0,   150.00),
    (36, 'Soy Sauce',              'liter', 2.0,   1.0,   2.0,   180.00),
    (37, 'Gulab Jamun Mix',        'kg',    4.0,   2.0,   3.0,   280.00),
    (38, 'Rice Flour',             'kg',    3.0,   1.5,   3.0,   100.00),
    (39, 'Lentils (Daal Chana)',  'kg',    8.0,   4.0,   6.0,   140.00),
    (40, 'Mango Pulp',             'kg',    3.0,   1.0,   3.0,   350.00),
    (41, 'Dried Fenugreek Leaves', 'kg',    2.0,   1.0,   2.0,   400.00),
    (42, 'Mixed Vegetables',       'kg',    10.0,  5.0,   8.0,   80.00),
    (43, 'Butter',                 'kg',    5.0,   2.0,   4.0,   450.00),
    (44, 'Spring Roll Pastry',     'pack',  8.0,   4.0,   6.0,   120.00),
    (45, 'Cardamom',               'kg',    1.0,   0.5,   1.0,   1800.00),
    (46, 'Almonds',                'kg',    3.0,   1.5,   3.0,   1200.00),
    (47, 'Pistachios',             'kg',    2.0,   1.0,   2.0,   1500.00),
    (48, 'Peanuts',                'kg',    5.0,   2.5,   5.0,   250.00),
    (49, 'Bread Slices',           'loaf',  10.0,  5.0,   8.0,   120.00),
    (50, 'Lemon',                  'kg',    5.0,   2.0,   5.0,   100.00),
    (51, 'Cinnamon Sticks',        'kg',    1.0,   0.5,   1.0,   900.00),
    (52, 'Black Pepper',           'kg',    1.5,   0.75,  1.5,   600.00),
    (53, 'Cumin Seeds',            'kg',    2.0,   1.0,   2.0,   350.00),
    (54, 'Turmeric Powder',        'kg',    2.0,   1.0,   2.0,   200.00),
    (55, 'Red Chili Powder',       'kg',    3.0,   1.5,   3.0,   300.00);

-- 15. Restore food recipes (all 41)
INSERT OR IGNORE INTO recipes (id, product_id, recipe_type_id, yield_quantity) VALUES
    (1,  1,  1, 1.0), (2,  2,  1, 1.0), (3,  6,  1, 1.0),
    (4,  10, 1, 1.0), (5,  14, 1, 1.0), (6,  18, 1, 1.0),
    (7,  23, 1, 1.0), (8,  28, 1, 1.0), (9,  30, 1, 1.0),
    (10, 35, 1, 1.0), (11, 39, 1, 1.0), (12, 43, 1, 1.0),
    (13, 4,  1, 1.0), (14, 25, 1, 1.0), (15, 3,  1, 1.0),
    (16, 5,  1, 1.0), (17, 8,  1, 1.0), (18, 11, 1, 1.0),
    (19, 12, 1, 1.0), (20, 13, 1, 1.0), (21, 15, 1, 1.0),
    (22, 16, 1, 1.0), (23, 17, 1, 1.0), (24, 20, 1, 1.0),
    (25, 22, 1, 1.0), (26, 24, 1, 1.0), (27, 26, 1, 1.0),
    (28, 27, 1, 1.0), (29, 31, 1, 1.0), (30, 32, 1, 1.0),
    (31, 34, 1, 1.0), (32, 36, 1, 1.0), (33, 37, 1, 1.0),
    (34, 38, 1, 1.0), (35, 40, 1, 1.0), (36, 41, 1, 1.0),
    (37, 42, 1, 1.0), (38, 44, 1, 1.0), (39, 45, 1, 1.0),
    (40, 46, 1, 1.0), (41, 47, 1, 1.0);

-- 16. Clear any stale product image references from gaming center products
UPDATE products SET image = NULL WHERE id BETWEEN 1 AND 47;
