# Generated by Django 5.2.16 on 2026-08-08 23:52

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_coursetag_specialization_course_objectives_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Main course image/thumbnail (Precis parity).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_course_images', to='wagtailimages.image', verbose_name='Course image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Resource title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='lesson_resources/', verbose_name='File')),
                ('resource_type', models.CharField(choices=[('slides', 'Slides'), ('code', 'Code files'), ('document', 'Document'), ('exercise', 'Exercise'), ('other', 'Other')], default='document', max_length=50, verbose_name='Resource type')),
                ('is_free', models.BooleanField(default=False, help_text='Available without enrollment', verbose_name='Free resource')),
                ('lesson', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.lesson', verbose_name='Parent Lesson')),
            ],
            options={
                'verbose_name': 'Lesson resource',
                'verbose_name_plural': 'Lesson resources',
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('time_spent_minutes', models.FloatField(default=0.0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='learning.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.module')),
            ],
            options={
                'ordering': ['module__order'],
                'indexes': [models.Index(fields=['enrollment', 'module'], name='learning_mo_enrollm_89f7a6_idx'), models.Index(fields=['status'], name='learning_mo_status_0d6cdd_idx')],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'module'), name='learning_enrollment_module')],
            },
        ),
    ]
