# Generated by Django 4.2.30 on 2026-05-20 11:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Portfolio Page',
                'verbose_name_plural': 'Portfolio Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PortfolioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., React, Django, UI Design, Mobile App', max_length=100, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of the tag name', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Optional description of this tag', verbose_name='Description')),
                ('color', models.CharField(default='#ee9b00', help_text='Hex color code for the tag badge', max_length=7, verbose_name='Tag Color')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class, e.g., bi-code-square', max_length=50, verbose_name='Icon Class')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is available for use', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Tag',
                'verbose_name_plural': 'Portfolio Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(help_text='Project category', max_length=100, verbose_name='Category')),
                ('description', models.TextField(help_text='Brief description', verbose_name='Description')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Detailed project content', verbose_name='Body')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', verbose_name='Video URL')),
                ('project_url', models.URLField(blank=True, help_text='Link to live project', verbose_name='Project URL')),
                ('tools', models.TextField(blank=True, help_text='Comma-separated list of tools used', verbose_name='Tools & Technologies')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('send_newsletter_on_publish', models.BooleanField(default=False, help_text='If checked, an email campaign will be generated and sent to all subscribers.', verbose_name='Send Newsletter on Publish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='wagtailimages.image', verbose_name='Featured Image')),
                ('tags', models.ManyToManyField(blank=True, help_text='Select portfolio tags', to='portfolio.portfoliotag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
    ]
