# Generated by Django 5.2.16 on 2026-08-12 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusionbranding',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Brand logo (overrides SiteSettings logo when set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='fusionbranding',
            name='company_name',
            field=models.CharField(default='Fusion Inc.', help_text='Legal company name for footer copyright', max_length=100),
        ),
        migrations.AlterField(
            model_name='fusionbranding',
            name='creator_name',
            field=models.CharField(default='Fusion Team', help_text='Creator/author name for meta tags and credits', max_length=100),
        ),
        migrations.AlterField(
            model_name='fusionbranding',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a favicon image', upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='fusionbranding',
            name='primary_color',
            field=models.CharField(default='#00a1b3', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='fusionbranding',
            name='secondary_color',
            field=models.CharField(default='#5b21b6', help_text='Secondary accent color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='fusionbranding',
            name='site_name',
            field=models.CharField(default='Fusion', help_text='Brand name used in the header and meta titles', max_length=100),
        ),
    ]
