# Generated by Django 5.2.16 on 2026-08-14 16:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "craft",
                    wagtail.fields.StreamField(
                        [("panel", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 80, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": False},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"required": False, "rows": 3},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Panel image URL (e.g. Unsplash).",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Accessible alt text.",
                                    "max_length": 160,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("caption", 1),
                                        ("body", 2),
                                        ("img", 3),
                                        ("alt", 4),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Craft accordion panels (the roast, the kitchen, the pickup).",
                    ),
                ),
                (
                    "voices",
                    wagtail.fields.StreamField(
                        [("voice", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 80, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": False},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"required": True, "rows": 3},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Portrait image URL (e.g. Unsplash).",
                                    "required": True,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("role", 1), ("quote", 2), ("img", 3)]],
                                {},
                            ),
                        },
                        help_text="Testimonial carousel voices.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Editorial settings",
            },
        ),
    ]
