# Generated by Django 5.2.13 on 2026-06-30 10:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='education',
            field=wagtail.fields.StreamField([('timeline_item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Degree, job title, milestone, or certification', 'label': 'Title', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Institution, company, or supporting label', 'label': 'Subtitle', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 2020 – Present', 'label': 'Date Range', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('date', 2), ('description', 3)]], {})}, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='experience',
            field=wagtail.fields.StreamField([('timeline_item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Degree, job title, milestone, or certification', 'label': 'Title', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Institution, company, or supporting label', 'label': 'Subtitle', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 2020 – Present', 'label': 'Date Range', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('date', 2), ('description', 3)]], {})}, verbose_name='Experience'),
        ),
    ]
