# Generated by Django 6.0.4 on 2026-04-16 19:04

import django.db.models.deletion
import django.utils.timezone
import django_rseal.contrib.utils
import django_rseal.pipelines.models.default
import embed_video.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=255, unique=True, verbose_name='Call SID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='initiated', help_text='Call status such as initiated, in-progress, or completed.', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Session Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('email_provider', models.CharField(choices=[('local', 'LOCAL'), ('console', 'CONSOLE'), ('smtp', 'SMTP'), ('sendgrid', 'SENDGRID'), ('mailgun', 'MAILGUN'), ('mailtrap', 'MAILTRAP'), ('mailpit', 'MAILPIT'), ('virtual', 'VIRTUAL'), ('aws_ses', 'AWS_SES')], max_length=50, verbose_name='Email Provider')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained')], max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Opened At')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Clicked At')),
                ('provider_message_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider Message ID')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active')),
                ('live', models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='First Published At')),
                ('last_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Published At')),
                ('search_description', models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('title', models.CharField(help_text='The title of the content.', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the content.', max_length=200, verbose_name='Subtitle')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews and listings.', verbose_name='Excerpt')),
                ('order', models.IntegerField(default=0, help_text='The display order of the content (lower numbers first).', verbose_name='Order')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates whether the content is published and visible to the public.', verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this content was published.', null=True, verbose_name='Published At')),
                ('notes', models.TextField(blank=True, help_text='Additional internal notes about the content.', verbose_name='Internal Notes')),
                ('file', models.FileField(blank=True, null=True, upload_to=django_rseal.contrib.utils.file_generate_upload_path, verbose_name='File')),
                ('original_file_name', models.TextField(verbose_name='Original File Name')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=255, verbose_name='File Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Upload Finished At')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'Files',
                'ordering': ['-uploaded_at', 'file_name'],
            },
            bases=(models.Model, django_rseal.pipelines.models.default.TemplateRenderMixin),
        ),
        migrations.CreateModel(
            name='GroupContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(db_index=True, help_text='Content type identifier (e.g., "page", "blog", "document")', max_length=100)),
                ('access_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('publish', 'Publish'), ('admin', 'Admin')], default='view', help_text='Level of access granted to this group', max_length=20)),
                ('content_id', models.CharField(blank=True, db_index=True, help_text='Specific content ID (leave blank for all content of this type)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Content Access',
                'verbose_name_plural': 'Group Content Access',
                'db_table': 'group_content_access',
                'ordering': ['content_type', 'group'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the integration (e.g. Twilio Messaging).', max_length=100, verbose_name='Integration Name')),
                ('external_id', models.CharField(blank=True, help_text='Unique identifier from the external system (if available).', max_length=255, verbose_name='External ID')),
                ('integration_type', models.CharField(choices=[('twilio', 'Twilio (Messaging API)'), ('stripe', 'Stripe (Payment Processor)'), ('paypal', 'PayPal (Payment Gateway)'), ('google', 'Google (OAuth / APIs)'), ('aws', 'Amazon Web Services (S3, SNS, etc.)'), ('slack', 'Slack (Messaging / Webhooks)'), ('zoho', 'Zoho (CRM / Accounting)'), ('hubspot', 'HubSpot (CRM / Marketing)'), ('quickbooks', 'QuickBooks (Accounting)'), ('custom', 'Custom Integration')], default='custom', help_text='Select which platform or service this integration connects to.', max_length=20, verbose_name='Integration Type')),
                ('endpoint_type', models.CharField(choices=[('sms', 'Messaging / SMS'), ('voice', 'Voice / Calls'), ('whatsapp', 'WhatsApp Messaging'), ('video', 'Video API'), ('payments', 'Payments / Charges'), ('invoices', 'Invoices / Billing'), ('customers', 'Customer Profiles'), ('subscriptions', 'Subscriptions / Plans'), ('auth', 'Authentication / OAuth'), ('webhook', 'Webhook Endpoint'), ('sync', 'Data Synchronization'), ('reports', 'Analytics / Reports'), ('callback', 'Callback or Redirect'), ('health', 'Health Check / Ping'), ('custom', 'Custom Endpoint')], default='custom', help_text='Type of endpoint or API section this configuration handles.', max_length=20, verbose_name='Endpoint Type')),
                ('api_endpoint', models.URLField(blank=True, help_text='Base URL for the endpoint, e.g., https://api.twilio.com/v1/messages', verbose_name='API Endpoint')),
                ('api_key', models.CharField(blank=True, help_text='API key or authentication token used for access.', max_length=255, verbose_name='API Key / Token')),
                ('metadata', models.JSONField(blank=True, help_text='Additional configuration or credentials as JSON.', null=True, verbose_name='Metadata')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this integration is currently enabled.', verbose_name='Is Active')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When the last synchronization or update occurred.', null=True, verbose_name='Last Sync At')),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending'), ('never', 'Never Synced')], default='never', help_text='The current synchronization status.', max_length=20, verbose_name='Sync Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active')),
                ('live', models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='First Published At')),
                ('last_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Published At')),
                ('search_description', models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Invitation Key')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
            bases=(models.Model, django_rseal.pipelines.models.default.TemplateRenderMixin),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS Message'), ('email', 'Email Notification'), ('voice', 'Voice Call'), ('push', 'Push Notification')], default='sms', max_length=20)),
                ('message', models.TextField(verbose_name='Message Content')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', help_text='Status of the notification: pending, sent, failed.', max_length=20, verbose_name='Status')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleEmailMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_role', models.CharField(db_index=True, help_text='Email role identifier (e.g., "admin", "supervisor")', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the email role mapping')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this mapping is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Email Mapping',
                'verbose_name_plural': 'Role Email Mappings',
                'db_table': 'role_email_mapping',
                'ordering': ['email_role'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active')),
                ('live', models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='First Published At')),
                ('last_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Published At')),
                ('search_description', models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('title', models.CharField(help_text='The title of the content.', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the content.', max_length=200, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, help_text='A brief description of the content.', verbose_name='Description')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews and listings.', verbose_name='Excerpt')),
                ('order', models.IntegerField(default=0, help_text='The display order of the content (lower numbers first).', verbose_name='Order')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates whether the content is published and visible to the public.', verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this content was published.', null=True, verbose_name='Published At')),
                ('notes', models.TextField(blank=True, help_text='Additional internal notes about the content.', verbose_name='Internal Notes')),
                ('video_url', embed_video.fields.EmbedVideoField(help_text='Paste a YouTube, Vimeo, or supported video URL.', verbose_name='Video URL')),
                ('duration', models.IntegerField(help_text='Duration in seconds', verbose_name='Duration')),
                ('is_preview', models.BooleanField(default=False, help_text='Mark this video as a preview clip.', verbose_name='Is Preview')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
            },
            bases=(models.Model, django_rseal.pipelines.models.default.TemplateRenderMixin),
        ),
        migrations.CreateModel(
            name='WagtailGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('editor', 'Editor'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], db_index=True, help_text='Role type in the hierarchy', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the group role and responsibilities')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this group is active and can be assigned to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wagtail Group Role',
                'verbose_name_plural': 'Wagtail Group Roles',
                'db_table': 'wagtail_group_role',
                'ordering': ['-role_type'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active')),
                ('live', models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='First Published At')),
                ('last_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Published At')),
                ('search_description', models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('title', models.CharField(help_text='The title of the content.', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the content.', max_length=200, verbose_name='Subtitle')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews and listings.', verbose_name='Excerpt')),
                ('order', models.IntegerField(default=0, help_text='The display order of the content (lower numbers first).', verbose_name='Order')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates whether the content is published and visible to the public.', verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this content was published.', null=True, verbose_name='Published At')),
                ('notes', models.TextField(blank=True, help_text='Additional internal notes about the content.', verbose_name='Internal Notes')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'Attachments',
                'ordering': ['-updated_at'],
            },
            bases=(models.Model, django_rseal.pipelines.models.default.TemplateRenderMixin),
        ),
    ]
