# Generated by Django 6.0.4 on 2026-04-16 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CI', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pipelines', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='pipelines.person'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Related Content Type'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='files',
            field=models.ManyToManyField(to='CI.file', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='groupcontentaccess',
            name='group',
            field=models.ForeignKey(help_text='Group with access to content', on_delete=django.db.models.deletion.CASCADE, related_name='content_access', to='auth.group'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['integration_type', 'is_active'], name='CI_integrat_integra_d2ac79_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['name'], name='CI_integrat_name_c381ce_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['sync_status'], name='CI_integrat_sync_st_2783a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('name', 'integration_type', 'endpoint_type')},
        ),
        migrations.AddField(
            model_name='call',
            name='integration',
            field=models.ForeignKey(blank=True, help_text='Reference to the integration used (e.g., Twilio Voice API).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='CI.integration', verbose_name='Integration'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Inviter'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='CI.invitation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pipelines.person'),
        ),
        migrations.AddField(
            model_name='notification',
            name='integration',
            field=models.ForeignKey(blank=True, help_text='The integration used to send this notification (e.g., Twilio, SendGrid).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='CI.integration', verbose_name='Integration'),
        ),
        migrations.AddField(
            model_name='roleemailmapping',
            name='wagtail_group',
            field=models.ForeignKey(help_text='Wagtail group to map to this email role', on_delete=django.db.models.deletion.CASCADE, related_name='email_role_mappings', to='auth.group'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Choose a thumbnail image from the Wagtail image library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnails', to='wagtailimages.image', verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='wagtailgrouprole',
            name='group',
            field=models.OneToOneField(help_text='Django group associated with this role', on_delete=django.db.models.deletion.CASCADE, related_name='wagtail_role', to='auth.group'),
        ),
        migrations.AddField(
            model_name='wagtailgrouprole',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Parent role in the hierarchy (for permission inheritance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='CI.wagtailgrouprole'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='Attachments_content_a54e19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupcontentaccess',
            unique_together={('group', 'content_type', 'content_id')},
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_address', 'sent_at'], name='CI_emaillog_email_a_ee6b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'sent_at'], name='CI_emaillog_status_dbaf1b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['invitation', 'sent_at'], name='CI_emaillog_invitat_9b5b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wagtailgrouprole',
            unique_together={('group', 'role_type')},
        ),
    ]
