# Generated by Django 5.2.16 on 2026-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 code — unified catalog currency (FUSION_DEFAULT_CURRENCY).', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('ar', 'Arabic'), ('pt-br', 'Portuguese (Brazil)')], default='en', max_length=10, verbose_name='Course Language'),
        ),
    ]
