networks:
  traefik-net:
    external: true

services:
  shared-media:
    build:
      context: ../..
      dockerfile: ./services/media/Dockerfile
    container_name: shared-media
    restart: unless-stopped
    networks:
      - traefik-net
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ../../assets/staticfiles:/var/www/static:ro
      - ../../assets/media:/var/www/media:ro
      - ../../ctc-research/assets/staticfiles:/var/www/sites/ctc-research/static:ro
      - ../../lms-demo/assets/staticfiles:/var/www/sites/lms-demo/static:ro
      - ../../VResume/assets/staticfiles:/var/www/sites/vresume/static:ro
      - ./media/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
