# Generated by Django 5.2.16 on 2026-08-07 12:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_founderpage_startuppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='applications',
            field=wagtail.fields.StreamField([('applications', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Application', 'max_length': 120}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Community / Business — shown as a chip on the card.', 'label': 'Edition', 'max_length': 80, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 3), ('edition', 4), ('url', 5), ('description', 2)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Applications'}), 8: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('applications', 7)]], {})}, help_text='Real applications/sites running on this product (e.g. Loop listing vResume + this site). One card each, linking out to the running product or its edition preview.', verbose_name='Built with this product'),
        ),
    ]
