# Generated by Django 5.2.16 on 2026-08-07 15:08

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_productpage_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='version',
            field=models.CharField(blank=True, help_text='Release label shown on catalog and product detail pages, for example beta 0.2 or v2.7.', max_length=40, verbose_name='Product version'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='editions',
            field=wagtail.fields.StreamField([('editions', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 80}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Tagline', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Price', 'max_length': 20}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Period', 'max_length': 40, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Features'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use a site static URL, for example /static/previews/formints/standard-front.jpg.', 'label': 'Media URL', 'max_length': 255}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('gif', 'Animated GIF'), ('video', 'Video')], 'help_text': 'Use GIF for a walkthrough. Use Video for an MP4/WebM recording.', 'label': 'Media type'}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional static poster path for video. Use /static/... or a relative previews/... path.', 'label': 'Video poster', 'max_length': 255, 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'View label', 'max_length': 80, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Alt text', 'max_length': 160, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('url', 9), ('kind', 10), ('poster', 11), ('label', 12), ('alt', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Optional screenshots shown on the edition preview page. Keep the list to the most useful product views.', 'label': 'Preview images', 'max_num': 4, 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': "Short deal/discount chip shown on the card (e.g. '50% off · launch'). Works on any edition — course, special, or standard.", 'label': 'Offer badge', 'max_length': 60, 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': "Original price struck through next to the current price (e.g. '$158'). Keep it short — the price row stays on one line.", 'label': 'Old price', 'max_length': 20, 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'CTA label', 'max_length': 80, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'CTA URL', 'max_length': 255, 'required': False}), 20: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Pick an internal page instead of typing a CTA URL.', 'label': 'CTA page', 'required': False}), 21: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Featured', 'required': False}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('outline', 'Outline — Community/open source'), ('default', 'Default — Standard/Solo'), ('featured', 'Featured — highlighted with accent'), ('managed', 'Managed — ribbon (hosted/Cloud)')], 'help_text': 'The card treatment: outline (Community), default (Standard/Solo), featured (Pro — accent + “most shipped”), managed (Cloud — ribbon).', 'label': 'Visual tier'}), 23: ('wagtail.blocks.StructBlock', [[('name', 3), ('tagline', 4), ('price', 5), ('period', 6), ('features', 8), ('preview_images', 15), ('offer_label', 16), ('offer_old_price', 17), ('cta_label', 18), ('cta_href', 19), ('cta_page', 20), ('featured', 21), ('tier', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'label': 'Editions'}), 25: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('editions', 24)]], {})}, verbose_name='Editions & pricing'),
        ),
    ]
