# Generated by Django 5.2.16 on 2026-08-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_customobjectdefinition_customobjectrecord_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "activity",
                "verbose_name_plural": "activities",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="customfielddefinition",
            options={
                "ordering": ["object_type", "position", "label"],
                "verbose_name": "custom field",
                "verbose_name_plural": "custom fields",
            },
        ),
        migrations.AlterModelOptions(
            name="customobjectdefinition",
            options={
                "ordering": ["name"],
                "verbose_name": "custom object",
                "verbose_name_plural": "custom objects",
            },
        ),
        migrations.AlterModelOptions(
            name="customobjectrecord",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "custom object record",
                "verbose_name_plural": "custom object records",
            },
        ),
        migrations.AlterModelOptions(
            name="deal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "deal",
                "verbose_name_plural": "deals",
            },
        ),
        migrations.AlterModelOptions(
            name="pipeline",
            options={
                "ordering": ["order"],
                "verbose_name": "pipeline",
                "verbose_name_plural": "pipelines",
            },
        ),
        migrations.AlterModelOptions(
            name="pipelinestage",
            options={
                "ordering": ["order"],
                "verbose_name": "pipeline stage",
                "verbose_name_plural": "pipeline stages",
            },
        ),
    ]
