# Generated by Django 6.0.4 on 2026-04-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_initial'),
    ]

    operations = [
    ]
