# Generated by Django 5.2.16 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_projectspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='companypage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='featurespage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='privacypage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='productspage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='productspage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='projectspage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
    ]
