# Generated by Django 5.2.16 on 2026-08-07 13:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_productpage_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='applications',
            field=wagtail.fields.StreamField([('applications', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Application', 'max_length': 120}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Community / Business — shown as a chip on the card.', 'label': 'Edition', 'max_length': 80, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL (e.g. the edition preview). Ignored when a page is chosen.', 'label': 'URL', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Pick an internal page — its URL wins over the manual URL field.', 'label': 'Link to a page', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('name', 3), ('edition', 4), ('url', 5), ('page', 6), ('description', 2)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Applications'}), 9: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('applications', 8)]], {})}, help_text='Real application/sites running on this product (e.g. Loop listing vResume + this site). One card each, linking out to the running product or its edition preview.', verbose_name='Built with this product'),
        ),
    ]
