# Generated by Django 5.2.16 on 2026-08-08 05:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_productpage_version_alter_productpage_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='gallery',
            field=wagtail.fields.StreamField(
                [('gallery', 11)],
                blank=True,
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}),
                    1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}),
                    2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}),
                    3: ('wagtail.blocks.ChoiceBlock', [], {
                        'choices': [
                            ('grid', 'Grid — responsive 2-3 column masonry'),
                            ('carousel', 'Carousel — horizontal snap scroll'),
                            ('stack', 'Stack — full-bleed with lightbox'),
                        ],
                        'default': 'grid',
                        'help_text': 'Grid shows a responsive 2-3 column layout. Carousel scrolls horizontally with snap points. Stack renders full-bleed images with a click-to-expand lightbox.',
                        'label': 'Display mode',
                    }),
                    4: ('wagtail.blocks.CharBlock', (), {
                        'help_text': 'Use a site static URL, for example /static/previews/formints/standard-front.jpg.',
                        'label': 'Media URL',
                        'max_length': 255,
                    }),
                    5: ('wagtail.blocks.ChoiceBlock', [], {
                        'choices': [('image', 'Image'), ('gif', 'Animated GIF'), ('video', 'Video')],
                        'help_text': 'Use GIF for a walkthrough. Use Video for an MP4/WebM recording.',
                        'label': 'Media type',
                    }),
                    6: ('wagtail.blocks.CharBlock', (), {
                        'help_text': 'Optional static poster path for video. Use /static/... or a relative previews/... path.',
                        'label': 'Video poster',
                        'max_length': 255,
                        'required': False,
                    }),
                    7: ('wagtail.blocks.CharBlock', (), {'label': 'View label', 'max_length': 80, 'required': False}),
                    8: ('wagtail.blocks.CharBlock', (), {'label': 'Alt text', 'max_length': 160, 'required': False}),
                    9: ('wagtail.blocks.StructBlock', [
                        [('url', 4), ('kind', 5), ('poster', 6), ('label', 7), ('alt', 8)]
                    ], {}),
                    10: ('wagtail.blocks.ListBlock', (9,), {
                        'help_text': 'Screenshots, GIFs and videos to display in the gallery.',
                        'label': 'Gallery items',
                    }),
                    11: ('wagtail.blocks.StructBlock', [
                        [('eyebrow', 0), ('title', 1), ('description', 2), ('display', 3), ('items', 10)]
                    ], {}),
                },
                verbose_name='Media gallery',
                help_text='Visual gallery: screenshots, GIFs and videos in a grid, carousel or stack.',
            ),
        ),
    ]
