# Generated by Django 5.2.16 on 2026-08-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0032_aboutpage_badges_featurespage_badges_and_more"),
        ("pages", "0032_productpage_profile"),
    ]

    operations = []
