# Generated by Django 4.2.30 on 2026-05-20 11:47

from django.db import migrations, models
import django.db.models.deletion
import pages.home.models.snippets.service
import pages.home.models.snippets.slider
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('slider', wagtail.fields.StreamField([('slider_item', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (pages.home.models.snippets.slider.Slider,), {})}, verbose_name='Slider Section')),
                ('services', wagtail.fields.StreamField([('service', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (pages.home.models.snippets.service.Service,), {})}, verbose_name='Services Section')),
                ('subscribe_newsletter', models.BooleanField(default=True, verbose_name='Show Newsletter Subscribe Section')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, default='folder-open', help_text='Bootstrap icon class, e.g. bi-code-square', max_length=100, verbose_name='Icon Class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('link_1_url', models.URLField(blank=True, verbose_name='Link 1 URL')),
                ('link_1_text', models.CharField(blank=True, max_length=100, verbose_name='Link 1 Text')),
                ('link_2_url', models.URLField(blank=True, verbose_name='Link 2 URL')),
                ('link_2_text', models.CharField(blank=True, max_length=100, verbose_name='Link 2 Text')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VResumeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL for the contact page', max_length=500, verbose_name='Map Embed URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('avatar', models.ForeignKey(blank=True, help_text='Avatar image displayed in the sidebar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('favicon', models.ForeignKey(blank=True, help_text='Browser favicon (small square image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, help_text='Company or personal logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'vResume Settings',
                'verbose_name_plural': 'vResume Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('contact_url', models.URLField(blank=True, verbose_name='Contact URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 100}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Remix icon class, e.g. ri-arrow-right-line', 'label': 'Icon Class', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1), ('icon', 2)]], {})}, help_text='Add one or more CTA links with icons', verbose_name='Links')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
