# Generated by Django 5.2.13 on 2026-06-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts_ai', '0004_announcementbanner_backgroundtasklog_campaign_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundTaskLog',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
