# Generated by Django 5.2.13 on 2026-08-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_emailsettings_language_alter_person_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtasklog',
            name='app_label_field',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='backgroundtasklog',
            name='backend',
            field=models.CharField(blank=True, default='dramatiq', max_length=50),
        ),
        migrations.AddField(
            model_name='backgroundtasklog',
            name='error_traceback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundtasklog',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backgroundtasklog',
            name='max_retries',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='backgroundtasklog',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='backgroundtasklog',
            name='site_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundtasklog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='queued', max_length=20),
        ),
        migrations.AddIndex(
            model_name='backgroundtasklog',
            index=models.Index(fields=['status', '-created_at'], name='grep_backgr_status_9092a9_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtasklog',
            index=models.Index(fields=['task_name', '-created_at'], name='grep_backgr_task_na_0e5a52_idx'),
        ),
        migrations.AddIndex(
            model_name='backgroundtasklog',
            index=models.Index(fields=['queue_name', 'status'], name='grep_backgr_queue_n_8cb95f_idx'),
        ),
    ]
