# Generated by Django 5.2.13 on 2026-06-26 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authemailtemplate_remove_article_author_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Privacy Consent',
                'verbose_name_plural': 'Privacy Consents',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=255)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terms Consent',
                'verbose_name_plural': 'Terms Consents',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms of Service', max_length=255)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='accounts_se_name_a7ce91_idx',
            old_name='services_name_a79f61_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='accounts_se_categor_1ae135_idx',
            old_name='services_categor_54c742_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='accounts_se_is_acti_283dec_idx',
            old_name='services_is_acti_b1f5d3_idx',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_verified_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_received_messages', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_sent_messages', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_shared_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='accounts.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tagged_items', to=settings.AUTH_USER_MODEL, verbose_name='Tagged By'),
        ),
        migrations.AlterModelTable(
            name='service',
            table='accounts_services',
        ),
        migrations.AddField(
            model_name='privacyconsent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_privacy_consent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privacyconsent',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.privacypolicy'),
        ),
        migrations.AddField(
            model_name='termsconsent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_terms_consent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termsconsent',
            name='terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.termsofservice'),
        ),
        migrations.AlterUniqueTogether(
            name='privacyconsent',
            unique_together={('user', 'policy')},
        ),
        migrations.AlterUniqueTogether(
            name='termsconsent',
            unique_together={('user', 'terms')},
        ),
    ]
