-- =============================================================================
-- Gaming Center Seed Migration — Rollback
-- Reverts: gaming center data → restaurant defaults
-- =============================================================================

-- 1. Revert business settings to restaurant defaults
UPDATE settings SET
    restaurant_name  = 'POS KO',
    address          = '123 Main Street, Food District',
    phone            = '+1-555-0123',
    email            = 'hello@pos.com',
    tax_rate         = '10.0',
    currency         = 'USD',
    opening_time     = '08:00',
    closing_time     = '23:00',
    receipt_footer   = 'Thank you for your visit! Come again!',
    dine_in_tables   = 10,
    delivery_fee     = 5.0,
    delivery_fee_per_km = 1.5
WHERE id = 1;

-- 2. Remove gaming center sale items
DELETE FROM sale_items WHERE sale_id BETWEEN 13 AND 32;

-- 3. Remove gaming center sales
DELETE FROM sales WHERE id BETWEEN 13 AND 32;

-- 4. Restore delivery types (remove gaming center types, restore restaurant types)
DELETE FROM delivery_types WHERE id BETWEEN 4 AND 5;

INSERT OR IGNORE INTO delivery_types (id, name, description, fee_multiplier) VALUES
    (1, 'Standard',   'Standard delivery',    1.0),
    (2, 'Express',    'Express delivery',     1.5),
    (3, 'Pickup',     'Customer pickup only', 0.0);

-- 5. Remove gaming center employees
DELETE FROM employees WHERE id BETWEEN 13 AND 19;

-- 6. Restore restaurant employee types
DELETE FROM employee_types WHERE id BETWEEN 8 AND 12;

INSERT OR IGNORE INTO employee_types (id, name, description) VALUES
    (1, 'Chef',          'Head chef / cook'),
    (2, 'Waiter',        'Serves customers'),
    (3, 'Cashier',       'Handles payments'),
    (4, 'Kitchen Staff', 'Kitchen helper'),
    (5, 'Manager',       'Restaurant manager'),
    (6, 'Delivery Boy',  'Delivery driver'),
    (7, 'Security',      'Security guard');

-- 7. Remove gaming center products
DELETE FROM products WHERE id BETWEEN 51 AND 76;

-- 8. Remove gaming center categories
DELETE FROM categories WHERE id BETWEEN 11 AND 16;

-- 9. Restore food categories
INSERT OR IGNORE INTO categories (id, name) VALUES
    (1, 'Burgers'),
    (2, 'Fast Food'),
    (3, 'BBQ'),
    (4, 'Desserts'),
    (5, 'Drinks'),
    (6, 'Salads'),
    (7, 'Appetizers'),
    (8, 'Seafood'),
    (9, 'Soups'),
    (10, 'Specials');

-- 10. Restore restaurant products (clean image field — will be regenerated by seed)
INSERT OR IGNORE INTO products (id, name, price, unit, category_id) VALUES
    (1,  'Chicken Burger',      8.99,  'piece', 1),
    (2,  'Beef Burger',         10.99, 'piece', 1),
    (3,  'Veggie Burger',       7.99,  'piece', 1),
    (4,  'French Fries',        3.99,  'plate', 2),
    (5,  'Chicken Nuggets',     5.99,  'plate', 2),
    (6,  'Fish & Chips',        12.99, 'plate', 2),
    (7,  'Chicken Tikka',       14.99, 'plate', 3),
    (8,  'Beef BBQ Platter',    18.99, 'plate', 3),
    (9,  'Seekh Kebab',         12.99, 'plate', 3),
    (10, 'Chocolate Cake',      5.99,  'slice', 4),
    (11, 'Ice Cream',           3.99,  'scoop', 4),
    (12, 'Cheesecake',          6.99,  'slice', 4),
    (13, 'Cola',                1.99,  'can',   5),
    (14, 'Orange Juice',        2.99,  'glass', 5),
    (15, 'Water',               1.50,  'bottle',5);

-- 11. Restore restaurant employees
INSERT OR IGNORE INTO employees (id, name, phone, email, employee_type_id, salary, joined_at) VALUES
    (1,  'Ahmed Hassan',    '+1-555-0201', 'ahmed@pos.com',    1, 1200.00, '2025-01-15'),
    (2,  'Fatima Ali',      '+1-555-0202', 'fatima@pos.com',   2, 800.00,  '2025-02-01'),
    (3,  'Omar Khan',       '+1-555-0203', 'omar@pos.com',     2, 800.00,  '2025-02-15'),
    (4,  'Layla Hassan',    '+1-555-0204', 'layla@pos.com',    3, 900.00,  '2025-03-01'),
    (5,  'Yusuf Rahman',    '+1-555-0205', 'yusuf@pos.com',    4, 700.00,  '2025-03-15'),
    (6,  'Zara Malik',      '+1-555-0206', 'zara@pos.com',     2, 800.00,  '2025-04-01'),
    (7,  'Khalid Othman',   '+1-555-0207', 'khalid@pos.com',   5, 1500.00, '2025-01-01'),
    (8,  'Nadia Farid',     '+1-555-0208', 'nadia@pos.com',    2, 800.00,  '2025-04-15'),
    (9,  'Hassan Abbas',    '+1-555-0209', 'hassan@pos.com',   4, 700.00,  '2025-05-01'),
    (10, 'Mona Adel',       '+1-555-0210', 'mona@pos.com',     3, 900.00,  '2025-05-15');
