# Generated by Django 5.2.13 on 2026-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='display_mode',
            field=models.CharField(choices=[('detail', 'Detail page'), ('modal', 'Modal / Overlay')], default='detail', help_text='How this page is displayed when navigated to.\n\n• **Detail page** — full-page navigation (default).\n• **Modal / Overlay** — opens in a modal dialog or overlay.\n\nModal mode works with Unpoly (up-layer="modal") and HTMX (swapped into a modal container).', max_length=20, verbose_name='Display mode'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='modal_size',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra large'), ('fullscreen', 'Full screen')], default='lg', help_text="Width of the modal dialog (only applies when display mode is 'Modal').", max_length=10, verbose_name='Modal size'),
        ),
    ]
