# Generated by Django 5.2.16 on 2026-08-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_background_task_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='external_ref',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='source',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
