# Generated by Django 5.2.16 on 2026-08-15 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_webhook_webhookdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('view_type', models.CharField(choices=[('list', 'List'), ('kanban', 'Kanban')], default='list', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='core.workspace')),
            ],
            options={
                'ordering': ['resource', 'name'],
                'indexes': [models.Index(fields=['workspace', 'user', 'resource'], name='core_savedv_workspa_23cfdb_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user', 'resource', 'name'), name='uniq_saved_view_member_name')],
            },
        ),
    ]
