# Generated by Django 5.2.16 on 2026-07-27 23:36

import django.db.models.deletion
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('registration_confirmation', 'Registration Confirmation'), ('signin_success', 'Sign-In Success')], max_length=50, verbose_name='Template Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body_html', wagtail.fields.RichTextField(verbose_name='Body (HTML)')),
                ('body_text', models.TextField(help_text='Used as fallback for email clients that do not render HTML.', verbose_name='Body (Plain Text)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Auth Email Template',
                'verbose_name_plural': 'Auth Email Templates',
                'db_table': 'accounts_registration_authemailtemplate',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=255)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms of Service', max_length=255)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('object_id', models.UUIDField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_created_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_privacy_consent', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.privacypolicy')),
            ],
            options={
                'verbose_name': 'Privacy Consent',
                'verbose_name_plural': 'Privacy Consents',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='accounts.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_shared_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Note',
                'verbose_name_plural': 'Shared Notes',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('tagged_at', models.DateTimeField(auto_now_add=True, verbose_name='Tagged At')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='accounts.tag', verbose_name='Tag')),
                ('tagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_tagged_items', to=settings.AUTH_USER_MODEL, verbose_name='Tagged By')),
            ],
            options={
                'verbose_name': 'Tagged Item',
                'verbose_name_plural': 'Tagged Items',
            },
        ),
        migrations.CreateModel(
            name='TermsConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_terms_consent', to=settings.AUTH_USER_MODEL)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='accounts.termsofservice')),
            ],
            options={
                'verbose_name': 'Terms Consent',
                'verbose_name_plural': 'Terms Consents',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issuer', models.CharField(max_length=200)),
                ('certificate_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('certificate_url', models.URLField(blank=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('verification_status', models.CharField(blank=True, max_length=50)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verification_file', models.FileField(blank=True, null=True, upload_to='certificates/verification/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='contenttypes.contenttype')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_verified_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='accounts_ce_content_9a0ccb_idx'), models.Index(fields=['status'], name='accounts_ce_status_cc80ae_idx'), models.Index(fields=['issue_date'], name='accounts_ce_issue_d_9b55c3_idx'), models.Index(fields=['expiry_date'], name='accounts_ce_expiry__761fba_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(db_index=True, help_text='Unique identifier for the form', max_length=50, verbose_name='Form ID')),
                ('data', models.JSONField(default=dict, help_text='JSON containing all submitted form field values', verbose_name='Form Data')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether notification email was sent', verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('page', models.ForeignKey(blank=True, help_text='The page where the form was submitted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='wagtailcore.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['form_id', 'submitted_at'], name='accounts_fo_form_id_4a4ef7_idx'), models.Index(fields=['email_sent'], name='accounts_fo_email_s_f3c018_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sender_object_id', models.UUIDField()),
                ('recipient_object_id', models.UUIDField()),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('general', 'General'), ('system', 'System'), ('notification', 'Notification'), ('alert', 'Alert'), ('support', 'Support')], default='general', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_received_messages', to='contenttypes.contenttype')),
                ('replied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='accounts.message')),
                ('sender_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_sent_messages', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender_content_type', 'sender_object_id'], name='accounts_me_sender__05475e_idx'), models.Index(fields=['recipient_content_type', 'recipient_object_id'], name='accounts_me_recipie_7c3720_idx'), models.Index(fields=['status'], name='accounts_me_status_52a087_idx'), models.Index(fields=['is_read'], name='accounts_me_is_read_ad2c8c_idx'), models.Index(fields=['priority', 'created_at'], name='accounts_me_priorit_446994_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['content_type', 'object_id'], name='accounts_no_content_3b97ae_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_by'], name='accounts_no_created_02b3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_pinned', 'created_at'], name='accounts_no_is_pinn_36fcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_archived'], name='accounts_no_is_arch_398b5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privacyconsent',
            unique_together={('user', 'policy')},
        ),
        migrations.AlterUniqueTogether(
            name='sharednote',
            unique_together={('note', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='termsconsent',
            unique_together={('user', 'terms')},
        ),
    
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    
]
