# Generated by Django 5.2.13 on 2026-08-02 19:47
#
# NOTE: Simplified for SQLite compatibility. The legacy accounts-owned
# Message / Note / SharedNote / Certificate models were migrated to the
# `handlers` app (django_fusion-based abstractions). The intermediate
# RemoveField/AlterUniqueTogether steps crashed SQLite's table-remake
# machinery because the models' indexes referenced the removed columns;
# DeleteModel drops each table (with its indexes) in a single operation.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='SharedNote',
        ),
    ]
