# Generated by Django 5.2.13 on 2026-08-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
    ]
