# Generated by Django 6.0.7 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='app_type',
            field=models.CharField(choices=[('pos-solo', 'POS Solo'), ('pos-full', 'POS Full'), ('pos-mini', 'POS Mini'), ('cloud', 'Cloud Server')], db_index=True, default='pos-solo', help_text='Application type flag for DataToken sync scoping.', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary extra data (e.g. invoice total, customer name).'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current sync state of this row/token.', max_length=20),
        ),
    ]
