# Generated by Django 6.1 on 2026-08-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_invoice_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueevent',
            name='kind',
            field=models.CharField(choices=[('deal_won', 'Deal won'), ('expansion', 'Expansion'), ('renewal', 'Renewal'), ('refund', 'Refund'), ('pos_sale', 'POS sale'), ('pos_refund', 'POS refund'), ('subscription', 'Subscription')], default='deal_won', max_length=20),
        ),
    ]
