# Generated by Django 5.2.13 on 2026-07-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
