# Generated by Django 6.0.7 on 2026-07-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Device identifier. Multiple tokens per device allowed for refresh cycles.', max_length=100, verbose_name='device ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the raw token.', max_length=128, unique=True, verbose_name='token hash')),
                ('token_prefix', models.CharField(help_text='First 8 characters of the raw token (for UI display).', max_length=8, verbose_name='token prefix')),
                ('node_id_link', models.CharField(blank=True, db_index=True, default='', help_text='Node identifier this token belongs to.', max_length=100, verbose_name='node ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('viewer', 'Viewer')], db_index=True, default='viewer', max_length=20, verbose_name='role')),
                ('app_type', models.CharField(choices=[('pos-solo', 'POS Solo'), ('pos-full', 'POS Full'), ('pos-mini', 'POS Mini'), ('cloud', 'Cloud Server')], db_index=True, default='pos-solo', help_text='Application type flag for DataToken sync scoping.', max_length=20, verbose_name='app type')),
                ('node_type', models.CharField(choices=[('pos-solo', 'POS Solo'), ('pos-full', 'POS Full'), ('pos-minimal', 'POS Minimal'), ('cloud-server', 'Cloud Server'), ('external', 'External')], default='pos-solo', max_length=20, verbose_name='node type')),
                ('capabilities', models.JSONField(blank=True, default=dict, verbose_name='capabilities')),
                ('allowed_entities', models.JSONField(blank=True, default=list, verbose_name='allowed entities')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('expires_at', models.DateTimeField(help_text='When this token expires.', verbose_name='expires at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When data tagged with this token was last confirmed synced.', null=True, verbose_name='last synced at')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Sync status of data tagged with this token.', max_length=20, verbose_name='sync status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this device token is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_tokens', to='core.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'device token',
                'verbose_name_plural': 'device tokens',
                'db_table': 'cloud_device_tokens',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['token_hash'], name='cloud_devic_token_h_539674_idx'), models.Index(fields=['device_id', 'is_active'], name='cloud_devic_device__722228_idx'), models.Index(fields=['role'], name='cloud_devic_role_531cf4_idx'), models.Index(fields=['expires_at'], name='cloud_devic_expires_d6e929_idx'), models.Index(fields=['sync_status'], name='cloud_devic_sync_st_953633_idx'), models.Index(fields=['app_type', 'sync_status'], name='cloud_devic_app_typ_8cc82c_idx'), models.Index(fields=['branch', 'is_active'], name='cloud_devic_branch__1599b9_idx')],
            },
        ),
    ]
