# Generated by Django 6.0.7 on 2026-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_devicetoken_app_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='allowed_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_id',
            field=models.CharField(db_index=True, help_text='Device identifier. Multiple tokens per device allowed for refresh cycles.', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='expires_at',
            field=models.DateTimeField(help_text='When this token expires'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When data tagged with this token was last confirmed synced', null=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='node_id_link',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Node identifier this token belongs to (matches Node.node_id)', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token_hash',
            field=models.CharField(help_text='SHA-256 hash of the raw token', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token_prefix',
            field=models.CharField(help_text='First 8 characters of raw token', max_length=8),
        ),
    ]
