# Generated by Django 5.0.14 on 2026-08-10 22:12

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backup_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='USD', max_length=3, verbose_name='currency code')),
                ('tax_profile_id', models.CharField(blank=True, default='', max_length=50, verbose_name='tax profile')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='tax rate')),
                ('price_decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='price decimals')),
                ('round_after_tax', models.BooleanField(default=False, verbose_name='round after tax')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='timezone')),
                ('locale', models.CharField(default='en', max_length=10, verbose_name='locale')),
                ('week_starts_on', models.PositiveSmallIntegerField(default=1, verbose_name='week starts on')),
                ('receipt_footer', models.TextField(blank=True, default='', verbose_name='receipt footer')),
                ('receipt_logo_url', models.URLField(blank=True, default='', verbose_name='receipt logo URL')),
                ('receipt_paper_width_mm', models.PositiveSmallIntegerField(default=80, verbose_name='paper width (mm)')),
                ('auto_print_receipt', models.BooleanField(default=True, verbose_name='auto-print receipt')),
                ('sync_interval_seconds', models.PositiveIntegerField(default=300, verbose_name='sync interval (s)')),
                ('offline_grace_minutes', models.PositiveIntegerField(default=30, verbose_name='offline grace (min)')),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=10, max_digits=12, verbose_name='low stock threshold')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='features')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_row', to='core.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'branch settings',
                'verbose_name_plural': 'branch settings',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='core.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'ordering': ['schema_name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.tenant')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domains',
                'ordering': ['domain'],
            },
        ),
    ]
