# Generated by Django 5.2.16 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_newslettersubscriber_provider_synced_at_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(choices=[("en", "English"), ("ar", "Arabic")], max_length=2, verbose_name="Language")),
                ("title", models.CharField(blank=True, max_length=255)),
                ("search_description", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_translations",
                        to="wagtailcore.page",
                        verbose_name="Page",
                    ),
                ),
            ],
            options={
                "verbose_name": "page translation",
                "verbose_name_plural": "page translations",
                "ordering": ["page_id", "language"],
            },
        ),
        migrations.AddConstraint(
            model_name="pagetranslation",
            constraint=models.UniqueConstraint(
                fields=("page", "language"),
                name="unique_landing_page_translation",
            ),
        ),
    ]
