# Generated by Django 5.2.11 on 2026-02-16 02:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('services_section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('subtitle', 1), ('title', 2)]], {})}, help_text='Dynamic content sections for the service.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_type',
            field=models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier'), ('partner', 'Partner'), ('vendor', 'Vendor'), ('competitor', 'Competitor'), ('educational', 'Educational Institution'), ('academic', 'Academic Institution'), ('internal', 'Internal Organization'), ('other', 'Other')], default='client', help_text='Primary classification of the company relationship', max_length=20, verbose_name='Company Type'),
        ),
    ]
