# Generated by Django 5.2.13 on 2026-08-01 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


class SafeAddField(migrations.AddField):
    """Apply an AddField only when its database column is not already present.

    Some existing Fusion databases predate the current migration history but
    already contain these shared audit/content columns. Keep Django's migration
    state authoritative while avoiding a duplicate-column failure on upgrade.
    Fresh databases still use Django's normal AddField implementation.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        introspection = schema_editor.connection.introspection
        with schema_editor.connection.cursor() as cursor:
            table = model._meta.db_table
            description = introspection.get_table_description(cursor, table)
            columns = {
                introspection.identifier_converter(column.name): column
                for column in description
            }
            column_name = introspection.identifier_converter(field.column)
            existing = columns.get(column_name)
            if existing is None:
                super().database_forwards(
                    app_label, schema_editor, from_state, to_state
                )
                return

            if isinstance(field, models.ForeignKey):
                # FK column stores the same database type as the target PK.
                # AutoField/BigAutoField introspect as IntegerField/BigIntegerField,
                # so map them for a fair comparison with the live schema.
                target_internal = field.target_field.get_internal_type()
                _auto_map = {
                    "AutoField": "IntegerField",
                    "BigAutoField": "BigIntegerField",
                    "SmallAutoField": "SmallIntegerField",
                }
                expected_type = _auto_map.get(target_internal, target_internal)
            else:
                expected_type = field.get_internal_type()
            actual_type = introspection.get_field_type(
                existing.type_code, existing
            )
            if actual_type != expected_type or existing.null_ok != field.null:
                raise RuntimeError(
                    f"Existing {table}.{column_name} does not match {expected_type} "
                    f"(type={actual_type}, nullable={existing.null_ok}); refusing "
                    "to mark the compatibility operation complete."
                )

            constraints = introspection.get_constraints(cursor, table)
            column_constraints = [
                constraint
                for constraint in constraints.values()
                if constraint.get("columns") == [field.column]
            ]
            if isinstance(field, models.ForeignKey) and not any(
                constraint.get("foreign_key") for constraint in column_constraints
            ):
                raise RuntimeError(
                    f"Existing {table}.{column_name} is missing its foreign-key "
                    "constraint; refusing to skip the migration operation."
                )
            if field.db_index and not any(
                constraint.get("index") or constraint.get("unique")
                for constraint in column_constraints
            ):
                raise RuntimeError(
                    f"Existing {table}.{column_name} is missing its expected index; "
                    "refusing to skip the migration operation."
                )

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        """Never drop a column that may predate this migration's history."""
        raise IrreversibleError(
            "The shared compatibility migration cannot be reversed safely because "
            "its columns may predate Django's recorded migration history."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SafeAddField(
            model_name='newsletter',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        SafeAddField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active'),
        ),
        SafeAddField(
            model_name='newsletter',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        SafeAddField(
            model_name='newsletter',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        SafeAddField(
            model_name='newslettersubscription',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        SafeAddField(
            model_name='newslettersubscription',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published At'),
        ),
        SafeAddField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active'),
        ),
        SafeAddField(
            model_name='newslettersubscription',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Published At'),
        ),
        SafeAddField(
            model_name='newslettersubscription',
            name='live',
            field=models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live'),
        ),
        SafeAddField(
            model_name='newslettersubscription',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        SafeAddField(
            model_name='newslettersubscription',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        SafeAddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        SafeAddField(
            model_name='person',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published At'),
        ),
        SafeAddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active'),
        ),
        SafeAddField(
            model_name='person',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Published At'),
        ),
        SafeAddField(
            model_name='person',
            name='live',
            field=models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live'),
        ),
        SafeAddField(
            model_name='person',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        SafeAddField(
            model_name='person',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        SafeAddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        SafeAddField(
            model_name='team',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published At'),
        ),
        SafeAddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active'),
        ),
        SafeAddField(
            model_name='team',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Published At'),
        ),
        SafeAddField(
            model_name='team',
            name='live',
            field=models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live'),
        ),
        SafeAddField(
            model_name='team',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        SafeAddField(
            model_name='team',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        SafeAddField(
            model_name='teaminvitation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        SafeAddField(
            model_name='teaminvitation',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published At'),
        ),
        SafeAddField(
            model_name='teaminvitation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active'),
        ),
        SafeAddField(
            model_name='teaminvitation',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Published At'),
        ),
        SafeAddField(
            model_name='teaminvitation',
            name='live',
            field=models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live'),
        ),
        SafeAddField(
            model_name='teaminvitation',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        SafeAddField(
            model_name='teaminvitation',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        SafeAddField(
            model_name='teammembership',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        SafeAddField(
            model_name='teammembership',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published At'),
        ),
        SafeAddField(
            model_name='teammembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active'),
        ),
        SafeAddField(
            model_name='teammembership',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Published At'),
        ),
        SafeAddField(
            model_name='teammembership',
            name='live',
            field=models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live'),
        ),
        SafeAddField(
            model_name='teammembership',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        SafeAddField(
            model_name='teammembership',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        SafeAddField(
            model_name='workspace',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        SafeAddField(
            model_name='workspace',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published At'),
        ),
        SafeAddField(
            model_name='workspace',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Published At'),
        ),
        SafeAddField(
            model_name='workspace',
            name='live',
            field=models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live'),
        ),
        SafeAddField(
            model_name='workspace',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        SafeAddField(
            model_name='workspace',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
