# Generated by Django 5.2.13 on 2026-08-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_newsletter_created_by_newsletter_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': False, 'ordering': ['template_type', 'name', 'version']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': False, 'ordering': ['-created_at', 'full_name'], 'permissions': [('view_profile_stats', 'Can view profile statistics'), ('export_profiles', 'Can export profile data'), ('can_manage_profiles', 'Can manage all profiles'), ('can_view_sensitive_data', 'Can view sensitive profile data'), ('can_invite_profiles', 'Can invite new profiles'), ('can_share_profiles', 'Can share profile data'), ('can_impersonate_profile', 'Can impersonate profile')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'managed': False, 'ordering': ['user', '-role']},
        ),
    ]
