# Generated by Django 5.2.13 on 2026-06-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='pages_conta_form_id_41afec_idx',
            old_name='content_con_form_id_9f1854_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='pages_conta_page_id_fc2419_idx',
            old_name='content_con_page_id_33c9c4_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='pages_conta_submiss_a663dd_idx',
            old_name='content_con_submiss_0ed1eb_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='pages_conta_process_6d8db5_idx',
            old_name='content_con_process_eeeffe_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='pages_conta_page_ti_83880f_idx',
            old_name='content_con_page_ti_71b799_idx',
        ),
        migrations.RenameIndex(
            model_name='contactsubmission',
            new_name='pages_conta_live_f0f8df_idx',
            old_name='content_con_live_068f7b_idx',
        ),
        migrations.AlterModelTable(
            name='aboutpage',
            table='content_aboutpage',
        ),
        migrations.AlterModelTable(
            name='contactpage',
            table='content_contactpage',
        ),
        migrations.AlterModelTable(
            name='homepage',
            table='content_homepage',
        ),
        migrations.AlterModelTable(
            name='servicespage',
            table='content_servicespage',
        ),
    ]
