http:
  routers:
    docs-http:
      rule: 'Host(`docs.structa.cloud`)'
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: docs-service
    docs-https:
      rule: 'Host(`docs.structa.cloud`)'
      entryPoints: [web-secure]
      middlewares: [compress, security-headers]
      service: docs-service
      tls:
  services:
    docs-service:
      loadBalancer:
        servers:
          - url: 'http://docs:80'
        healthCheck:
          path: /
          interval: 60s
          timeout: 5s
