from configs.base.admin_site import *
from configs.base.apps import *
from configs.base.assets import *
from configs.base.auth import *
from configs.base.databases import *
from configs.base.emails import *
from configs.base.i18n import *
from configs.base.logging import *
from configs.base.middlewares import *
from configs.base.security import *
from configs.base.templates import *
from configs.base.wagtail import *
