# Generated by Django 5.2.16 on 2026-08-18

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "publication category",
                "verbose_name_plural": "publication categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                ("abstract", wagtail.fields.RichTextField(blank=True, default="")),
                ("authors", models.CharField(blank=True, default="", max_length=500)),
                ("language", models.CharField(choices=[("en", "English"), ("sv", "Swedish"), ("fr", "French"), ("de", "German"), ("es", "Spanish"), ("ar", "Arabic"), ("pt-br", "Portuguese (Brazil)")], db_index=True, default="en", max_length=10)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("external_url", models.URLField(blank=True, default="")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="publications", to="pages.publicationcategory")),
            ],
            options={
                "verbose_name": "publication",
                "verbose_name_plural": "publications",
                "ordering": ["-published_at"],
            },
        ),
    ]
