# Generated by Django 5.2.15 on 2026-08-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_homepage_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='canonical_url',
            field=models.URLField(blank=True, default='', help_text='Optional absolute canonical origin (defaults to the site URL from settings)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_type',
            field=models.CharField(blank=True, default='website', help_text='Open Graph type (website, article, product, …)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='robots_meta',
            field=models.CharField(blank=True, choices=[('', 'index, follow (default)'), ('noindex, follow', 'noindex, follow'), ('index, nofollow', 'index, nofollow'), ('noindex, nofollow', 'noindex, nofollow')], default='', help_text='Global robots directive (per-page overrides win)', max_length=100),
        ),
    ]
