# Generated by Django 5.2.16 on 2026-08-19 19:55

import django.db.models.deletion
import django_fusion.routes.pages.mixins
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_aboutpage_facts'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_page_at_footer', models.BooleanField(default=False, help_text='If enabled, this page will appear as a link in the footer menu.', verbose_name='Show Page at Footer')),
                ('hero_heading', models.CharField(blank=True, default='', max_length=200, verbose_name='Hero Heading')),
                ('hero_subheading', models.TextField(blank=True, default='', verbose_name='Hero Subheading')),
                ('intro_text', models.TextField(blank=True, default='', verbose_name='Intro Text')),
                ('faq', wagtail.fields.StreamField([('faq_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Question', 'max_length': 300}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Answer'}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, null=True, verbose_name='FAQ')),
                ('pricing', wagtail.fields.StreamField([('pricing', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Intro', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Plan Name', 'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'default': '0', 'label': 'Price', 'max_length': 20}), 4: ('wagtail.blocks.CharBlock', (), {'default': '', 'label': 'Period', 'max_length': 50}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Features'}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Highlighted', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Get started', 'label': 'CTA Label', 'max_length': 50}), 10: ('wagtail.blocks.CharBlock', (), {'default': '/#cta', 'label': 'CTA Link', 'max_length': 300}), 11: ('wagtail.blocks.StructBlock', [[('name', 2), ('price', 3), ('period', 4), ('description', 5), ('features', 7), ('featured', 8), ('cta_label', 9), ('cta_href', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Tiers'}), 13: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('tiers', 12)]], {})}, null=True, verbose_name='Pricing')),
                ('features', wagtail.fields.StreamField([('feature', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Icon (SVG path or class)', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description'}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}, null=True, verbose_name='Features')),
                ('projects', wagtail.fields.StreamField([('project', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Edition', 'max_length': 100, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'program', 'label': 'Category', 'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Path', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 200}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Shared', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 5), ('shared', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Features', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 0), ('edition', 1), ('category', 2), ('path', 3), ('description', 4), ('features', 8)]], {})}, null=True, verbose_name='Projects')),
                ('products', wagtail.fields.StreamField([('product', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Slug', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Tagline', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '/services/', 'label': 'Link', 'max_length': 300}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('slug', 1), ('tagline', 2), ('href', 3)]], {})}, null=True, verbose_name='Products')),
                ('stats', wagtail.fields.StreamField([('stat', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Value', 'max_length': 50}), 2: ('wagtail.blocks.CharBlock', (), {'default': '', 'label': 'Suffix', 'max_length': 20, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('value', 1), ('suffix', 2)]], {})}, null=True, verbose_name='Stats')),
                ('CTA', wagtail.fields.StreamField([('cta_content', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'label': 'Label', 'max_length': 50}), 3: ('wagtail.blocks.CharBlock', (), {'default': '/contact/', 'label': 'Link', 'max_length': 300}), 4: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3)]], {'label': 'Primary CTA'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('primary_cta', 4)]], {})}, null=True, verbose_name='CTA Section')),
            ],
            options={
                'verbose_name': 'marketing page',
                'verbose_name_plural': 'marketing pages',
                'db_table': 'content_marketingpage',
            },
            bases=(django_fusion.routes.pages.mixins.WagtailPageMixin, 'wagtailcore.page'),
        ),
    ]
