# Generated by Django 5.2.16 on 2026-08-25 13:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_homepage_hero_accent_homepage_hero_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_chrome',
            field=wagtail.fields.StreamField([('slider_head', 3), ('course_head', 4), ('evidence_panel', 11), ('learning_teaser', 16), ('methods_head', 18), ('programs_head', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small label above the title', 'label': 'Eyebrow', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional supporting sentence', 'label': 'Intro', 'max_length': 400, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('intro', 2)]], {'icon': 'slides', 'label': 'Research slider heading'}), 4: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('intro', 2)]], {'icon': 'list-ul', 'label': 'Course slider heading'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Text', 'max_length': 400, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 17+', 'label': 'Value', 'max_length': 20, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 100, 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('value', 7), ('label', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'default': [{'label': 'years of research', 'value': '17+'}, {'label': 'course programs', 'value': '6'}, {'label': 'languages', 'value': '7'}], 'label': 'Stats', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('stats', 10)]], {'icon': 'clipboard-list', 'label': 'Hero evidence panel'}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Marker', 'max_length': 60, 'required': False}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Intro', 'max_length': 400, 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Label', 'max_length': 60, 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'CTA URL', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('marker', 12), ('title', 1), ('intro', 13), ('cta_label', 14), ('cta_url', 15)]], {'icon': 'graduation-cap', 'label': 'Learning teaser'}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 100, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('eyebrow', 17), ('title', 1)]], {'icon': 'list-ul', 'label': 'Methods section head'}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Side Note', 'max_length': 120, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('eyebrow', 17), ('title', 1), ('side_note', 19)]], {'icon': 'cogs', 'label': 'Programs heading'})}, verbose_name='Home Section Headings (CMS)'),
        ),
    ]
