# Generated by Django 5.2.13 on 2026-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_sitelanguage_code_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© 2026 CTC Research. All rights reserved.', help_text='Copyright text in footer bottom', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='CTC Research', help_text='Site name displayed in footer/titles', max_length=200),
        ),
    ]
