# Generated by Django 5.2.16 on 2026-08-19 18:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='head',
            field=wagtail.fields.StreamField([('slider', 10), ('features', 16)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image', 'template': 'blocks/media/image_lite.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'max_length': 100, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200, 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional slide description shown under the title', 'label': 'Description', 'max_length': 400, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Text Alignment', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Button Link', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Video URL', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessible description of the slide image', 'label': 'Alt Text', 'max_length': 200, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('subtitle', 1), ('title', 2), ('description', 3), ('text_alignment', 4), ('button_text', 5), ('button_link', 6), ('video_url', 7), ('alt_text', 8)]], {'icon': 'images', 'label': 'Slide'}), 10: ('wagtail.blocks.StreamBlock', [[('slide', 9)]], {'icon': 'images', 'label': 'Slider'}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-happy', 'help_text': 'e.g., flaticon-happy', 'label': 'Icon Class', 'max_length': 100, 'required': False}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'template': 'blocks/media/image_lite.html'}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 100, 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('icon_class', 11), ('image', 12), ('title', 13), ('description', 14)]], {'icon': 'th-list', 'label': 'Feature'}), 16: ('wagtail.blocks.StreamBlock', [[('feature', 15)]], {'icon': 'th-list', 'label': 'Features'})}, verbose_name='Header Section'),
        ),
    ]
