# Generated by Django 5.2.16 on 2026-08-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_sitesettings_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_accent',
            field=models.CharField(blank=True, default='', help_text='Accented word(s) rendered in the brand color inside the hero heading', max_length=100, verbose_name='Hero Accent'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Hero Heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheading',
            field=models.TextField(blank=True, default='', verbose_name='Hero Subheading'),
        ),
    ]
