# Generated by Django 5.2.13 on 2026-07-04 01:27

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='date', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('institution_name', models.CharField(max_length=80, verbose_name='Institution')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_details', models.CharField(max_length=255, verbose_name='Payment Details')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Owing')),
                ('status', models.BooleanField(default=False, verbose_name='Paid')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-date'],
            },
        ),
    ]
