default:
  CELERY:
    BROKER_URL: "@env CELERY_BROKER_URL redis://localhost:6379/1"
    RESULT_BACKEND: "@env CELERY_RESULT_BACKEND redis://localhost:6379/1"
    ACCEPT_CONTENT: [json]
    TASK_SERIALIZER: json
    RESULT_SERIALIZER: json
    TIMEZONE: UTC
    TASK_TRACK_STARTED: true
    TASK_TIME_LIMIT: 1800
    TASK_SOFT_TIME_LIMIT: 1200
    WORKER_PREFETCH_MULTIPLIER: 1
    WORKER_MAX_TASKS_PER_CHILD: 100
    TASK_DEFAULT_QUEUE: shared
    TASK_ROUTES:
      shared.email.*:
        queue: email
      shared.content.*:
        queue: shared

development:
  CELERY:
    TASK_ALWAYS_EAGER: false
    TASK_EAGER_PROPAGATES: true

production:
  CELERY:
    BROKER_URL: "@env CELERY_BROKER_URL"
    RESULT_BACKEND: "@env CELERY_RESULT_BACKEND"
    TASK_ALWAYS_EAGER: false
    TASK_EAGER_PROPAGATES: true
