# Generated by Django 5.2.16 on 2026-08-07 14:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_founderpage_startuppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='editions',
            field=wagtail.fields.StreamField([('editions', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 80}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Tagline', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Price', 'max_length': 20}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Period', 'max_length': 40, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Features'}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Use a site static URL, for example /static/previews/formints/standard-front.jpg.', 'label': 'Image URL'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'View label', 'max_length': 80, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Alt text', 'max_length': 160, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('url', 9), ('label', 10), ('alt', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Optional screenshots shown on the edition preview page. Keep the list to the most useful product views.', 'label': 'Preview images', 'max_num': 4, 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': "Short deal/discount chip shown on the card (e.g. '50% off · launch'). Works on any edition — course, special, or standard.", 'label': 'Offer badge', 'max_length': 60, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Original price struck through next to the current price (e.g. '$158'). Keep it short — the price row stays on one line.", 'label': 'Old price', 'max_length': 20, 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'CTA label', 'max_length': 80, 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'CTA URL', 'max_length': 255, 'required': False}), 18: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Pick an internal page instead of typing a CTA URL.', 'label': 'CTA page', 'required': False}), 19: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Featured', 'required': False}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('outline', 'Outline — Community/open source'), ('default', 'Default — Standard/Solo'), ('featured', 'Featured — highlighted with accent'), ('managed', 'Managed — ribbon (hosted/Cloud)')], 'help_text': 'The card treatment: outline (Community), default (Standard/Solo), featured (Pro — accent + “most shipped”), managed (Cloud — ribbon).', 'label': 'Visual tier'}), 21: ('wagtail.blocks.StructBlock', [[('name', 3), ('tagline', 4), ('price', 5), ('period', 6), ('features', 8), ('preview_images', 13), ('offer_label', 14), ('offer_old_price', 15), ('cta_label', 16), ('cta_href', 17), ('cta_page', 18), ('featured', 19), ('tier', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'label': 'Editions'}), 23: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('editions', 22)]], {})}, verbose_name='Editions & pricing'),
        ),
    ]
