# Generated by Django 5.2.16 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_productpage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='show_on_home',
            field=models.BooleanField(
                default=True,
                help_text='Show this product in the home preview grid. Turn off for subproducts (e.g. vResume) that stay catalog-only: they still appear on /products/ and the pricing tabs, just not on the homepage cards.',
                verbose_name='Show on home',
            ),
        ),
    ]
