# Generated by Django 5.2.16 on 2026-08-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_merge_20260814_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='logo_style',
            field=models.CharField(choices=[('crest', 'Crest — Formints merchant seal'), ('ribbon', 'Ribbon — Precis LMS award ribbon'), ('isometric', 'Isometric — Loop blocks'), ('orbit', 'Orbit — Syntara AI signal'), ('ascent', 'Ascent — vResume career path'), ('research', 'Research signal — CTC Research evidence path')], default='crest', help_text='The brand mark shown on the product card and detail page — each mark is a constructed symbol tied to the product: crest (Formints merchant seal), ribbon (Precis LMS award ribbon), isometric (Loop blocks), orbit (Syntara AI signal), or ascent (vResume career path).', max_length=20, verbose_name='Logo'),
        ),
    ]
