# Generated by Django 5.2.15 on 2026-08-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_syncconflict_syncqueueitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='core_syncco_branch__46d7a9_idx',
            old_name='core_syncconflict_branch_entity_type_idx',
        ),
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='core_syncco_status_11ca1b_idx',
            old_name='core_syncconflict_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='syncconflict',
            new_name='core_syncco_node_id_bf36d1_idx',
            old_name='core_syncconflict_node_id_idx',
        ),
        migrations.RenameIndex(
            model_name='syncqueueitem',
            new_name='core_syncqu_status_364f0a_idx',
            old_name='core_syncqueueitem_status_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='syncqueueitem',
            new_name='core_syncqu_branch__0a8929_idx',
            old_name='core_syncqueueitem_branch_status_idx',
        ),
        migrations.AlterField(
            model_name='branch',
            name='pos_type',
            field=models.CharField(choices=[('formint-pos', 'Formint POS'), ('pos-solo', 'POS Solo'), ('pos-full', 'POS Full'), ('pos-mini', 'POS Mini')], default='formint-pos', max_length=20, verbose_name='POS type'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='node_type',
            field=models.CharField(choices=[('formint-pos', 'Formint POS'), ('pos-solo', 'POS Solo'), ('pos-full', 'POS Full'), ('pos-minimal', 'POS Minimal'), ('cloud-server', 'Cloud Server'), ('external', 'External')], default='formint-pos', max_length=20, verbose_name='node type'),
        ),
    ]
