http:
  routers:
    structa-site-http:
      rule: 'Host(`structa.cloud`) || Host(`www.structa.cloud`) || Host(`core.structa.cloud`)'
      entryPoints: [web]
      middlewares: [redirect-to-https]
      service: structa-site-service
      priority: 10
    structa-site-https:
      rule: 'Host(`structa.cloud`) || Host(`www.structa.cloud`) || Host(`core.structa.cloud`)'
      entryPoints: [web-secure]
      middlewares: [compress, csrf-headers, security-headers]
      service: structa-site-service
      tls:
        domains:
          - main: 'structa.cloud'
            sans: ['*.structa.cloud']
    structa-media-http:
      rule: '(Host(`structa.cloud`) || Host(`www.structa.cloud`) || Host(`core.structa.cloud`)) && (PathPrefix(`/static/`) || PathPrefix(`/media/`))'
      entryPoints: [web]
      middlewares: [compress, redirect-to-https]
      service: structa-media-service
      priority: 100
    structa-media-https:
      rule: '(Host(`structa.cloud`) || Host(`www.structa.cloud`) || Host(`core.structa.cloud`)) && (PathPrefix(`/static/`) || PathPrefix(`/media/`))'
      entryPoints: [web-secure]
      middlewares: [compress, security-headers]
      service: structa-media-service
      priority: 100
      tls:
  services:
    structa-site-service:
      loadBalancer:
        servers:
          - url: 'http://lms-web:5071'
        healthCheck:
          path: /health/
          interval: 30s
          timeout: 10s
    structa-media-service:
      loadBalancer:
        servers:
          - url: 'http://shared-media:80'
