# Generated by Django 4.2.30 on 2026-05-20 11:47

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Internal name for the campaign', max_length=255, verbose_name='Campaign Name')),
                ('subject', models.CharField(help_text='Subject line for the email', max_length=255, verbose_name='Email Subject')),
                ('preview_text', models.CharField(blank=True, default='', help_text='Preview text shown in email clients (max 255 chars)', max_length=255, verbose_name='Preview Text')),
                ('body', models.TextField(help_text='HTML content of the email', verbose_name='Email Body')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When the campaign should be sent', null=True, verbose_name='Scheduled At')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the campaign was sent', null=True, verbose_name='Sent At')),
                ('total_sent', models.PositiveIntegerField(default=0, help_text='Number of emails sent', verbose_name='Total Sent')),
                ('total_opened', models.PositiveIntegerField(default=0, help_text='Number of emails opened', verbose_name='Total Opened')),
                ('total_clicked', models.PositiveIntegerField(default=0, help_text='Number of emails with clicks', verbose_name='Total Clicked')),
                ('total_bounced', models.PositiveIntegerField(default=0, help_text='Number of emails bounced', verbose_name='Total Bounced')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('blog_post', models.ForeignKey(blank=True, help_text='Associated blog post for newsletter campaigns', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='blog.blogpage', verbose_name='Blog Post')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('form_background_color', colorfield.fields.ColorField(default='#ffffff', help_text='Background color for the contact form container', image_field=None, max_length=25, samples=None, verbose_name='Form Background Color')),
                ('form_text_color', colorfield.fields.ColorField(default='#000000', help_text='Text color for the form labels and inputs', image_field=None, max_length=25, samples=None, verbose_name='Form Text Color')),
                ('form_button_color', colorfield.fields.ColorField(default='#0d6efd', help_text='Background color for the submit button', image_field=None, max_length=25, samples=None, verbose_name='Button Background Color')),
                ('form_button_text_color', colorfield.fields.ColorField(default='#ffffff', help_text='Text color for the submit button', image_field=None, max_length=25, samples=None, verbose_name='Button Text Color')),
                ('contact_form', wagtail.fields.StreamField([('contact_form', 4)], blank=True, block_lookup={0: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Show Name Field', 'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Show Phone Field', 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Show Subject Field', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Send Message', 'label': 'Submit Button Text', 'max_length': 50}), 4: ('wagtail.blocks.StructBlock', [[('show_name', 0), ('show_phone', 1), ('show_subject', 2), ('button_text', 3)]], {})}, verbose_name='Form Block')),
                ('form_title', wagtail.fields.RichTextField(blank=True, help_text='Optional heading above the form', verbose_name='Form Title')),
                ('form_intro', wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text displayed above the form', verbose_name='Form Introduction')),
                ('button_text', models.CharField(default='Send Message', max_length=50, verbose_name='Submit Button Text')),
                ('success_message', wagtail.fields.RichTextField(blank=True, default="<p>✨ <strong>Your message has wings!</strong></p><p>Thank you for reaching out. Like a carefully sealed envelope,<br/>your words are now in our hands. We'll respond within 24 hours,<br/>bringing thoughtful answers to your thoughtful questions.</p>", help_text='Message shown after successful form submission', verbose_name='Success Message')),
                ('error_message', wagtail.fields.RichTextField(blank=True, default="<p>🔄 <strong>A temporary detour...</strong></p><p>Sometimes even the best-laid plans need a second try.<br/>Your message couldn't be sent, but don't let this pause stop you.<br/>Please try again, or reach us directly through the contact details below.</p>", help_text='Message shown when form submission fails', verbose_name='Error Message')),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL', max_length=500, verbose_name='Map Embed URL')),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('framework', 'Framework'), ('language', 'Language'), ('tool', 'Tool'), ('design', 'Design'), ('other', 'Other')], default='tool', max_length=50)),
                ('proficiency', models.IntegerField(default=50, help_text='Proficiency level 0-100')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrackedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='The actual URL to redirect to', max_length=2048, verbose_name='Original URL')),
                ('url_hash', models.CharField(db_index=True, help_text='Short hash for tracking', max_length=32, unique=True, verbose_name='URL Hash')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Total number of clicks', verbose_name='Click Count')),
                ('unique_clicks', models.PositiveIntegerField(default=0, help_text='Number of unique clicks (based on IP)', verbose_name='Unique Clicks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_urls', to='connect.campaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Tracked URL',
                'verbose_name_plural': 'Tracked URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('blog_notifications', models.BooleanField(default=True, help_text='Receive notifications when new blog posts are published', verbose_name='Blog Notifications')),
                ('newsletter_notifications', models.BooleanField(default=True, help_text='Receive weekly newsletter updates', verbose_name='Newsletter Notifications')),
                ('project_updates', models.BooleanField(default=False, help_text='Receive updates about new projects and portfolio items', verbose_name='Project Updates')),
                ('confirmation_token', models.CharField(blank=True, default='', max_length=64, verbose_name='Confirmation Token')),
                ('unsubscribe_token', models.CharField(blank=True, default='', max_length=64, verbose_name='Unsubscribe Token')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('source', models.CharField(blank=True, default='', help_text='Where the subscription was created from (e.g., blog, homepage, footer)', max_length=100, verbose_name='Source')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at time of subscription', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/device information at time of subscription', verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='connect_sub_status_81af6d_idx'), models.Index(fields=['confirmation_token'], name='connect_sub_confirm_240b29_idx'), models.Index(fields=['unsubscribe_token'], name='connect_sub_unsubsc_4b97cc_idx'), models.Index(fields=['blog_notifications', 'status'], name='connect_sub_blog_no_4aca19_idx'), models.Index(fields=['newsletter_notifications', 'status'], name='connect_sub_newslet_ddb9ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(db_index=True, help_text='Unique identifier for the form', max_length=50, verbose_name='Form ID')),
                ('data', models.JSONField(default=dict, help_text='JSON containing all submitted form field values', verbose_name='Form Data')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether notification email was sent', verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('page', models.ForeignKey(blank=True, help_text='The page where the form was submitted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='wagtailcore.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_token', models.CharField(db_index=True, help_text='Unique token for tracking opens and clicks', max_length=64, unique=True, verbose_name='Tracking Token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Opened At')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Clicked At')),
                ('bounced_at', models.DateTimeField(blank=True, null=True, verbose_name='Bounced At')),
                ('open_count', models.PositiveIntegerField(default=0, help_text='Number of times the email was opened', verbose_name='Open Count')),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times a link was clicked', verbose_name='Click Count')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', null=True, verbose_name='Error Message')),
                ('bounce_type', models.CharField(blank=True, choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce')], help_text='Type of bounce: hard or soft', max_length=10, null=True, verbose_name='Bounce Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='connect.campaign', verbose_name='Campaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='connect.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Email Delivery',
                'verbose_name_plural': 'Email Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='subscribers',
            field=models.ManyToManyField(help_text='Subscribers to send this campaign to', related_name='campaigns', to='connect.subscriber', verbose_name='Subscribers'),
        ),
        migrations.CreateModel(
            name='URLClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the clicker', verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser and device information', verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, default='', help_text='URL that linked to the tracked URL', max_length=2048, verbose_name='Referrer')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='desktop', max_length=20, verbose_name='Device Type')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Clicked At')),
                ('email_delivery', models.ForeignKey(blank=True, help_text='The email delivery that triggered this click', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_clicks', to='connect.emaildelivery', verbose_name='Email Delivery')),
                ('tracked_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='connect.trackedurl', verbose_name='Tracked URL')),
            ],
            options={
                'verbose_name': 'URL Click',
                'verbose_name_plural': 'URL Clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['tracked_url', 'clicked_at'], name='connect_url_tracked_2f8b82_idx'), models.Index(fields=['email_delivery', 'clicked_at'], name='connect_url_email_d_f3e5de_idx'), models.Index(fields=['device_type'], name='connect_url_device__fcc14b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trackedurl',
            index=models.Index(fields=['url_hash'], name='connect_tra_url_has_3f0e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedurl',
            index=models.Index(fields=['campaign', 'click_count'], name='connect_tra_campaig_ce989d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedurl',
            unique_together={('campaign', 'original_url')},
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form_id', 'submitted_at'], name='connect_for_form_id_101148_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['email_sent'], name='connect_for_email_s_eaed7b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['tracking_token'], name='connect_ema_trackin_21c170_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['campaign', 'status'], name='connect_ema_campaig_840b20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emaildelivery',
            unique_together={('campaign', 'subscriber')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='connect_cam_status_0c4487_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['scheduled_at', 'status'], name='connect_cam_schedul_88bd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by', 'created_at'], name='connect_cam_created_d6e297_idx'),
        ),
    ]
