#!/usr/bin/env python3
"""
Generate README.md namespace documentation for every directory in the libs packages.

For each directory containing Python files, creates a README.md describing:
- The namespace path
- What the module/package provides
- Public classes and functions (from __init__.py or by scanning)
- Usage example

Usage: python scripts/libs/generate_namespace_docs.py [--dry-run]
"""
import ast
import sys
from pathlib import Path

LIBS = Path("/root/site/libs")

PACKAGES = {
    "django-osoul":  ("django_osoul",  "Django foundation layer"),
    "django-rseal":  ("django_rseal",  "Django automation engine"),
    "django-grep":   ("django_grep",   "Django testing framework"),
    "crafts-ai":     ("crafts_ai",     "Standalone AI/MCP toolkit"),
}

DRY_RUN = "--dry-run" in sys.argv


def get_public_names(init_path: Path) -> list[str]:
    """Extract __all__ or top-level names from __init__.py."""
    if not init_path.exists():
        return []
    try:
        tree = ast.parse(init_path.read_text(encoding="utf-8"))
    except Exception:
        return []

    # Try __all__ first
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    if isinstance(node.value, ast.List):
                        return [
                            elt.value for elt in node.value.elts
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str)
                        ]

    # Fall back: top-level class/function names
    names = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                names.append(node.name)
    return names[:10]  # cap at 10


def get_module_docstring(init_path: Path) -> str:
    """Extract module docstring from __init__.py."""
    if not init_path.exists():
        return ""
    try:
        tree = ast.parse(init_path.read_text(encoding="utf-8"))
        return ast.get_docstring(tree) or ""
    except Exception:
        return ""


def get_submodules(directory: Path) -> list[str]:
    """List immediate Python submodules/subpackages."""
    items = []
    for child in sorted(directory.iterdir()):
        if child.name.startswith("_") or child.name.startswith("."):
            continue
        if child.is_dir() and (child / "__init__.py").exists():
            items.append(f"`{child.name}/`")
        elif child.suffix == ".py" and not child.name.startswith("_"):
            items.append(f"`{child.stem}`")
    return items


def namespace_from_path(src_root: Path, directory: Path, pkg_namespace: str) -> str:
    """Compute the Python namespace for a directory."""
    try:
        rel = directory.relative_to(src_root)
        parts = list(rel.parts)
        return ".".join([pkg_namespace] + parts)
    except ValueError:
        return pkg_namespace


def write_readme(directory: Path, src_root: Path, pkg_name: str,
                 pkg_namespace: str, pkg_desc: str) -> None:
    """Write a README.md for a single directory."""
    readme_path = directory / "README.md"

    namespace = namespace_from_path(src_root, directory, pkg_namespace)
    init_path = directory / "__init__.py"
    docstring = get_module_docstring(init_path)
    public_names = get_public_names(init_path)
    submodules = get_submodules(directory)

    # Build content
    lines = [
        f"# `{namespace}`",
        "",
        f"> Part of **{pkg_name}** — {pkg_desc}",
        "",
    ]

    if docstring:
        # Take first paragraph only
        first_para = docstring.split("\n\n")[0].strip().replace("\n", " ")
        lines += [first_para, ""]

    if submodules:
        lines += ["## Contents", ""]
        for sub in submodules:
            lines.append(f"- {sub}")
        lines.append("")

    if public_names:
        lines += ["## Public API", ""]
        for name in public_names:
            lines.append(f"- `{name}`")
        lines.append("")

    lines += [
        "## Usage",
        "",
        "```python",
        f"from {namespace} import ...",
        "```",
        "",
        "---",
        f"*Auto-generated by `scripts/libs/generate_namespace_docs.py`*",
    ]

    content = "\n".join(lines) + "\n"

    if DRY_RUN:
        print(f"[dry-run] would write {readme_path.relative_to(LIBS)}")
        return

    readme_path.write_text(content, encoding="utf-8")
    print(f"  wrote {readme_path.relative_to(LIBS)}")


def process_package(pkg_dir_name: str, pkg_namespace: str, pkg_desc: str) -> None:
    pkg_dir = LIBS / pkg_dir_name
    if not pkg_dir.exists():
        print(f"  skip {pkg_dir_name} (not found)")
        return

    # Find src root
    src_root = pkg_dir / "src" / pkg_namespace
    if not src_root.exists():
        # nawaai uses flat layout
        src_root = pkg_dir / pkg_namespace
    if not src_root.exists():
        print(f"  skip {pkg_dir_name} (src root not found)")
        return

    print(f"\n[{pkg_dir_name}] scanning {src_root.relative_to(LIBS)}")

    # Walk all subdirectories that are Python packages
    for directory in sorted(src_root.rglob("*")):
        if not directory.is_dir():
            continue
        if "__pycache__" in str(directory):
            continue
        if not (directory / "__init__.py").exists():
            continue
        write_readme(directory, src_root, pkg_dir_name, pkg_namespace, pkg_desc)

    # Also write for the src root itself
    write_readme(src_root, src_root.parent, pkg_dir_name, pkg_namespace, pkg_desc)


def main():
    print("=== Generating namespace README.md files ===")
    if DRY_RUN:
        print("(dry-run mode — no files written)")

    for pkg_dir_name, (pkg_namespace, pkg_desc) in PACKAGES.items():
        process_package(pkg_dir_name, pkg_namespace, pkg_desc)

    print("\n✓ Done")


if __name__ == "__main__":
    main()
