# Generated by Django 5.2.13 on 2026-07-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privacyconsent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='privacyconsent',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='privacyconsent',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='termsconsent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='termsconsent',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='termsconsent',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='PrivacyConsent',
        ),
        migrations.DeleteModel(
            name='TermsOfService',
        ),
        migrations.DeleteModel(
            name='TermsConsent',
        ),
    ]
