# Generated by Django 5.2.16 on 2026-08-05 23:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_productpage_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this product from the /products/ listing and pricing tabs while keeping its detail page reachable by direct link (e.g. internal libraries like ceptor-ai).', verbose_name='Hidden from catalog'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='logo_style',
            field=models.CharField(choices=[('mark', 'Mark (default)'), ('crest', 'Crest'), ('ribbon', 'Ribbon'), ('isometric', 'Isometric')], default='mark', help_text='The brand mark shown on the product card and detail page: a crest (e.g. Formints), a ribbon (e.g. Precis LMS), an isometric shape (e.g. Loop), or the default mark.', max_length=20, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='status',
            field=models.CharField(choices=[('live', 'Live / released'), ('development', 'Under development')], default='live', help_text='Set to “Under development” to show the amber caution badge + warning banner. CAUTION: development products are previews — their APIs, editions and pricing may change before release.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact',
            field=wagtail.fields.StreamField([('contact', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('hours', 'Working hours')], 'label': 'Type'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Value', 'max_length': 255}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Link', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('method_type', 3), ('label', 4), ('value', 5), ('href', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Contact methods'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Form title', 'max_length': 200, 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Form description', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Topic', 'max_length': 120}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Options for the “What can we help with?” select — one per product or service line (e.g. Formints POS, Precis LMS, Loop CMS, Website building).', 'label': 'Form topic choices', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('methods', 8), ('form_title', 9), ('form_description', 10), ('topics', 12)]], {})}, verbose_name='Contact section'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='editions',
            field=wagtail.fields.StreamField([('editions', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 80}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Tagline', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Price', 'max_length': 20}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Period', 'max_length': 40, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Features'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'CTA label', 'max_length': 80, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'CTA URL', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Featured', 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('outline', 'Outline — Community/open source'), ('default', 'Default — Standard/Solo'), ('featured', 'Featured — highlighted with accent'), ('managed', 'Managed — ribbon (hosted/Cloud)')], 'help_text': 'The card treatment: outline (Community), default (Standard/Solo), featured (Pro — accent + “most shipped”), managed (Cloud — ribbon).', 'label': 'Visual tier'}), 13: ('wagtail.blocks.StructBlock', [[('name', 3), ('tagline', 4), ('price', 5), ('period', 6), ('features', 8), ('cta_label', 9), ('cta_href', 10), ('featured', 11), ('tier', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Editions'}), 15: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('editions', 14)]], {})}, verbose_name='Editions & pricing'),
        ),
    ]
