# Generated by Django 5.2.16 on 2026-08-14 02:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0031_alter_blogpostpage_snippets"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="badges",
            field=wagtail.fields.StreamField(
                [("badges", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Eyebrow", "max_length": 80, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 200, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Badge text, e.g. 'Best POS 2026' or '5-star rated'.",
                            "label": "Label",
                            "max_length": 120,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional second line, e.g. 'G2 · 4.9/5 from 1,200 reviews'.",
                            "label": "Sub-label",
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("star", "Star"),
                                ("badge", "Badge / seal"),
                                ("award", "Award / trophy"),
                                ("shield", "Shield / trust"),
                                ("check", "Check / verified"),
                                ("flame", "Flame / hot"),
                                ("sparkle", "Sparkle / new"),
                                ("icon", "Custom icon"),
                            ],
                            "help_text": "Icon shown next to the label. 'Custom icon' lets you enter a name/class.",
                            "label": "Icon",
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon name/class when kind is 'Custom icon', e.g. 'ph-medal'.",
                            "label": "Custom icon",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("neutral", "Neutral"),
                                ("primary", "Primary"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("danger", "Danger"),
                                ("gold", "Gold / award"),
                            ],
                            "help_text": "Colour treatment of the badge chip.",
                            "label": "Tone",
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 0,
                            "help_text": "Render N filled stars instead of the icon (0 = icon only).",
                            "label": "Stars",
                            "max_value": 5,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 3),
                                ("sublabel", 4),
                                ("kind", 5),
                                ("icon", 6),
                                ("tone", 7),
                                ("stars", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {"label": "Badges"}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 0),
                                ("title", 1),
                                ("description", 2),
                                ("badges", 10),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="A row of award/star/trust chips (stars, medals, seals, verified checks) shown under the section heading — social proof band.",
                verbose_name="Badges & awards",
            ),
        ),
        migrations.AddField(
            model_name="featurespage",
            name="badges",
            field=wagtail.fields.StreamField(
                [("badges", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Eyebrow", "max_length": 80, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 200, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Badge text, e.g. 'Best POS 2026' or '5-star rated'.",
                            "label": "Label",
                            "max_length": 120,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional second line, e.g. 'G2 · 4.9/5 from 1,200 reviews'.",
                            "label": "Sub-label",
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("star", "Star"),
                                ("badge", "Badge / seal"),
                                ("award", "Award / trophy"),
                                ("shield", "Shield / trust"),
                                ("check", "Check / verified"),
                                ("flame", "Flame / hot"),
                                ("sparkle", "Sparkle / new"),
                                ("icon", "Custom icon"),
                            ],
                            "help_text": "Icon shown next to the label. 'Custom icon' lets you enter a name/class.",
                            "label": "Icon",
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon name/class when kind is 'Custom icon', e.g. 'ph-medal'.",
                            "label": "Custom icon",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("neutral", "Neutral"),
                                ("primary", "Primary"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("danger", "Danger"),
                                ("gold", "Gold / award"),
                            ],
                            "help_text": "Colour treatment of the badge chip.",
                            "label": "Tone",
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 0,
                            "help_text": "Render N filled stars instead of the icon (0 = icon only).",
                            "label": "Stars",
                            "max_value": 5,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 3),
                                ("sublabel", 4),
                                ("kind", 5),
                                ("icon", 6),
                                ("tone", 7),
                                ("stars", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {"label": "Badges"}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 0),
                                ("title", 1),
                                ("description", 2),
                                ("badges", 10),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="A row of award/star/trust chips (stars, medals, seals, verified checks) shown under the section heading — social proof band.",
                verbose_name="Badges & awards",
            ),
        ),
        migrations.AddField(
            model_name="productspage",
            name="badges",
            field=wagtail.fields.StreamField(
                [("badges", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Eyebrow", "max_length": 80, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 200, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Badge text, e.g. 'Best POS 2026' or '5-star rated'.",
                            "label": "Label",
                            "max_length": 120,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional second line, e.g. 'G2 · 4.9/5 from 1,200 reviews'.",
                            "label": "Sub-label",
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("star", "Star"),
                                ("badge", "Badge / seal"),
                                ("award", "Award / trophy"),
                                ("shield", "Shield / trust"),
                                ("check", "Check / verified"),
                                ("flame", "Flame / hot"),
                                ("sparkle", "Sparkle / new"),
                                ("icon", "Custom icon"),
                            ],
                            "help_text": "Icon shown next to the label. 'Custom icon' lets you enter a name/class.",
                            "label": "Icon",
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Icon name/class when kind is 'Custom icon', e.g. 'ph-medal'.",
                            "label": "Custom icon",
                            "max_length": 80,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("neutral", "Neutral"),
                                ("primary", "Primary"),
                                ("success", "Success"),
                                ("warning", "Warning"),
                                ("danger", "Danger"),
                                ("gold", "Gold / award"),
                            ],
                            "help_text": "Colour treatment of the badge chip.",
                            "label": "Tone",
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 0,
                            "help_text": "Render N filled stars instead of the icon (0 = icon only).",
                            "label": "Stars",
                            "max_value": 5,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 3),
                                ("sublabel", 4),
                                ("kind", 5),
                                ("icon", 6),
                                ("tone", 7),
                                ("stars", 8),
                            ]
                        ],
                        {},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {"label": "Badges"}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 0),
                                ("title", 1),
                                ("description", 2),
                                ("badges", 10),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="A row of award/star/trust chips (stars, medals, seals, verified checks) shown under the section heading — social proof band.",
                verbose_name="Badges & awards",
            ),
        ),
    ]
