# Generated by Django 5.2.13 on 2026-07-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceptor_ai', '0204_backgroundtasklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundTaskLog',
        ),
    ]
