# Generated by Django 6.0.4 on 2026-04-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
    ]

    operations = [
    ]
