# Generated by Django 5.2.16 on 2026-08-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_add_nav_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='companypage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='featurespage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='featurespage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='privacypage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='privacypage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='productspage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='productspage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='projectspage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='projectspage',
            name='show_in_nav',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='nav_order',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='show_in_nav',
        ),
    ]
