# Generated by Django 5.2.16 on 2026-08-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_productpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyPage',
        ),
    ]
