# Generated by Django 5.2.16 on 2026-08-06 02:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_teampage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero', wagtail.fields.StreamField([('hero', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Badge', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Primary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Secondary CTA', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Trusted-by text', 'max_length': 160, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('subtitle', 2), ('primary_cta', 6), ('secondary_cta', 7), ('trusted_by', 8)]], {})}, verbose_name='Hero')),
                ('cta', wagtail.fields.StreamField([('cta', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 5: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Primary CTA', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Secondary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('primary_cta', 5), ('secondary_cta', 6)]], {})}, verbose_name='Call to action')),
                ('display_mode', models.CharField(choices=[('page', 'Full page'), ('modal', 'Modal only'), ('both', 'Page + modal')], default='both', help_text='Where this page is surfaced: as its own full page (page), as a modal overlay triggered from product logos/tooltips (modal), or both. Modal-only hides the full-page affordance in the modal.', max_length=10, verbose_name='Display mode')),
            ],
            options={
                'verbose_name': 'Brand page',
                'verbose_name_plural': 'Brand pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
