# Generated by Django 5.2.16 on 2026-08-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_productpage_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='display_mode',
            field=models.CharField(choices=[('page', 'Full page'), ('modal', 'Modal only'), ('both', 'Page + modal')], default='both', help_text='Where this page is surfaced: as its own full page (page), as a modal overlay triggered from product logos/tooltips (modal), or both. Modal-only hides the full-page affordance in the modal.', max_length=10, verbose_name='Display mode'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='display_mode',
            field=models.CharField(choices=[('page', 'Full page'), ('modal', 'Modal only'), ('both', 'Page + modal')], default='both', help_text='Where this page is surfaced: as its own full page (page), as a modal overlay triggered from product logos/tooltips (modal), or both. Modal-only hides the full-page affordance in the modal.', max_length=10, verbose_name='Display mode'),
        ),
    ]
