# Generated by Django 5.2.16 on 2026-08-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('content', '0010_alter_sitelanguage_code'),
    ]

    operations = [
        # ── SocialLink: add icon_svg field, alter platform choices (tiktok) ──
        migrations.AddField(
            model_name='sociallink',
            name='icon_svg',
            field=models.CharField(blank=True, default='', help_text="Path to SVG icon (e.g., '/assets/img/icons/github.svg')", max_length=200),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('other', 'Other')], default='github', max_length=20),
        ),

        # ── FusionBranding: new Wagtail snippet ──
        migrations.CreateModel(
            name='FusionBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Structa Cloud', help_text='Brand name used in the header and meta titles', max_length=100)),
                ('company_name', models.CharField(default='Structa Cloud', help_text='Legal company name for footer copyright', max_length=100)),
                ('creator_name', models.CharField(default='Mahmoud Ezzat', help_text='Creator/author name for meta tags and credits', max_length=100)),
                ('primary_color', models.CharField(default='#0B57D0', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#5b21b6', help_text='Secondary accent color (hex)', max_length=7)),
                ('favicon', models.ImageField(blank=True, help_text='Upload a favicon image', upload_to='branding/')),
                ('logo', models.ForeignKey(blank=True, help_text='Brand logo (overrides SiteSettings logo when set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'fusion branding',
                'verbose_name_plural': 'fusion branding',
            },
        ),
    ]
