# Generated by Django 5.2.16 on 2026-08-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_sitesettings_footer_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, default='', help_text="CSS class for icon font (e.g., 'fab fa-github')", max_length=100),
        ),
    ]
