# Generated by Django 5.2.13 on 2026-07-28 11:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('layout', models.CharField(choices=[('default', 'Default (Header + Content + Footer)'), ('full_width', 'Full Width (Edge-to-edge)'), ('sidebar', 'Sidebar (Content + Sidebar)'), ('blank', 'Blank (Content only)')], default='default', help_text='Which fusion layout template to render this page with.', max_length=20)),
                ('fusion_render_first', models.BooleanField(default=False, help_text='Server-render HTML before Next.js hydration.')),
                ('fragment_name', models.CharField(blank=True, default='', help_text='Dotted fragment identifier. Auto-derived from slug if blank.', max_length=255)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Include in navigation menus.')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Optional inline CSS for this page only.')),
                ('hero_heading', models.CharField(blank=True, default='Welcome to Fusion CMS', help_text='Main hero heading.', max_length=255)),
                ('hero_subheading', models.TextField(blank=True, default='A modern content management platform powered by django-fusion and django-bolt.', help_text='Supporting text below the hero heading.')),
            ],
            options={
                'verbose_name': 'Fusion CMS Home Page',
                'verbose_name_plural': 'Fusion CMS Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FusionContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('layout', models.CharField(choices=[('default', 'Default (Header + Content + Footer)'), ('full_width', 'Full Width (Edge-to-edge)'), ('sidebar', 'Sidebar (Content + Sidebar)'), ('blank', 'Blank (Content only)')], default='default', help_text='Which fusion layout template to render this page with.', max_length=20)),
                ('fusion_render_first', models.BooleanField(default=False, help_text='Server-render HTML before Next.js hydration.')),
                ('fragment_name', models.CharField(blank=True, default='', help_text='Dotted fragment identifier. Auto-derived from slug if blank.', max_length=255)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Include in navigation menus.')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Optional inline CSS for this page only.')),
                ('body', wagtail.fields.RichTextField(blank=True, default='', help_text='Main page content.')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Optional featured image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Fusion CMS Content Page',
                'verbose_name_plural': 'Fusion CMS Content Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
