# Generated by Django 5.2.15 on 2026-08-26 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fusion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('jti', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for JWT token', unique=True, verbose_name='JWT ID')),
                ('token', models.TextField(blank=True, help_text='Token value for authentication', null=True)),
                ('token_type', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh'), ('sliding', 'Sliding')], help_text='Type of token', max_length=10)),
                ('secret', models.CharField(blank=True, help_text='Secure secret for token validation', max_length=64, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('usage', models.CharField(choices=[('api', 'API'), ('web', 'Web'), ('mobile', 'Mobile')], default='api', help_text='Usage context for the token', max_length=20)),
                ('session_token', models.CharField(blank=True, db_index=True, help_text='Session ID associated with the token', max_length=64, null=True)),
                ('preferences', models.JSONField(blank=True, default=list, help_text='Token preferences and metadata')),
                ('iat', models.DateTimeField(auto_now_add=True, help_text='When the token was issued', verbose_name='Issued At')),
                ('exp', models.DateTimeField(blank=True, help_text='When the token expires', null=True, verbose_name='Expires At')),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time the token was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent token (refresh token for access tokens)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_fusion.token')),
                ('user', models.ForeignKey(help_text='The user this token was issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bearer Token',
                'verbose_name_plural': 'Bearer Tokens',
                'db_table': 'tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'token_type', 'is_revoked'], name='tokens_user_id_d54023_idx'), models.Index(fields=['jti'], name='tokens_jti_910755_idx'), models.Index(fields=['session_token'], name='tokens_session_5958d0_idx'), models.Index(fields=['exp'], name='tokens_exp_e89627_idx'), models.Index(fields=['created_at'], name='tokens_created_a3c85e_idx')],
            },
        ),
    ]
