# Generated by Django 5.2.16 on 2026-09-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_fusion', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
