# Generated by Django 5.2.16 on 2026-08-13 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_finance_workflow_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('queue_name', models.CharField(default='default', max_length=100)),
                ('site_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='queued', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site_name', '-created_at'], name='core_taskex_site_na_0eb852_idx'), models.Index(fields=['task_name', '-created_at'], name='core_taskex_task_na_34fe2c_idx')],
            },
        ),
    ]
