# Generated by Django 6.1 on 2026-08-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emailaccount_emailmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'audit log entry', 'verbose_name_plural': 'audit log entries'},
        ),
        migrations.AlterModelOptions(
            name='emailaccount',
            options={'ordering': ['provider', 'email'], 'verbose_name': 'email account', 'verbose_name_plural': 'email accounts'},
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['-received_at'], 'verbose_name': 'email message', 'verbose_name_plural': 'email messages'},
        ),
        migrations.AlterModelOptions(
            name='savedview',
            options={'ordering': ['resource', 'name'], 'verbose_name': 'saved view', 'verbose_name_plural': 'saved views'},
        ),
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'ordering': ['-created_at'], 'verbose_name': 'task execution', 'verbose_name_plural': 'task executions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'ordering': ['-created_at'], 'verbose_name': 'webhook', 'verbose_name_plural': 'webhooks'},
        ),
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'ordering': ['-created_at'], 'verbose_name': 'webhook delivery', 'verbose_name_plural': 'webhook deliveries'},
        ),
        migrations.AlterModelOptions(
            name='workflowdefinition',
            options={'ordering': ['name'], 'verbose_name': 'workflow definition', 'verbose_name_plural': 'workflow definitions'},
        ),
        migrations.AlterModelOptions(
            name='workflowrun',
            options={'ordering': ['-queued_at'], 'verbose_name': 'workflow run', 'verbose_name_plural': 'workflow runs'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['name'], 'verbose_name': 'workspace', 'verbose_name_plural': 'workspaces'},
        ),
    ]
