# Generated by Django 5.2.11 on 2026-02-12 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CI', '0002_cart'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(editable=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CI.cart', verbose_name='Cart')),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Cart Item',
                'verbose_name_plural': 'Course Cart Items',
            },
        ),
    ]
