# Generated by Django 5.2.11 on 2026-02-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_coursecartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecartitem',
            name='object_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
