from django_grep.comp.blocks.media.image import SimpleImageBlock

# Generated by Django 5.2.11 on 2026-02-16 02:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_coursecartitem_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespage',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, help_text='Use dark color scheme for this page.', verbose_name='Enable Dark Mode'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='has_footer_with_partners',
            field=models.BooleanField(blank=True, default=False, help_text='Display partner logos in the footer section.', null=True, verbose_name='Show Footer Partners'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='header_section',
            field=wagtail.fields.StreamField([('hero', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Intro Text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('subtitle', 1), ('title', 2), ('intro_text', 3)]], {'icon': 'title', 'label': 'Header Section'})}, verbose_name='Header Section'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short summary or introduction for this page.', verbose_name='Intro Text'),
        ),
    ]
