from django_grep.comp.blocks.media.image import SimpleImageBlock

# Generated by Django 5.2.11 on 2026-02-18 02:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_coursespage_enable_dark_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespage',
            name='cta_section',
            field=wagtail.fields.StreamField([('cta', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Title', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Subtitle', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Button Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_link', 4)]], {'icon': 'bullhorn', 'label': 'Call To Action'})}, verbose_name='Call To Action'),
        ),
        migrations.AlterField(
            model_name='coursespage',
            name='header_section',
            field=wagtail.fields.StreamField([('hero', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Intro Text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('subtitle', 1), ('title', 2), ('intro_text', 3)]], {'icon': 'id-card', 'label': 'Header Section'})}, verbose_name='Header Section'),
        ),
    ]
