# Generated by Django 5.2.11 on 2026-02-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_coursespage_cta_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespage',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='show_cta_banner',
        ),
    ]
