# Generated by Django 5.2.11 on 2026-02-19 18:30

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_remove_coursespage_enable_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespage',
            name='professional_solutions',
            field=wagtail.fields.StreamField([('solutions_section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'What We Offer', 'help_text': 'Small text above the main title.', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Professional Solutions for Your Need', 'help_text': 'Main section heading.', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short paragraph describing the services.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('subtitle', 0), ('title', 1), ('description', 2)]], {'icon': 'cogs', 'label': 'Solutions Section'})}, help_text="Configure the 'Professional Solutions' section heading and description.", verbose_name='Professional Solutions'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='show_professional_solutions',
            field=models.BooleanField(default=True, help_text="Display the 'Professional Solutions' services section on this page.", verbose_name='Show Professional Solutions'),
        ),
    ]
