# Generated by Django 5.2.11 on 2026-02-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_coursespage_professional_solutions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespage',
            name='professional_solutions',
        ),
        migrations.RemoveField(
            model_name='coursespage',
            name='show_professional_solutions',
        ),
    ]
