# Generated by Django 5.2.11 on 2026-02-20 04:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_alter_course_overview_alter_course_preview_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=wagtail.fields.StreamField([('preview_video', 0)], blank=True, block_lookup={0: ('wagtail.embeds.blocks.EmbedBlock', (), {'template': 'django_grep/comp/blocks/media/simple_video.html'})}, help_text='An embedded preview or introduction video.', null=True, verbose_name='Preview Video'),
        ),
        migrations.AlterField(
            model_name='coursespage',
            name='cta_section',
            field=wagtail.fields.StreamField([('cta', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Title', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Subtitle', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Button Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_link', 4)]], {'icon': 'bullhorn', 'label': 'Call To Action'})}, verbose_name='Call To Action'),
        ),
        migrations.AlterField(
            model_name='coursespage',
            name='head',
            field=wagtail.fields.StreamField([('page_title', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Home', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('page_title_background', 0), ('page_title', 1), ('breadcrumb_home_text', 2)]], {'icon': 'image', 'label': 'Page Title Section'})}, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='coursespage',
            name='header_section',
            field=wagtail.fields.StreamField([('hero', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Intro Text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('subtitle', 1), ('title', 2), ('intro_text', 3)]], {'icon': 'id-card', 'label': 'Header Section'})}, verbose_name='Header Section'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('video', 1), ('image', 2), ('code', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Rich Text'}), 1: ('wagtail.embeds.blocks.EmbedBlock', (), {'template': 'django_grep/comp/blocks/media/simple_video.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add code with syntax highlighting', 'label': 'Code Snippet'})}, verbose_name='Lesson Content'),
        ),
    ]
