# Generated by Django 5.2.11 on 2026-02-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_course_preview_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursespage',
            name='has_footer_with_partners',
        ),
    ]
