# Generated by Django 5.2.11 on 2026-02-27 04:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_remove_coursespage_has_footer_with_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursespage',
            name='head',
            field=wagtail.fields.StreamField([('page_title', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Page Title Background', 'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Page Title', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Home', 'label': 'Breadcrumb Home Text', 'max_length': 50}), 3: ('wagtail.blocks.StructBlock', [[('page_title_background', 0), ('page_title', 1), ('breadcrumb_home_text', 2)]], {'icon': 'image', 'label': 'Page Title Section'})}, max_length=1, null=True, verbose_name='Header Section'),
        ),
    ]
