# Generated by Django 5.2.11 on 2026-02-28 02:55

import django.db.models.deletion
import django_grep.pipelines.models.default
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_alter_coursespage_head'),
        ('pipelines', '0015_coupon_announcementbanner_certificationtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Optional coupon attached to this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='pipelines.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='course',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Auto-calculated: (price - discount) + tax. Do not edit.', max_digits=10, verbose_name='Final Price'),
        ),
        migrations.AddField(
            model_name='course',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage applied after discount (e.g. 15 for 15%).', max_digits=5, verbose_name='Tax %'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('live', models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='First Published At')),
                ('last_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Published At')),
                ('search_description', models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description')),
                ('title', models.CharField(blank=True, help_text='Optional descriptive title for this schedule', max_length=200, verbose_name='Schedule Title')),
                ('schedule_type', models.CharField(choices=[('one_time', 'One-time Session'), ('weekly', 'Weekly Recurring'), ('biweekly', 'Bi-weekly Recurring'), ('monthly', 'Monthly Recurring'), ('custom', 'Custom Pattern')], default='one_time', help_text='Type of schedule pattern', max_length=20, verbose_name='Schedule Type')),
                ('start_date', models.DateField(help_text='First occurrence date', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for recurring schedules', null=True, verbose_name='End Date')),
                ('start_time', models.TimeField(help_text='Session start time', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='Session end time', verbose_name='End Time')),
                ('recurrence_days', models.CharField(blank=True, help_text='Comma-separated days (0=Sunday, 1=Monday, etc.) for weekly recurrence', max_length=50, verbose_name='Recurrence Days')),
                ('recurrence_interval', models.PositiveIntegerField(default=1, help_text='Interval for recurrence (e.g., 2 for every 2 weeks)', verbose_name='Recurrence Interval')),
                ('meeting_platform', models.CharField(choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('webex', 'Webex'), ('jitsi', 'Jitsi Meet'), ('other', 'Other Platform')], default='zoom', max_length=20, verbose_name='Meeting Platform')),
                ('meeting_link', models.URLField(blank=True, help_text='URL for joining the online session', verbose_name='Meeting Link')),
                ('meeting_id', models.CharField(blank=True, help_text='Platform-specific meeting ID', max_length=100, verbose_name='Meeting ID')),
                ('meeting_passcode', models.CharField(blank=True, help_text='Meeting passcode if required', max_length=50, verbose_name='Passcode')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active', verbose_name='Active')),
                ('is_recorded', models.BooleanField(default=False, help_text='Indicates if sessions are recorded', verbose_name='Recorded Session')),
                ('recording_link', models.URLField(blank=True, help_text='Link to session recording', verbose_name='Recording Link')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants allowed', null=True, verbose_name='Maximum Participants')),
                ('location', models.CharField(blank=True, help_text='Physical location for in-person sessions', max_length=200, verbose_name='Location')),
                ('is_online', models.BooleanField(default=True, help_text='Whether this is an online session', verbose_name='Online Session')),
                ('is_hybrid', models.BooleanField(default=False, help_text='Supports both online and in-person attendance', verbose_name='Hybrid Session')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active')),
                ('live', models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='First Published At')),
                ('last_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Published At')),
                ('search_description', models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('title', models.CharField(help_text='The title of the content.', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle for the content.', max_length=200, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, help_text='A brief description of the content.', verbose_name='Description')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for previews and listings.', verbose_name='Excerpt')),
                ('order', models.IntegerField(default=0, help_text='The display order of the content (lower numbers first).', verbose_name='Order')),
                ('is_published', models.BooleanField(default=False, help_text='Indicates whether the content is published and visible to the public.', verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this content was published.', null=True, verbose_name='Published At')),
                ('notes', models.TextField(blank=True, help_text='Additional internal notes about the content.', verbose_name='Internal Notes')),
                ('class_type', models.CharField(choices=[('lecture', 'Lecture'), ('workshop', 'Workshop'), ('lab', 'Lab Session'), ('seminar', 'Seminar'), ('tutorial', 'Tutorial'), ('discussion', 'Discussion'), ('other', 'Other')], default='lecture', max_length=20, verbose_name='Class Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Order within course/module', verbose_name='Sequence')),
                ('objectives', models.TextField(blank=True, help_text='What students will learn in this class', verbose_name='Learning Objectives')),
                ('materials', wagtail.fields.StreamField([('heading', 6), ('paragraph', 13), ('block_quote', 22), ('image', 30), ('video', 35), ('document', 44), ('embed', 51)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the heading text.', 'label': 'Heading Text', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], 'label': 'Heading Level'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Text Alignment', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Add a decorative line below the heading.', 'label': 'Show Divider Line', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': '#3b82f6', 'help_text': 'CSS color for the divider line.', 'label': 'Divider Color', 'max_length': 20, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional icon to display before heading (e.g., 'fas fa-star').", 'label': 'Icon Class', 'max_length': 50, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('alignment', 2), ('show_divider', 3), ('divider_color', 4), ('icon', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote', 'ul', 'ol', 'hr', 'document-link', 'image', 'embed'], 'help_text': 'Enter rich text content.', 'label': 'Content', 'required': True}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left Justified'), ('center', 'Center Aligned'), ('right', 'Right Justified'), ('justify', 'Full Justify')], 'label': 'Text Alignment', 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Apply a drop cap to the first letter.', 'label': 'Drop Cap', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional background color for the paragraph.', 'label': 'Background Color', 'max_length': 20, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional custom text color.', 'label': 'Text Color', 'max_length': 20, 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No Padding'), ('small', 'Small Padding'), ('medium', 'Medium Padding'), ('large', 'Large Padding')], 'label': 'Padding', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('content', 7), ('alignment', 8), ('drop_cap', 9), ('background_color', 10), ('text_color', 11), ('padding', 12)]], {}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'The quoted text.', 'label': 'Quote Text', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Who said it (e.g., 'John Doe, CEO of Company').", 'label': 'Citation', 'max_length': 200, 'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link for the citation.', 'label': 'Citation URL', 'required': False}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional photo of the person quoted.', 'label': 'Avatar Image', 'required': False}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large Text'), ('border', 'With Border'), ('icon', 'With Quote Icon'), ('highlight', 'Highlighted Background')], 'label': 'Quote Style', 'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left Aligned'), ('center', 'Center Aligned'), ('right', 'Right Aligned')], 'label': 'Alignment', 'required': False}), 20: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Show Quote Icon', 'required': False}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top-left', 'Top Left'), ('top', 'Top Center'), ('left', 'Left Side')], 'label': 'Icon Position', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('quote_text', 14), ('citation', 15), ('citation_url', 16), ('avatar', 17), ('quote_style', 18), ('alignment', 19), ('quote_icon', 20), ('icon_position', 21)]], {}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload or select an image.', 'label': 'Image', 'required': True}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'Descriptive text for screen readers and SEO.', 'label': 'Alternative Text (Alt Text)', 'max_length': 200, 'required': True}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left Aligned'), ('center', 'Center Aligned'), ('right', 'Right Aligned'), ('full', 'Full Width')], 'label': 'Image Alignment', 'required': False}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('rounded', 'Rounded Corners'), ('circle', 'Circular'), ('shadow', 'With Shadow'), ('border', 'With Border'), ('polaroid', 'Polaroid Style')], 'label': 'Image Style', 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'default': '100%', 'help_text': 'CSS value for max-width (e.g., 100%, 800px, 50vw).', 'label': 'Maximum Width', 'max_length': 20, 'required': False}), 28: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Enable lazy loading for better performance.', 'label': 'Lazy Loading', 'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'default': '(max-width: 768px) 100vw, 768px', 'help_text': 'HTML sizes attribute for responsive images.', 'label': 'Responsive Sizes', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('image', 23), ('alternative_text', 24), ('alignment', 25), ('image_style', 26), ('max_width', 27), ('lazy_loading', 28), ('responsive_sizes', 29)]], {}), 31: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL from YouTube, Vimeo, or other embeddable video service.', 'label': 'Embed URL', 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title displayed above or with the video.', 'label': 'Video Title', 'max_length': 200, 'required': False}), 33: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Description displayed with the video.', 'label': 'Video Description', 'required': False}), 34: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Custom thumbnail image. If not provided, will use service thumbnail.', 'label': 'Thumbnail Image', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('embed_url', 31), ('video_title', 32), ('video_description', 33), ('thumbnail_image', 34)]], {}), 36: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Select a document to display.', 'label': 'Document', 'required': True}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': "Override the document's filename as the display title.", 'label': 'Custom Title', 'max_length': 200, 'required': False}), 38: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional description of the document.', 'label': 'Description', 'required': False}), 39: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Show File Icon', 'required': False}), 40: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Show File Size', 'required': False}), 41: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Show Download Count', 'required': False}), 42: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Text Link'), ('button', 'Button'), ('card', 'Card'), ('inline', 'Inline Badge')], 'label': 'Display Style', 'required': False}), 43: ('wagtail.blocks.CharBlock', (), {'default': 'Download', 'label': 'Button Text', 'max_length': 50, 'required': False}), 44: ('wagtail.blocks.StructBlock', [[('document', 36), ('title', 37), ('description', 38), ('show_icon', 39), ('show_size', 40), ('show_download_count', 41), ('button_style', 42), ('button_text', 43)]], {}), 45: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'URL to embed (YouTube, Vimeo, Twitter, etc.).', 'label': 'Embed URL', 'required': True}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption below the embed.', 'label': 'Caption', 'max_length': 200, 'required': False}), 47: ('wagtail.blocks.CharBlock', (), {'default': '100%', 'help_text': 'Maximum width of the embed (e.g., 800px, 100%, 50vw).', 'label': 'Maximum Width', 'max_length': 20, 'required': False}), 48: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Alignment', 'required': False}), 49: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Make the embed responsive (adjust to container width).', 'label': 'Responsive', 'required': False}), 50: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': "Delay loading the embed until it's visible.", 'label': 'Lazy Load', 'required': False}), 51: ('wagtail.blocks.StructBlock', [[('embed_url', 45), ('caption', 46), ('max_width', 47), ('alignment', 48), ('responsive', 49), ('lazy_load', 50)]], {})}, help_text='Additional materials and resources for this class', verbose_name='Class Materials')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Maximum number of students allowed', null=True, verbose_name='Maximum Students')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether attendance is mandatory', verbose_name='Mandatory')),
                ('requires_registration', models.BooleanField(default=True, help_text='Whether students need to register for this class', verbose_name='Requires Registration')),
                ('co_instructors', models.ManyToManyField(blank=True, help_text='Additional instructors assisting with this class', related_name='co_taught_classes', to=settings.AUTH_USER_MODEL, verbose_name='Co-instructors')),
                ('course', models.ForeignKey(help_text='Parent course for this class', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='lms.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('module', models.ForeignKey(blank=True, help_text='Optional parent module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='lms.module', verbose_name='Module')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Classes that should be completed before this one', to='lms.classes', verbose_name='Prerequisites')),
                ('primary_instructor', models.ForeignKey(blank=True, help_text='Main instructor responsible for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_classes', to=settings.AUTH_USER_MODEL, verbose_name='Primary Instructor')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('schedule', models.OneToOneField(help_text='Schedule for this class instance', on_delete=django.db.models.deletion.CASCADE, related_name='class_instance', to='lms.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['course', 'sequence', 'created_at'],
            },
            bases=(models.Model, django_grep.pipelines.models.default.TemplateRenderMixin),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_date', 'start_time'], name='lms_schedul_start_d_687f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_active'], name='lms_schedul_is_acti_ebdf11_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type'], name='lms_schedul_schedul_74a6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['meeting_platform'], name='lms_schedul_meeting_232793_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['course', 'sequence'], name='lms_classes_course__e835bf_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['status'], name='lms_classes_status_4cf911_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['class_type'], name='lms_classes_class_t_81e52a_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['primary_instructor'], name='lms_classes_primary_db9341_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('course', 'sequence')},
        ),
    ]
