# Generated by Django 5.2.16 on 2026-08-04 23:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_delete_companypage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero', wagtail.fields.StreamField([('hero', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Badge', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Primary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Secondary CTA', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Trusted-by text', 'max_length': 160, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('subtitle', 2), ('primary_cta', 6), ('secondary_cta', 7), ('trusted_by', 8)]], {})}, verbose_name='Hero')),
                ('cta', wagtail.fields.StreamField([('cta', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 5: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Primary CTA', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Secondary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('primary_cta', 5), ('secondary_cta', 6)]], {})}, verbose_name='Call to action')),
                ('show_in_nav', models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation')),
                ('nav_order', models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Category')),
                ('post_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('read_time', models.CharField(blank=True, help_text='e.g. 6 min read', max_length=40, verbose_name='Read time')),
                ('excerpt', models.TextField(blank=True, help_text='One-liner shown on the blog index grid card.', verbose_name='Excerpt')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='The post content — paragraphs, headings, lists, code.', verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Blog post page',
                'verbose_name_plural': 'Blog post pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
