# Generated by Django 5.2.16 on 2026-08-05 21:06

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_blogpostpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='category',
            field=models.CharField(choices=[('application', 'Application'), ('platform', 'Platform'), ('library', 'Library')], default='application', help_text='How the product is positioned in the catalog: an Application (desktop/web app), a Platform (hosted service), or a Library (reusable open-source package).', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productspage',
            name='projects',
            field=wagtail.fields.StreamField([('project', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Community / Standard / Pro / Cloud for the POS editions.', 'label': 'Edition', 'max_length': 80, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('website', 'Website'), ('product', 'Product'), ('library', 'Library'), ('infra', 'Infrastructure')], 'label': 'Category'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Repo path', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Feature', 'max_length': 160}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Tick when this capability is reused by other projects in the monorepo.', 'label': 'Shared across the repo', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 6), ('shared', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Features'}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('edition', 1), ('category', 2), ('path', 3), ('url', 4), ('description', 5), ('features', 9)]], {})}, verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='projectspage',
            name='projects',
            field=wagtail.fields.StreamField([('project', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Community / Standard / Pro / Cloud for the POS editions.', 'label': 'Edition', 'max_length': 80, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('website', 'Website'), ('product', 'Product'), ('library', 'Library'), ('infra', 'Infrastructure')], 'label': 'Category'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Repo path', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Feature', 'max_length': 160}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Tick when this capability is reused by other projects in the monorepo.', 'label': 'Shared across the repo', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 6), ('shared', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Features'}), 10: ('wagtail.blocks.StructBlock', [[('name', 0), ('edition', 1), ('category', 2), ('path', 3), ('url', 4), ('description', 5), ('features', 9)]], {})}, verbose_name='Projects'),
        ),
    ]
