# Generated by Django 5.2.15 on 2026-08-06 18:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_brandpage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero', wagtail.fields.StreamField([('hero', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Badge', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Primary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Secondary CTA', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Trusted-by text', 'max_length': 160, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('subtitle', 2), ('primary_cta', 6), ('secondary_cta', 7), ('trusted_by', 8)]], {})}, verbose_name='Hero')),
                ('cta', wagtail.fields.StreamField([('cta', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 5: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Primary CTA', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Secondary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('primary_cta', 5), ('secondary_cta', 6)]], {})}, verbose_name='Call to action')),
                ('phase_number', models.PositiveIntegerField(default=1, verbose_name='Phase number')),
                ('phase_label', models.CharField(choices=[('discovery', 'Discovery'), ('build', 'Build'), ('launch', 'Launch'), ('enhance', 'Enhance')], default='discovery', max_length=20, verbose_name='Phase type')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Phase brief')),
                ('outcomes', models.TextField(blank=True, help_text='One outcome per line, shown as the phase checklist.', verbose_name='Outcomes')),
            ],
            options={
                'verbose_name': 'Delivery phase',
                'verbose_name_plural': 'Delivery phases',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PromptPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero', wagtail.fields.StreamField([('hero', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Badge', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Primary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Secondary CTA', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Trusted-by text', 'max_length': 160, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('subtitle', 2), ('primary_cta', 6), ('secondary_cta', 7), ('trusted_by', 8)]], {})}, verbose_name='Hero')),
                ('cta', wagtail.fields.StreamField([('cta', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 5: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Primary CTA', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Secondary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('primary_cta', 5), ('secondary_cta', 6)]], {})}, verbose_name='Call to action')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('context', wagtail.fields.RichTextField(blank=True, verbose_name='Context')),
                ('output', wagtail.fields.RichTextField(blank=True, verbose_name='Expected output')),
                ('tool', models.CharField(blank=True, help_text='Optional tool or stack label, for example Astro + Wagtail.', max_length=80, verbose_name='Tool / stack')),
            ],
            options={
                'verbose_name': 'Implementation prompt',
                'verbose_name_plural': 'Implementation prompts',
            },
            bases=('wagtailcore.page',),
        ),
    ]
