# Generated by Django 5.2.16 on 2026-08-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_productpage_gallery'),
        ('pages', '0026_blogpostpage_hero_screenshot_url_and_more'),
    ]

    operations = [
    ]
