# Generated by Django 5.2.16 on 2026-08-12 22:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_blogpostpage_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='profile',
            field=wagtail.fields.StreamField([('profile', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'ICP intro', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Persona', 'max_length': 120}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Demographic / role / business type — who they are in detail.', 'label': 'Who'}), 5: ('wagtail.blocks.TextBlock', (), {'help_text': 'Buying habits, pain points, goals and triggers — how they actually operate.', 'label': 'Behaviour'}), 6: ('wagtail.blocks.StructBlock', [[('title', 3), ('who', 4), ('behaviour', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Ideal customer profiles'}), 8: ('wagtail.blocks.TextBlock', (), {'help_text': 'Minimum inventory / data size and the throughput the software can process.', 'label': 'Capacity & scale', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Report', 'max_length': 160}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Financial, supply-chain and marketing reports the product ships.', 'label': 'Dashboards & reports'}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'How invoices reach customers (WhatsApp, email, print) and how loyalty points accrue.', 'label': 'Channels & loyalty', 'required': False}), 12: ('wagtail.blocks.TextBlock', (), {'help_text': 'The marketing voice for this product — distinct per ICP.', 'label': 'Marketing tone', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('icp_intro', 2), ('icps', 7), ('capacity', 8), ('reports', 10), ('channels', 11), ('tone', 12)]], {})}, help_text="The business profile: ideal customer profiles (who + behaviour), capacity & scale, financial/supply-chain reporting, channels & loyalty, and the product's distinct marketing tone.", verbose_name='Product profile'),
        ),
    ]
