# ============================================================
# Alliance Standard Infrastructure (Non-Traefik)
# Simplified setup for local development.
# ============================================================

# ------------------------------------------------------------
# NETWORKS
# ------------------------------------------------------------
networks:
  traefik-net:
    external: true

services:
  # ============================================================
  # POSTGRESQL DATABASE
  # ============================================================
  # ============================================================
  # CORE - Django/Uvicorn Application
  # ============================================================
  core:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: core
    container_name: core
    restart: unless-stopped
    ports:
      - "8280:5080"
    env_file:
      - ./.env
    volumes:
      - ../libs:/libs:rw
      - core_static:/app/assets/staticfiles:rw
      - core_media:/app/assets/media:rw
    environment:
      - RUNNING_ENV=docker
      - RELOAD=${RELOAD:-false}
      - SERVER_ENV=production
      - DEBUG=True
      - PORT=5080
      - DB_HOST=postgres
      - DB_NAME=db_structa
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - RUN_SETUP=true
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - traefik-net

volumes:
  core_static:
  core_media:
