# Generated by Django 6.0.4 on 2026-04-17 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='RelayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relay Configuration',
                'verbose_name_plural': 'Relay Configurations',
                'db_table': 'relay_config',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('backend', models.CharField(choices=[('openai', 'OpenAI'), ('rasa', 'Rasa'), ('echo', 'Echo (dev)')], default='openai', max_length=32)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=8)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crafts_ai.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('label', models.CharField(blank=True, default='work', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crafts_ai.contact')),
            ],
            options={
                'verbose_name': 'Contact Email',
                'verbose_name_plural': 'Contact Emails',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('label', models.CharField(blank=True, default='work', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='crafts_ai.contact')),
            ],
            options={
                'verbose_name': 'Contact Phone',
                'verbose_name_plural': 'Contact Phones',
            },
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='companies', to='crafts_ai.contact')),
            ],
            options={
                'verbose_name': 'Corporate',
                'verbose_name_plural': 'Corporates',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(help_text='Official display name of the company', max_length=200, verbose_name='Company Name')),
                ('legal_name', models.CharField(blank=True, help_text='Official legal name if different from display name', max_length=200, verbose_name='Legal Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of the company name', max_length=200, unique=True, verbose_name='Slug')),
                ('company_type', models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier'), ('partner', 'Partner'), ('vendor', 'Vendor'), ('competitor', 'Competitor'), ('educational', 'Educational Institution'), ('academic', 'Academic Institution'), ('internal', 'Internal Organization'), ('other', 'Other')], default='client', help_text='Primary classification of the company relationship', max_length=20, verbose_name='Company Type')),
                ('website', models.URLField(blank=True, help_text='Primary company website URL', verbose_name='Website')),
                ('email', models.EmailField(blank=True, help_text='General contact email address', max_length=254, verbose_name='General Email')),
                ('phone', models.CharField(blank=True, help_text='Main company phone number', max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Primary business address', verbose_name='Address')),
                ('country', models.CharField(blank=True, help_text='Company headquarters country', max_length=100, verbose_name='Country')),
                ('timezone', models.CharField(blank=True, default='UTC', help_text='Primary business timezone', max_length=50, verbose_name='Timezone')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance & Banking'), ('retail', 'Retail & E-commerce'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('other', 'Other')], default='other', help_text='Primary industry sector', max_length=20, verbose_name='Industry')),
                ('company_size', models.CharField(blank=True, choices=[('micro', 'Micro (1-10)'), ('small', 'Small (11-50)'), ('medium', 'Medium (51-200)'), ('large', 'Large (201-1000)'), ('enterprise', 'Enterprise (1000+)')], help_text='Approximate number of employees', max_length=20, verbose_name='Company Size')),
                ('employee_count', models.PositiveIntegerField(blank=True, help_text='Exact number of employees (if known)', null=True, verbose_name='Employee Count')),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='Year the company was founded', null=True, verbose_name='Founded Year')),
                ('tax_id', models.CharField(blank=True, help_text='Business tax identification number', max_length=100, verbose_name='Tax ID/VAT Number')),
                ('registration_number', models.CharField(blank=True, help_text='Company registration or business number', max_length=100, verbose_name='Registration Number')),
                ('brand_color', models.CharField(blank=True, help_text='Primary brand color in hex format', max_length=7, verbose_name='Brand Color')),
                ('is_displayed', models.BooleanField(default=False, help_text='Display this company in public directories and partner pages', verbose_name='Display Publicly')),
                ('partnership_level', models.CharField(blank=True, choices=[('strategic', 'Strategic Partner'), ('premium', 'Premium Partner'), ('standard', 'Standard Partner'), ('affiliate', 'Affiliate Partner')], help_text='Level of partnership (for partner companies only)', max_length=20, verbose_name='Partnership Level')),
                ('partnership_start_date', models.DateField(blank=True, help_text='When the partnership began', null=True, verbose_name='Partnership Start Date')),
                ('is_educational', models.BooleanField(default=False, help_text='This company is an educational institution', verbose_name='Educational Institution')),
                ('accreditation', models.TextField(blank=True, help_text='Educational accreditations and certifications', verbose_name='Accreditations')),
                ('institution_type', models.CharField(blank=True, choices=[('university', 'University'), ('college', 'College'), ('school', 'School'), ('training', 'Training Center'), ('online', 'Online Institution')], help_text='Type of educational institution', max_length=50, verbose_name='Institution Type')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Annual revenue in local currency', max_digits=15, null=True, verbose_name='Annual Revenue')),
                ('currency', models.CharField(default='USD', help_text='Primary currency for financial data', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Company is currently active and engaged', verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, help_text='Company information has been verified', verbose_name='Verified')),
                ('notes', models.TextField(blank=True, help_text='Additional internal notes about the company', verbose_name='Internal Notes')),
                ('logo', models.ForeignKey(blank=True, help_text='Official company logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Company Logo')),
                ('parent_company', models.ForeignKey(blank=True, help_text='Parent or holding company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='crafts_ai.organization', verbose_name='Parent Company')),
                ('relationship_manager', models.ForeignKey(blank=True, help_text='Primary contact person within our organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Relationship Manager')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(help_text='Official name of the department', max_length=100, verbose_name='Department Name')),
                ('code', models.CharField(blank=True, help_text='Internal department code or abbreviation', max_length=20, verbose_name='Department Code')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the department name', max_length=100, verbose_name='Slug')),
                ('function', models.CharField(choices=[('executive', 'Executive'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('it', 'Information Technology'), ('operations', 'Operations'), ('product', 'Product Development'), ('customer_service', 'Customer Service'), ('r_d', 'Research & Development'), ('legal', 'Legal'), ('other', 'Other')], default='other', help_text='Primary business function of the department', max_length=20, verbose_name='Department Function')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Annual operating budget for the department', max_digits=12, null=True, verbose_name='Annual Budget')),
                ('budget_year', models.PositiveIntegerField(default=2026, help_text='Year for which the budget is allocated', verbose_name='Budget Year')),
                ('mission', models.TextField(blank=True, help_text='Mission statement and primary purpose', verbose_name='Department Mission')),
                ('objectives', models.TextField(blank=True, help_text='Main objectives and goals for the department', verbose_name='Key Objectives')),
                ('location', models.CharField(blank=True, help_text='Primary physical location of the department', max_length=200, verbose_name='Location')),
                ('color', models.CharField(blank=True, default='#6B7280', help_text='Color for visual identification of the department', max_length=7, verbose_name='Department Color')),
                ('employee_count', models.PositiveIntegerField(default=0, help_text='Number of employees in this department', verbose_name='Employee Count')),
                ('team_count', models.PositiveIntegerField(default=0, help_text='Number of teams in this department', verbose_name='Team Count')),
                ('service_count', models.PositiveIntegerField(default=0, help_text='Number of services managed by this department', verbose_name='Service Count')),
                ('deputy_manager', models.ForeignKey(blank=True, help_text='Secondary manager supporting the department head', limit_choices_to={'is_active': True, 'type': 'EMP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Deputy Manager')),
                ('manager', models.ForeignKey(blank=True, help_text='Primary manager responsible for the department', limit_choices_to={'is_active': True, 'type': 'EMP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Department Manager')),
                ('parent_department', models.ForeignKey(blank=True, help_text='Parent department for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='crafts_ai.department', verbose_name='Parent Department')),
                ('services', models.ManyToManyField(blank=True, help_text='Services provided or managed by this department', related_name='departments', to='accounts.service', verbose_name='Department Services')),
                ('company', models.ForeignKey(help_text='Parent company organization', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='crafts_ai.organization', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['company', 'function', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='companies_slug_e0676c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['company_type'], name='companies_company_b23eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry'], name='companies_industr_7891ac_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_displayed'], name='companies_is_disp_2740e2_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_educational'], name='companies_is_educ_dfc6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='companies_is_acti_e9a12b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent_company'], name='companies_parent__ece8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['slug'], name='departments_slug_b4a8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_c59a45_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company'], name='departments_company_d64605_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['function'], name='departments_functio_b775f8_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department'], name='departments_parent__cf33d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_name_per_company'),
        ),
    ]
