# Generated by Django 5.2.16 on 2026-08-04 06:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Platform', 'Support'", max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('discord', 'Discord'), ('other', 'Other')], default='github', max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text="Display name (e.g., 'Follow on GitHub')", max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('icon_class', models.CharField(blank=True, default='', help_text="CSS class for icon (e.g., 'fab fa-github')", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'social link',
                'verbose_name_plural': 'social links',
                'ordering': ['sort_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.footerlinkgroup')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Structa Cloud', help_text='Site name displayed in header/footer', max_length=200)),
                ('site_tagline', models.CharField(blank=True, default='', help_text='Short tagline shown in footer', max_length=300)),
                ('footer_description', models.TextField(blank=True, default='', help_text='Company description in footer')),
                ('footer_address', models.CharField(blank=True, default='', help_text='Physical address', max_length=300)),
                ('footer_phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=50)),
                ('footer_email', models.EmailField(blank=True, default='', help_text='Contact email', max_length=254)),
                ('footer_copyright', models.CharField(default='© 2026 structa.cloud. All rights reserved.', help_text='Copyright text in footer bottom', max_length=200)),
                ('privacy_policy_url', models.CharField(blank=True, default='/privacy', help_text='Link to privacy policy page', max_length=300)),
                ('terms_of_use_url', models.CharField(blank=True, default='', help_text='Link to terms of use page', max_length=300)),
                ('logo', models.ForeignKey(blank=True, help_text='Site logo for header/footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.AddField(
            model_name='footerlinkgroup',
            name='setting',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_link_groups', to='content.sitesettings'),
        ),
    ]
