# Generated by Django 5.2.16 on 2026-08-06 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_seo_analytics_nav_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Subscribed email address (unique).', max_length=254, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to pause this subscription (unsubscribe).', verbose_name='active')),
                ('source', models.CharField(blank=True, choices=[('footer', 'Footer signup'), ('contact', 'Contact form'), ('product', 'Product page'), ('other', 'Other')], default='footer', help_text='Where this address subscribed from.', max_length=40, verbose_name='source')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'newsletter subscriber',
                'verbose_name_plural': 'newsletter subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
