# Generated by Django 5.2.16 on 2026-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_merge_20260808_1005'),
        ('content', '0013_alter_pagetranslation_language_and_more'),
    ]

    operations = [
    ]
