# Generated by Django 5.2.16 on 2026-08-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_merge_20260808_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(help_text='Identifier for the form that was submitted.', max_length=100, verbose_name='Form ID')),
                ('page_id', models.IntegerField(default=0, help_text='ID of the page containing the form.', verbose_name='Page ID')),
                ('page_title', models.CharField(blank=True, help_text='Title of the page containing the form.', max_length=255, verbose_name='Page Title')),
                ('page_url', models.URLField(blank=True, help_text='URL of the page containing the form.', verbose_name='Page URL')),
                ('submitted_data', models.JSONField(blank=True, default=dict, help_text='Form data as JSON.', verbose_name='Submitted Data')),
                ('files_data', models.JSONField(blank=True, default=dict, help_text='Information about uploaded files.', verbose_name='Files Data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, help_text='URL of the page that referred the user.', verbose_name='Referrer')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Whether this submission has been reviewed.', verbose_name='Processed')),
                ('processed_date', models.DateTimeField(blank=True, help_text='When this submission was processed.', null=True, verbose_name='Processed Date')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this submission.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'contact submission',
                'verbose_name_plural': 'contact submissions',
                'ordering': ['-submission_date'],
                'indexes': [models.Index(fields=['form_id'], name='content_con_form_id_9f1854_idx'), models.Index(fields=['page_id'], name='content_con_page_id_33c9c4_idx'), models.Index(fields=['submission_date'], name='content_con_submiss_0ed1eb_idx'), models.Index(fields=['processed'], name='content_con_process_eeeffe_idx')],
            },
        ),
    ]
