# Generated by Django 5.2.16 on 2026-07-30 15:54

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Person Tag',
                'verbose_name_plural': 'Person Tags',
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='TaggedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tagged Person',
                'verbose_name_plural': 'Tagged Persons',
            },
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='teams_is_acti_dd3222_idx',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='live',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='live',
        ),
        migrations.RemoveField(
            model_name='person',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='team',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='live',
        ),
        migrations.RemoveField(
            model_name='team',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='live',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='live',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='live',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teaminvitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddField(
            model_name='taggedperson',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='shared.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='taggedperson',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Skills and tags associated with this profile', through='shared.TaggedPerson', to='taggit.Tag', verbose_name='Tags/Skills'),
        ),
    ]
