networks:
  traefik-net:
    external: true

volumes:
  traefik_acme:

services:
  structa-proxy:
    image: traefik:v3.6
    container_name: structa-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    security_opt:
      - no-new-privileges:true

    volumes:
      - traefik_acme:/etc/traefik/acme
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/certs:/etc/traefik/certs:ro

    environment:
      DOCKER_API_VERSION: "1.44"
      TRAEFIK_ACME_EMAIL: ${TRAEFIK_ACME_EMAIL:-admin@structa.cloud}
      TRAEFIK_LOG_LEVEL: ${TRAEFIK_LOG_LEVEL:-INFO}

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    networks:
      - traefik-net
    command:
      - "--configFile=/etc/traefik/traefik.yml"
