# Generated by Django 5.2.16 on 2026-07-30 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='live',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the content is published and visible.', verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this content.', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first).', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle.', max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
    ]
