# Generated by Django 5.2.13 on 2026-08-02 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_classes_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='classes',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='First Published At'),
        ),
        migrations.AddField(
            model_name='classes',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='classes',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Published At'),
        ),
        migrations.AddField(
            model_name='classes',
            name='live',
            field=models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live'),
        ),
        migrations.AddField(
            model_name='classes',
            name='search_description',
            field=models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description'),
        ),
        migrations.AddField(
            model_name='classes',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Indicates whether the content is published and visible to the public.', verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional internal notes about the content.', verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='order',
            field=models.IntegerField(default=0, help_text='The display order of the content (lower numbers first).', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for the content.', max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
