# Generated by Django 5.2.16 on 2026-08-14 02:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("heading", 2), ("paragraph", 3), ("badges", 14)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("h2", "H2"), ("h3", "H3")],
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("cms.models.ParagraphBlock", (), {}),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 60, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": False},
                            ),
                            6: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"required": False, "rows": 2},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Badge label, e.g. “Top Rated”",
                                    "max_length": 80,
                                    "required": True,
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Supporting line, e.g. “Google Reviews · 4.9”",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Show a star rating (1–5) instead of the icon below.",
                                    "max_value": 5,
                                    "min_value": 1,
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("star", "Star"),
                                        ("award", "Award"),
                                        ("shield", "Shield"),
                                        ("check", "Check"),
                                        ("flame", "Flame"),
                                        ("sparkle", "Sparkle"),
                                    ],
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("gold", "Gold"),
                                        ("primary", "Brand (verdigris)"),
                                        ("success", "Success"),
                                        ("warning", "Warning"),
                                        ("danger", "Danger"),
                                    ],
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 7),
                                        ("sublabel", 8),
                                        ("stars", 9),
                                        ("kind", 10),
                                        ("tone", 11),
                                    ]
                                ],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.ListBlock",
                                (12,),
                                {"label": "Badges"},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 4),
                                        ("title", 5),
                                        ("description", 6),
                                        ("badges", 13),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "CMS page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="light",
                        help_text="Color-scheme mode served to browsers.",
                        max_length=10,
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        default="158 42% 32%",
                        help_text="HSL accent triple (h s% l%) — the verdigris brand token.",
                        max_length=7,
                    ),
                ),
                (
                    "font_pair",
                    models.CharField(
                        choices=[
                            ("brutalist", "Bricolage Grotesque + Public Sans"),
                            ("editorial", "Spectral + Public Sans"),
                            ("mono", "JetBrains Mono + Public Sans"),
                        ],
                        default="brutalist",
                        help_text="Display/body font pairing for server-rendered pages.",
                        max_length=40,
                    ),
                ),
                (
                    "radius",
                    models.CharField(
                        choices=[
                            ("sharp", "Sharp (0.375rem)"),
                            ("round", "Round (1.25rem)"),
                            ("pill", "Pill (999px)"),
                        ],
                        default="round",
                        help_text="Corner radius treatment for cards and buttons.",
                        max_length=10,
                    ),
                ),
                (
                    "density",
                    models.CharField(
                        choices=[
                            ("airy", "Airy"),
                            ("comfortable", "Comfortable"),
                            ("compact", "Compact"),
                        ],
                        default="comfortable",
                        help_text="Vertical rhythm between sections.",
                        max_length=14,
                    ),
                ),
                (
                    "reduced_motion_default",
                    models.BooleanField(
                        default=False,
                        help_text="Serve the reduced-motion stylesheet to all visitors by default.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme settings",
            },
        ),
    ]
