default:
  default: lms-demo
  websites:
    lms-demo:
      aliases: [structa, core, demo, structa.cloud]
      domain: structa.cloud
      port: 5071
      module: LMS
      ssl_enabled: false
      allowed_hosts: [.structa.cloud, structa.cloud, www.structa.cloud, core.structa.cloud, localhost, 127.0.0.1]
      csrf_trusted_origins: [http://structa.cloud, https://structa.cloud, http://www.structa.cloud, https://www.structa.cloud, http://core.structa.cloud, https://core.structa.cloud]
      cors_allowed_origins: [http://structa.cloud, https://structa.cloud, http://www.structa.cloud, https://www.structa.cloud, http://core.structa.cloud, https://core.structa.cloud]
    ctc-research:
      aliases: [ctc, ctc-research, ctc-research.com]
      domain: ctc-research.com
      port: 5070
      module: LMS
      ssl_enabled: false
      allowed_hosts: [ctc-research.com, www.ctc-research.com, arch.ctc-research.com, localhost, 127.0.0.1]
      csrf_trusted_origins: [http://ctc-research.com, https://ctc-research.com, http://www.ctc-research.com, https://www.ctc-research.com, http://arch.ctc-research.com, https://arch.ctc-research.com]
      cors_allowed_origins: [http://ctc-research.com, https://ctc-research.com, http://www.ctc-research.com, https://www.ctc-research.com, http://arch.ctc-research.com, https://arch.ctc-research.com]
    vresume:
      path: VResume
      aliases: [vresume, resume, vresume.structa.cloud]
      domain: vresume.structa.cloud
      port: 5072
      module: CMS
      ssl_enabled: false
      allowed_hosts: [vresume.structa.cloud, www.vresume.structa.cloud, resume.structa.cloud, localhost, 127.0.0.1]
      csrf_trusted_origins: [http://vresume.structa.cloud, https://vresume.structa.cloud, http://www.vresume.structa.cloud, https://www.vresume.structa.cloud, http://resume.structa.cloud, https://resume.structa.cloud]
      cors_allowed_origins: [http://vresume.structa.cloud, https://vresume.structa.cloud, http://www.vresume.structa.cloud, https://www.vresume.structa.cloud, http://resume.structa.cloud, https://resume.structa.cloud]
    customizer:
      path: customizer
      aliases: [cust, template-customizer]
      domain: localhost
      port: 5073
      module: CMS
      ssl_enabled: false
      allowed_hosts: [localhost, 127.0.0.1]
      csrf_trusted_origins: [http://localhost, http://127.0.0.1]
      cors_allowed_origins: [http://localhost, http://127.0.0.1]
    crm:
      path: crm
      aliases: [crm, sales, inventory, crm.structa.cloud]
      domain: crm.structa.cloud
      port: 5074
      module: CMS
      ssl_enabled: false
      allowed_hosts: [crm.structa.cloud, www.crm.structa.cloud, localhost, 127.0.0.1]
      csrf_trusted_origins: [http://crm.structa.cloud, https://crm.structa.cloud, http://www.crm.structa.cloud, https://www.crm.structa.cloud]
      cors_allowed_origins: [http://crm.structa.cloud, https://crm.structa.cloud, http://www.crm.structa.cloud, https://www.crm.structa.cloud]
