# Generated by Django 5.2.16 on 2026-08-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_sitelanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='nav_cta_url',
            field=models.CharField(blank=True, default='/contact/', help_text='CTA button link in header', max_length=300),
        ),
    ]
