# Generated by Django 5.2.16 on 2026-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_fusion_branding_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_banner_enabled',
            field=models.BooleanField(default=False, help_text='Show a site-wide announcement banner above the footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_banner_text',
            field=models.TextField(blank=True, default='', help_text='Announcement text. HTML allowed. Shown when enabled above.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_banner_style',
            field=models.CharField(blank=True, choices=[('', 'None'), ('info', 'Info (blue)'), ('offer', 'Offer (amber)'), ('alert', 'Alert (red)'), ('success', 'Success (green)')], default='', max_length=20, help_text='Visual style for the announcement banner'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_secondary',
            field=models.TextField(blank=True, default='', help_text="Secondary footer text row (e.g., 'Proudly built in MENA region')"),
        ),
    ]
