# Generated by Django 5.2.16 on 2026-08-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="reduced_motion_default",
            field=models.BooleanField(
                default=False,
                help_text="Default the site to reduced motion for visitors who haven't set a preference",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="theme_density",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compact", "Compact"),
                    ("comfortable", "Comfortable"),
                    ("airy", "Airy"),
                ],
                default="comfortable",
                help_text="Vertical spacing density",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="theme_font",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default (Bricolage / Public Sans)"),
                    ("outfit", "Outfit"),
                    ("satoshi", "Satoshi"),
                    ("cabinet", "Cabinet Grotesk"),
                ],
                default="",
                help_text="Display font family preference",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="theme_mode",
            field=models.CharField(
                blank=True,
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                default="system",
                help_text="Default color scheme: follow the OS (system) or force light/dark",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="theme_radius",
            field=models.CharField(
                blank=True,
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("full", "Full (pill)"),
                ],
                default="large",
                help_text="UI corner radius treatment",
                max_length=12,
            ),
        ),
    ]
