# Generated by Django 6.0.4 on 2026-04-17 17:26

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CI', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('lms', '0001_initial'),
        ('pipelines', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Optional coupon attached to this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='pipelines.coupon', verbose_name='Coupon'),
        ),
        migrations.AddField(
            model_name='course',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Large header image for course detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_header_images', to='wagtailimages.image', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Main course image/thumbnail', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_images', to='wagtailimages.image', verbose_name='Course Image'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Instructors'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ForeignKey(help_text='Parent course for this class', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='lms.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='lms.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='coursecartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CI.cart', verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='coursecartitem',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coursecartitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='coursespage',
            name='selected_courses',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select which courses to display on this page. Only published courses will be shown.', related_name='displayed_in_index', to='lms.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lms.lesson'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='lesson',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lms.lesson', verbose_name='Parent Lesson'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lms.course', verbose_name='Parent Course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.module', verbose_name='Parent Module'),
        ),
        migrations.AddField(
            model_name='classes',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Optional parent module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='lms.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='lms.enrollment'),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lms.module'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms.lesson', verbose_name='Lesson'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.quizattempt', verbose_name='Attempt'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='selected_in_answers', to='lms.quizchoice', verbose_name='Selected Choices'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lms.quizquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='lms.quizquestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this review is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lms.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(help_text='The student who submitted this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Student Profile'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_date', 'start_time'], name='lms_schedul_start_d_687f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_active'], name='lms_schedul_is_acti_ebdf11_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type'], name='lms_schedul_schedul_74a6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['meeting_platform'], name='lms_schedul_meeting_232793_idx'),
        ),
        migrations.AddField(
            model_name='classes',
            name='schedule',
            field=models.OneToOneField(help_text='Schedule for this class instance', on_delete=django.db.models.deletion.CASCADE, related_name='class_instance', to='lms.schedule', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialization_icons', to='wagtailimages.image', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='course',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='courses', to='lms.specialization', verbose_name='Specializations'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='lms.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='lms_certifi_certifi_cf2bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', 'issued_at'], name='lms_certifi_user_id_c0a44a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='lms_lessonp_user_id_7b6c07_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['status'], name='lms_lessonp_status_b8a997_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['completed_at'], name='lms_lessonp_complet_bea12b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('order', 'course'), name='unique_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('order', 'module'), name='unique_lesson_order_per_module'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('slug', 'module'), name='unique_slug_per_module'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['enrollment', 'module'], name='lms_modulep_enrollm_a70996_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['status'], name='lms_modulep_status_8f813b_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['progress_percentage'], name='lms_modulep_progres_936512_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['completed_at'], name='lms_modulep_complet_e60a0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('enrollment', 'module')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='lms_quizatt_user_id_46d915_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['attempt_id'], name='lms_quizatt_attempt_19322b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course'], name='reviews_course__4a9337_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rating_17e8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_displayed'], name='reviews_is_disp_a579f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('course', 'profile')},
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['course', 'sequence'], name='lms_classes_course__e835bf_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['status'], name='lms_classes_status_4cf911_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['class_type'], name='lms_classes_class_t_81e52a_idx'),
        ),
        migrations.AddIndex(
            model_name='classes',
            index=models.Index(fields=['primary_instructor'], name='lms_classes_primary_db9341_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('course', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug', 'publication_date'], name='lms_course_slug_0abf74_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'is_featured', 'is_active'], name='lms_course_is_publ_db924e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['difficulty_level', 'language'], name='lms_course_difficu_bf29b7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['price'], name='lms_course_price_f5d9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='lms_course_created_f358f1_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'created_at'], name='lms_wishlis_user_id_feca96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'course')},
        ),
    ]
