# Generated by Django 5.2.17 on 2026-08-15 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0008_apikey_rate_limit_per_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('table_number', models.CharField(blank=True, default='', max_length=50)),
                ('order_type', models.CharField(choices=[('dine-in', 'Dine In'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine-in', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'full_sale_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='parent_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pos_full.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos_full.salegroup'),
        ),
    ]
