# Generated by Django 5.2.17 on 2026-08-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0009_salegroup_sale_parent_sale_sale_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('action', models.CharField(default='push', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In Flight'), ('done', 'Done'), ('failed', 'Failed'), ('dead', 'Dead Letter')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=10)),
                ('last_error', models.TextField(blank=True, default='')),
                ('available_at', models.DateTimeField(blank=True, help_text="Backoff — don't retry before this time", null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'full_outbox_queue',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='full_outbox_status_bcd177_idx'), models.Index(fields=['node_id', 'entity_type'], name='full_outbox_node_id_a3a247_idx')],
            },
        ),
    ]
