# Generated by Django 5.2.17 on 2026-08-15 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0011_gamingstation_gamingtoken_gamingqueueentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining spendable balance.', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=20)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'full_gift_cards',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='full_gift_c_status_505abe_idx')],
            },
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('issue', 'Issue'), ('redeem', 'Redeem'), ('reload', 'Reload'), ('void', 'Void')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed amount: positive = adds balance, negative = spends.', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos_full.giftcard')),
                ('sale', models.ForeignKey(blank=True, help_text='Sale this redemption was applied to (redeem only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to='pos_full.sale')),
            ],
            options={
                'db_table': 'full_gift_card_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gift_card', 'created_at'], name='full_gift_c_gift_ca_baaaca_idx')],
            },
        ),
    ]
