# Generated by Django 5.2.17 on 2026-08-15 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0012_giftcard_giftcardtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display label, e.g. 'T12' or 'Patio 3'.", max_length=100)),
                ('section', models.CharField(choices=[('main', 'Main Hall'), ('patio', 'Patio'), ('bar', 'Bar'), ('terrace', 'Terrace'), ('private', 'Private Room'), ('outdoor', 'Outdoor')], db_index=True, default='main', max_length=20)),
                ('shape', models.CharField(choices=[('round', 'Round'), ('rect', 'Rectangle'), ('square', 'Square'), ('booth', 'Booth')], default='rect', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Seats this table can host.')),
                ('status', models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('closed', 'Closed')], db_index=True, default='free', max_length=20)),
                ('pos_x', models.IntegerField(default=0)),
                ('pos_y', models.IntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_sale', models.ForeignKey(blank=True, help_text='The open sale currently seated at this table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='pos_full.sale')),
            ],
            options={
                'db_table': 'full_restaurant_tables',
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', help_text='Booking name when no Customer record is linked.', max_length=200)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('reservation_time', models.DateTimeField(help_text='When the party is expected to arrive.')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_reservations', to='pos_full.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='pos_full.restauranttable')),
            ],
            options={
                'db_table': 'full_table_reservations',
                'ordering': ['reservation_time'],
            },
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['status', 'section'], name='full_restau_status_e80e96_idx'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='uniq_table_section_name'),
        ),
        migrations.AddIndex(
            model_name='tablereservation',
            index=models.Index(fields=['status', 'reservation_time'], name='full_table__status_f0551a_idx'),
        ),
    ]
