# Generated by Django 5.2.17 on 2026-08-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0013_restauranttable_tablereservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('talabat', 'Talabat'), ('hungerstation', 'HungerStation'), ('careem', 'Careem Food'), ('manual', 'Manual / Own Fleet')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=20)),
                ('base_url', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, default='', help_text='Provider API credential (kept plaintext for local POS config).', max_length=200)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission percentage (0–100).', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'full_delivery_providers',
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_order_id', models.CharField(blank=True, default='', help_text='External order id returned by the provider.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Distance from the branch to the drop-off point.', max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Computed fee from the delivery zone (base + per-km).', max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='pos_full.deliverytype')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='pos_full.deliveryzone')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='pos_full.sale')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='pos_full.deliveryprovider')),
            ],
            options={
                'db_table': 'full_delivery_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='full_delive_status_0d62b1_idx'), models.Index(fields=['provider', 'status'], name='full_delive_provide_508792_idx')],
            },
        ),
    ]
