# Generated by Django 5.2.17 on 2026-08-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0015_timeclockentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text="Friendly kiosk label (e.g. 'Kiosk 1').", max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile'), ('mixed', 'Mixed'), ('credit', 'Store Credit')], default='card', help_text='Default payment method for kiosk checkout.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(blank=True, help_text='Sale created when this session checked out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_sessions', to='pos_full.sale')),
            ],
            options={
                'db_table': 'full_kiosk_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KioskCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosk_cart_items', to='pos_full.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pos_full.kiosksession')),
            ],
            options={
                'db_table': 'full_kiosk_cart_items',
                'ordering': ['id'],
            },
        ),
    ]
