# Generated by Django 5.2.16 on 2026-08-22 17:48

from django.db import migrations


def seed_default_plans(apps, schema_editor):
    CenterPlan = apps.get_model("tenants", "CenterPlan")
    # Only seed if no plans exist (idempotent)
    if CenterPlan.objects.exists():
        return

    plans = [
        {
            "name": "Free",
            "slug": "free",
            "max_courses": 5,
            "max_instructors": 1,
            "max_students": 50,
            "custom_domain": False,
            "custom_branding": False,
            "analytics": False,
            "trial_days": 14,
            "features": {
                "icon": "rocket",
                "description": "Start teaching today — no credit card required.",
                "highlights": [
                    "Up to 5 published courses",
                    "1 instructor account",
                    "50 enrolled students",
                    "Basic landing page",
                    "Built-in student auth",
                ],
            },
        },
        {
            "name": "Starter",
            "slug": "starter",
            "max_courses": 25,
            "max_instructors": 5,
            "max_students": 500,
            "custom_domain": False,
            "custom_branding": True,
            "analytics": False,
            "trial_days": 14,
            "features": {
                "icon": "zap",
                "description": "For growing training teams with custom branding.",
                "highlights": [
                    "Up to 25 published courses",
                    "5 instructor accounts",
                    "500 enrolled students",
                    "Custom logo + brand colors",
                    "Built-in student auth + MFA",
                ],
            },
        },
        {
            "name": "Pro",
            "slug": "pro",
            "max_courses": 0,
            "max_instructors": 0,
            "max_students": 0,
            "custom_domain": True,
            "custom_branding": True,
            "analytics": True,
            "trial_days": 14,
            "features": {
                "icon": "crown",
                "description": "Unlimited everything — your own domain, full analytics.",
                "highlights": [
                    "Unlimited courses & instructors",
                    "Unlimited students",
                    "Custom domain (acme.com)",
                    "Full branding control",
                    "Student progress analytics",
                    "Priority support",
                ],
            },
        },
    ]
    for plan in plans:
        CenterPlan.objects.create(**plan)


def remove_default_plans(apps, schema_editor):
    CenterPlan = apps.get_model("tenants", "CenterPlan")
    CenterPlan.objects.filter(slug__in=["free", "starter", "pro"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_plans, remove_default_plans),
    ]