"""Generated by Django 4.2 on 2026-07-25 14:30

Creates the Video and VideoCaption models for LMS video hosting.
"""

from django.db import migrations, models
import django.db.models.deletion
import plugins.lms.models.video


class Migration(migrations.Migration):
    """Add Video and VideoCaption models for lesson video hosting."""

    dependencies = [
        ("lms", "0002_alter_course_overview_alter_course_preview_video_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Display title for the video",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description shown below the video player",
                        verbose_name="Description",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload the video file (MP4 recommended, max 2GB)",
                        upload_to=plugins.lms.models.video._video_upload_path,
                        verbose_name="Video File",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated or custom preview image",
                        null=True,
                        upload_to=plugins.lms.models.video._thumbnail_upload_path,
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "captions",
                    models.FileField(
                        blank=True,
                        help_text="VTT or SRT subtitle file",
                        null=True,
                        upload_to=plugins.lms.models.video._caption_upload_path,
                        verbose_name="Captions / Subtitles",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Video duration in seconds (auto-detected)",
                        verbose_name="Duration (seconds)",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(default=0, verbose_name="Width (px)"),
                ),
                (
                    "height",
                    models.PositiveIntegerField(default=0, verbose_name="Height (px)"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="File Size (bytes)"
                    ),
                ),
                (
                    "video_format",
                    models.CharField(
                        choices=[
                            ("mp4", "MP4 (H.264)"),
                            ("webm", "WebM (VP9)"),
                            ("ogg", "Ogg (Theora)"),
                            ("other", "Other"),
                        ],
                        default="mp4",
                        max_length=10,
                        verbose_name="Video Format",
                    ),
                ),
                (
                    "bitrate",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Average video bitrate",
                        verbose_name="Bitrate (kbps)",
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Processing Status",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        verbose_name="Processing Error",
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Processing Started",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processed At"
                    ),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False,
                        help_text="Allow viewing without course enrollment",
                        verbose_name="Free Preview",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Hide from students without deleting",
                        verbose_name="Active",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order among multiple videos in a lesson",
                        verbose_name="Sort Order",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="The lesson this video belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="lms.lesson",
                        verbose_name="Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "db_table": "lms_video",
                "ordering": ["sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "sort_order"],
                        name="lms_video_lesson_sort",
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="lms_video_processing",
                    ),
                    models.Index(
                        fields=["is_active", "is_preview"],
                        name="lms_video_access",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoCaption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="BCP 47 language code (e.g. 'en', 'fr', 'ar')",
                        max_length=10,
                        verbose_name="Language Code",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="English",
                        help_text="Display label (e.g. 'English', 'French')",
                        max_length=50,
                        verbose_name="Label",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="WebVTT (.vtt) or SubRip (.srt) file",
                        upload_to=plugins.lms.models.video._caption_upload_path,
                        verbose_name="Caption File",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Play by default when captions are enabled",
                        verbose_name="Default Track",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caption_tracks",
                        to="lms.video",
                        verbose_name="Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Caption",
                "verbose_name_plural": "Video Captions",
                "db_table": "lms_video_caption",
                "unique_together": {("video", "language")},
            },
        ),
    ]
