# Simple .toml configuration (alternative to pyproject.toml)
line-length = 100
target-version = "py311"

[format]
quote-style = "double"
skip-magic-trailing-comma = false

[lint]
select = [
    "E",   # pycodestyle errors
#   "W",   # pycodestyle warnings
    "F",   # pyflakes (unused imports/variables)
    "I",   # isort (import sorting)
#   "B",   # flake8-bugbear
#   "C4",  # flake8-comprehensions
#   "UP",  # pyupgrade
#   "RUF", # ruff-specific rules
#   "ARG", # flake8-unused-arguments
#   "ERA", # eradicate (commented code)
]
ignore = [
    "E501", "B008", "C901",
    "PLR0913", "PLR0915", "PLR0912", "PLR0911",
    "S101", "S311", "ERA001","W292",
    "RUF005","RUF059", "F405", "F403", "F401",
    "RUF012", "UP035", "UP045", "UP006","F811", # with fix
    "RUF013", "F841", "RUF010","E722", # miss handling  & conversion
    "ARG003","ARG002", "ARG001", "ARG004" # callable, & unusing arg
]

[lint.isort]
known-first-party = ["core", "apps", "config", "pages"]
known-third-party = [
    "django", "celery", "rest_framework", "sentry_sdk",
    "structlog", "wagtail", "ninja", "pydantic", "dynaconf"
]


[lint.per-file-ignores]
"**/admin.py" = ["F401", "F403"]
"**/apps.py" = ["F401"]
"**/migrations/*.py" = ["F401", "F841"]
"**/models.py" = ["RUF012"]
"**/tests/*.py" = ["S101"]
"**/test_*.py" = ["S101"]
"**/urls.py" = ["F401"]
"com" = ["F401"]

[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"


# Unused arguments configuration
[lint.flake8-unused-arguments]
ignore-variadic-names = false

# Docstring style configuration
[lint.pydocstyle]
convention = "google"

