# Generated by Django 5.2.16 on 2026-08-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_blogpage_pricingpage_productspage_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
        migrations.AddField(
            model_name='pricingpage',
            name='nav_order',
            field=models.IntegerField(default=100, help_text='Lower numbers appear first in the header nav.', verbose_name='Navigation order'),
        ),
        migrations.AddField(
            model_name='pricingpage',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Include this page in the main site header navigation.', verbose_name='Show in navigation'),
        ),
    ]
