# Generated by Django 5.2.16 on 2026-08-05 23:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_delete_projectspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='comparison',
            field=wagtail.fields.StreamField([('comparison', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Column', 'max_length': 40}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Edition names, left to right (e.g. Community, Standard, Pro, Cloud).', 'label': 'Edition columns'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Feature', 'max_length': 200}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Cell', 'max_length': 120}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'One value per edition column, in order: Yes / No / short note.', 'label': 'Values per column'}), 8: ('wagtail.blocks.StructBlock', [[('feature', 5), ('cells', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Feature rows'}), 10: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('columns', 4), ('rows', 9)]], {})}, help_text='A full edition-by-edition capability table (columns = editions, rows = features). Cells use Yes / No / short notes.', verbose_name='Feature comparison'),
        ),
    ]
