# Generated by Django 5.2.16 on 2026-08-06 01:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_productpage_logo_styles'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero', wagtail.fields.StreamField([('hero', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Badge', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Primary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('style', 5)]], {'label': 'Secondary CTA', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Trusted-by text', 'max_length': 160, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('subtitle', 2), ('primary_cta', 6), ('secondary_cta', 7), ('trusted_by', 8)]], {})}, verbose_name='Hero')),
                ('cta', wagtail.fields.StreamField([('cta', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 80}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'URL', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline'), ('white', 'White')], 'label': 'Style'}), 5: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Primary CTA', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 2), ('href', 3), ('style', 4)]], {'label': 'Secondary CTA', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('primary_cta', 5), ('secondary_cta', 6)]], {})}, verbose_name='Call to action')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Team story content.', verbose_name='Body')),
                ('team', wagtail.fields.StreamField([('team', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 120}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Role', 'max_length': 120, 'required': False}), 5: ('wagtail.blocks.TextBlock', (), {'label': 'Bio', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Avatar fallback, e.g. ME.', 'label': 'Initials', 'max_length': 4, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. GitHub, LinkedIn, Facebook, X.', 'label': 'Platform', 'max_length': 40}), 8: ('wagtail.blocks.URLBlock', (), {'label': 'URL'}), 9: ('wagtail.blocks.StructBlock', [[('platform', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Links', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 3), ('role', 4), ('bio', 5), ('initials', 6), ('links', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Members'}), 13: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('members', 12)]], {})}, verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team page',
                'verbose_name_plural': 'Team pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
