# Generated by Django 5.2.16 on 2026-08-07 13:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_brandpage_palette_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='hero_screenshot_url',
            field=models.URLField(blank=True, help_text='Optional image shown under the post hero (e.g. a product screenshot). Leave empty for a text-only post.', verbose_name='Hero screenshot URL'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='snippets',
            field=wagtail.fields.StreamField([('snippets', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Language', 'max_length': 40, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'The snippet body — kept verbatim.', 'label': 'Code'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Pick the blog post that hosts this code. When set, the card links to the post instead of rendering the code inline.', 'label': 'Deep-dive post', 'page_type': ['pages.BlogPostPage'], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 1), ('language', 3), ('code', 4), ('related_post', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Snippets'}), 8: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('snippets', 7)]], {})}, help_text="The code for this post's deep dive — product pages link their snippet cards here via SnippetBlock.related_post.", verbose_name='Code sections'),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='variants',
            field=wagtail.fields.StreamField([('variant', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Image URL (https://… or a data: URI). Leave empty to render a stylized screen frame with the variant name.', 'label': 'Screenshot URL', 'max_length': 500, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'One line describing what this variant shows.', 'label': 'Caption', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Open the Community preview. Leave empty to use the page title.', 'label': 'Link label', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL. Ignored when a page is chosen.', 'label': 'Link URL', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Pick an internal page — its URL wins over the manual link.', 'label': 'Link to a page', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('screenshot_url', 1), ('caption', 2), ('link_label', 3), ('link_href', 4), ('link_page', 5)]], {})}, help_text='Screenshot variants of the product — each with an optional image, caption and hyperlink (e.g. the Community terminal linking to its edition preview).', verbose_name='Variants & screenshots'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='snippets',
            field=wagtail.fields.StreamField([('snippets', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Eyebrow', 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Language', 'max_length': 40, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'The snippet body — kept verbatim.', 'label': 'Code'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Pick the blog post that hosts this code. When set, the card links to the post instead of rendering the code inline.', 'label': 'Deep-dive post', 'page_type': ['pages.BlogPostPage'], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 1), ('language', 3), ('code', 4), ('related_post', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Snippets'}), 8: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('description', 2), ('snippets', 7)]], {})}, verbose_name='Reference snippets'),
        ),
    ]
