services:
  code-server:
    image: 'lscr.io/linuxserver/code-server:latest'
    container_name: code-server
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Madrid
      PASSWORD: ${SERVICE_PASSWORD_64_PASSWORDCODESERVER}
      SUDO_PASSWORD: ${SERVICE_PASSWORD_SUDOCODESERVER}
      DEFAULT_WORKSPACE: /config/workspace
      SERVICE_NAME_CODE_SERVER: code-server
    volumes:
      - 'code-server-config:/config'
      - '/data:/config/workspace/data:ro'
    healthcheck:
      test: [CMD, curl, '-f', 'http://127.0.0.1:8443']
      interval: 2s
      timeout: 10s
      retries: 15
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.1.2
      - coolify.serviceId=6
      - coolify.type=service
      - coolify.resourceName=code-server
      - coolify.projectName=websites
      - coolify.serviceName=code-server
      - coolify.environmentName=dev-env
      - traefik.enable=true
      - traefik.http.routers.code-server.entryPoints=http
      - traefik.http.routers.code-server.rule=Host(`code-server.${SERVER_IP:-72.61.82.167}.sslip.io`)
      - traefik.http.routers.code-server.service=code-server
      - traefik.http.services.code-server.loadbalancer.server.port=8443
    networks:
      - coolify
    env_file:
      - .env

volumes:
  code-server-config:
    name: code-server-config

networks:
  coolify:
    name: coolify
    external: true
