services:
  code-server:
    image: 'lscr.io/linuxserver/code-server:latest'
    environment:
      SERVICE_URL_CODESERVER_8443: 'http://codeserver-x7nfbeijdh7ulpehx9d3s03y.72.61.82.167.sslip.io:8443'
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Madrid
      PASSWORD: $SERVICE_PASSWORD_64_PASSWORDCODESERVER
      SUDO_PASSWORD: $SERVICE_PASSWORD_SUDOCODESERVER
      DEFAULT_WORKSPACE: /config/workspace
      COOLIFY_RESOURCE_UUID: x7nfbeijdh7ulpehx9d3s03y
      COOLIFY_CONTAINER_NAME: code-server-x7nfbeijdh7ulpehx9d3s03y
      COOLIFY_FQDN: codeserver-x7nfbeijdh7ulpehx9d3s03y.72.61.82.167.sslip.io
      COOLIFY_URL: 'http://codeserver-x7nfbeijdh7ulpehx9d3s03y.72.61.82.167.sslip.io'
      SERVICE_NAME_CODE_SERVER: code-server
    volumes:
      - 'code-server-config:/config'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8443'
      interval: 2s
      timeout: 10s
      retries: 15
    container_name: code-server-x7nfbeijdh7ulpehx9d3s03y
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.1.2
      - coolify.serviceId=6
      - coolify.type=service
      - coolify.name=code-server-x7nfbeijdh7ulpehx9d3s03y
      - coolify.resourceName=code-server
      - coolify.projectName=websites
      - coolify.serviceName=code-server
      - coolify.environmentName=dev-env
      - coolify.pullRequestId=0
      - coolify.service.subId=15
      - coolify.service.subType=application
      - coolify.service.subName=code-server
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-x7nfbeijdh7ulpehx9d3s03y-code-server.entryPoints=http
      - traefik.http.routers.http-0-x7nfbeijdh7ulpehx9d3s03y-code-server.middlewares=gzip
      - 'traefik.http.routers.http-0-x7nfbeijdh7ulpehx9d3s03y-code-server.rule=Host(`codeserver-x7nfbeijdh7ulpehx9d3s03y.72.61.82.167.sslip.io`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-x7nfbeijdh7ulpehx9d3s03y-code-server.service=http-0-x7nfbeijdh7ulpehx9d3s03y-code-server
      - traefik.http.services.http-0-x7nfbeijdh7ulpehx9d3s03y-code-server.loadbalancer.server.port=8443
    networks:
      code-server: null
    env_file:
      - .env
volumes:
  code-server-config:
    name: code-server-config
networks:
  code-server:
    name: code-server
    external: true
