# Generated by Django 5.2.16 on 2026-08-08 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_course_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Course tag name (e.g., 'Django', 'HTMX')", max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Course tag',
                'verbose_name_plural': 'Course tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Specialization title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, help_text='What students will learn — one per line.', verbose_name='Learning objectives'),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, help_text='Prerequisites and requirements — one per line.', verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Who this course is for — one per line.', verbose_name='Target audience'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learning.coursetag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learning.specialization', verbose_name='Specializations'),
        ),
        migrations.CreateModel(
            name='CourseEnrollmentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Phone number for contact', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this lead')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateTimeField(blank=True, help_text='When the user actually enrolled', null=True)),
                ('course', models.ForeignKey(help_text='Course being enrolled', on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_leads', to='learning.course')),
            ],
            options={
                'verbose_name': 'Course enrollment lead',
                'verbose_name_plural': 'Course enrollment leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='learning_co_email_9824fe_idx'), models.Index(fields=['status', '-created_at'], name='learning_co_status_4182f4_idx'), models.Index(fields=['course', 'status'], name='learning_co_course__6a4108_idx')],
                'unique_together': {('course', 'email')},
            },
        ),
    ]
