# Generated by Django 5.2.16 on 2026-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='provider_synced_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the row was last pushed to the configured email provider (Mailchimp / Brevo / webhook). Unset when no provider is configured or the sync failed.', null=True, verbose_name='provider synced'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the branded welcome email was last sent. Unset if the send failed or this address was imported.', null=True, verbose_name='welcome email sent'),
        ),
    ]
