# Generated by Django 5.2.16 on 2026-08-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_alter_sitesettings_meta_author"),
        ("content", "0017_sitesettings_reduced_motion_default_and_more"),
    ]

    operations = []
