# Generated by Django 5.2.16 on 2026-08-14 23:23

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_workspace_external_ref_workspace_source'),
        ('crm', '0002_custom_field_definitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cashback_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile'), ('mixed', 'Mixed'), ('credit', 'Store Credit')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('source', models.CharField(default='formint-pro', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='crm.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sales', to='core.workspace')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PosPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile'), ('mixed', 'Mixed'), ('credit', 'Store Credit')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pos_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.possale')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PosSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pos_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.possale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['workspace', 'sale_date'], name='pos_possale_workspa_d88e64_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['workspace', 'status'], name='pos_possale_workspa_0931d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='possale',
            constraint=models.UniqueConstraint(fields=('workspace', 'external_id'), name='uniq_pos_sale_workspace_external'),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['pos_sale', 'paid_on'], name='pos_pospaym_pos_sal_3e4aad_idx'),
        ),
        migrations.AddConstraint(
            model_name='possaleitem',
            constraint=models.UniqueConstraint(fields=('pos_sale', 'external_id'), name='uniq_pos_sale_item_external'),
        ),
    ]
