# Generated by Django 6.1 on 2026-08-18 18:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditlog_options_alter_emailaccount_options_and_more'),
        ('crm', '0004_alter_activity_options_alter_company_options_and_more'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pospayment',
            options={'ordering': ['-paid_on', '-id'], 'verbose_name': 'POS payment', 'verbose_name_plural': 'POS payments'},
        ),
        migrations.AlterModelOptions(
            name='possale',
            options={'ordering': ['-sale_date', '-id'], 'verbose_name': 'POS sale', 'verbose_name_plural': 'POS sales'},
        ),
        migrations.AlterModelOptions(
            name='possaleitem',
            options={'ordering': ['id'], 'verbose_name': 'POS sale item', 'verbose_name_plural': 'POS sale items'},
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile'), ('mixed', 'Mixed'), ('credit', 'Store Credit')], default='cash', max_length=20, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='paid_on',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='paid on'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='pos_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.possale', verbose_name='POS sale'),
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cashback amount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='crm.contact', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='discount amount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='external_id',
            field=models.CharField(max_length=120, verbose_name='external id'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile'), ('mixed', 'Mixed'), ('credit', 'Store Credit')], default='cash', max_length=20, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='sale date'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='source',
            field=models.CharField(default='formint-pro', max_length=40, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='tax amount'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='possale',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sales', to='core.workspace', verbose_name='workspace'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='external id'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='line total'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='pos_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.possale', verbose_name='POS sale'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='possaleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='unit price'),
        ),
    ]
