# Generated by Django 4.2.30 on 2026-05-20 11:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Used in author archive URLs', unique=True, verbose_name='Slug')),
                ('role', models.CharField(blank=True, help_text='e.g. Lead Developer, Designer, Contributor', max_length=100, verbose_name='Role / Title')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('send_newsletter_on_publish', models.BooleanField(default=False, help_text='If checked, an email campaign will be generated and sent to all subscribers when this page is published.', verbose_name='Send Newsletter on Publish')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Featured Image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='OG Image')),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, help_text='Group tags by category, e.g. Technology, Design', max_length=100, verbose_name='Category')),
                ('color', models.CharField(default='#ee9b00', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon Class')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='blog_blogta_categor_d2258b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduction')),
                ('excerpt', wagtail.fields.RichTextField(blank=True, verbose_name='Excerpt')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published Date')),
                ('body', wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {})}, verbose_name='Body')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Page Views')),
                ('reading_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Reading Time (min)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Featured Image')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='OG Image')),
                ('related_posts', models.ManyToManyField(blank=True, to='blog.blogpost', verbose_name='Related Posts')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.blogtag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Blog Post (Snippet)',
                'verbose_name_plural': 'Blog Posts (Snippets)',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reads', models.IntegerField(default=0)),
                ('unique_readers', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to='blog.blogpage')),
            ],
            options={
                'verbose_name': 'Article Engagement',
                'verbose_name_plural': 'Article Engagements',
            },
        ),
        migrations.CreateModel(
            name='BlogPostAuthorRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_relationships', to='blog.blogauthor', verbose_name='Author')),
                ('post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_relationships', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Post Author',
                'ordering': ['-is_primary', 'sort_order'],
                'unique_together': {('post', 'author')},
            },
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Tag')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_pages', to='blog.blogtag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Blog Page Tag',
                'verbose_name_plural': 'Blog Page Tags',
                'ordering': ['-is_primary', 'sort_order'],
                'unique_together': {('page', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='BlogPageAuthorRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_relationships', to='blog.blogauthor', verbose_name='Author')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_relationships', to='blog.blogpage')),
            ],
            options={
                'verbose_name': 'Page Author',
                'ordering': ['-is_primary', 'sort_order'],
                'unique_together': {('page', 'author')},
            },
        ),
        migrations.CreateModel(
            name='ArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('read_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('scroll_depth', models.IntegerField(default=0, help_text='Scroll depth percentage (0-100)')),
                ('is_unique', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_reads', to='blog.blogpage')),
            ],
            options={
                'verbose_name': 'Article Read',
                'verbose_name_plural': 'Article Reads',
                'indexes': [models.Index(fields=['post', 'read_at'], name='blog_articl_post_id_bcfa6e_idx'), models.Index(fields=['session_key', 'read_at'], name='blog_articl_session_3de706_idx')],
            },
        ),
    ]
