# Generated by Django 5.2.13 on 2026-06-08 13:44

import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('registration_confirmation', 'Registration Confirmation'), ('signin_success', 'Sign-In Success')], max_length=50, verbose_name='Template Type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body_html', wagtail.fields.RichTextField(verbose_name='Body (HTML)')),
                ('body_text', models.TextField(help_text='Used as fallback for email clients that do not render HTML.', verbose_name='Body (Plain Text)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Auth Email Template',
                'verbose_name_plural': 'Auth Email Templates',
                'db_table': 'accounts_registration_authemailtemplate',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='live',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='live',
        ),
        migrations.RemoveField(
            model_name='message',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='live',
        ),
        migrations.RemoveField(
            model_name='note',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='live',
        ),
        migrations.RemoveField(
            model_name='service',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='live',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='search_description',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='sharednote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
