# Generated by Django 5.2.16 on 2026-08-18 05:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero",
                    wagtail.fields.StreamField(
                        [("hero", 11)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The emphasized word rendered with the accent mark (e.g. 'loop').",
                                    "label": "Accent word",
                                    "max_length": 60,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle / lede", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small mono line under the CTAs (e.g. heritage note).",
                                    "label": "Footnote",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title", 1),
                                        ("accent", 2),
                                        ("subtitle", 3),
                                        ("primary_cta", 8),
                                        ("secondary_cta", 9),
                                        ("note", 10),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Hero",
                    ),
                ),
                (
                    "cta",
                    wagtail.fields.StreamField(
                        [("cta", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("primary_cta", 6),
                                        ("secondary_cta", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Call to action",
                    ),
                ),
                (
                    "faq",
                    wagtail.fields.StreamField(
                        [("faq", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Question", "max_length": 200},
                            ),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Answer", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 3), ("answer", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.ListBlock",
                                (5,),
                                {"label": "FAQ items"},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("description", 2),
                                        ("items", 6),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="FAQ",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ page",
                "verbose_name_plural": "FAQ pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero",
                    wagtail.fields.StreamField(
                        [("hero", 11)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The emphasized word rendered with the accent mark (e.g. 'loop').",
                                    "label": "Accent word",
                                    "max_length": 60,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle / lede", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small mono line under the CTAs (e.g. heritage note).",
                                    "label": "Footnote",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title", 1),
                                        ("accent", 2),
                                        ("subtitle", 3),
                                        ("primary_cta", 8),
                                        ("secondary_cta", 9),
                                        ("note", 10),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Hero",
                    ),
                ),
                (
                    "cta",
                    wagtail.fields.StreamField(
                        [("cta", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("primary_cta", 6),
                                        ("secondary_cta", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Call to action",
                    ),
                ),
                (
                    "dna",
                    wagtail.fields.StreamField(
                        [("dna", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Label", "max_length": 80},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Value", "max_length": 120},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("value", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.ListBlock", (2,), {"label": "Items"}),
                            4: ("wagtail.blocks.StructBlock", [[("items", 3)]], {}),
                        },
                        verbose_name="DNA band",
                    ),
                ),
                (
                    "features",
                    wagtail.fields.StreamField(
                        [("features", 10)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Astro icon key (crm, marketing, attribution, …).",
                                    "label": "Icon",
                                    "max_length": 80,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Kicker",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 120},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Module URL (e.g. /crm/). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page instead of typing a URL.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 3),
                                        ("label", 4),
                                        ("title", 5),
                                        ("description", 2),
                                        ("href", 6),
                                        ("page", 7),
                                    ]
                                ],
                                {},
                            ),
                            9: (
                                "wagtail.blocks.ListBlock",
                                (8,),
                                {"label": "Features"},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("description", 2),
                                        ("features", 9),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Modules",
                    ),
                ),
                (
                    "steps",
                    wagtail.fields.StreamField(
                        [("steps", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Number", "max_length": 10},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 120},
                            ),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Copy", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("number", 2), ("title", 3), ("copy", 4)]],
                                {},
                            ),
                            6: ("wagtail.blocks.ListBlock", (5,), {"label": "Steps"}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("eyebrow", 0), ("title", 1), ("steps", 6)]],
                                {},
                            ),
                        },
                        verbose_name="How it works",
                    ),
                ),
                (
                    "stats",
                    wagtail.fields.StreamField(
                        [("stats", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Section title",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Value", "max_length": 20},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Suffix",
                                    "max_length": 10,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Label", "max_length": 120},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("value", 1), ("suffix", 2), ("label", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.ListBlock", (4,), {"label": "Stats"}),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("stats", 5)]],
                                {},
                            ),
                        },
                        verbose_name="Stats",
                    ),
                ),
                (
                    "pricing",
                    wagtail.fields.StreamField(
                        [("pricing", 14)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Name", "max_length": 80},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Price", "max_length": 20},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Period",
                                    "max_length": 40,
                                    "required": False,
                                },
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"max_length": 160}),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"label": "Features"},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "CTA label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "CTA URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page instead of typing a CTA URL.",
                                    "label": "CTA page",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "Featured",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 3),
                                        ("description", 2),
                                        ("price", 4),
                                        ("period", 5),
                                        ("features", 7),
                                        ("cta_label", 8),
                                        ("cta_href", 9),
                                        ("cta_page", 10),
                                        ("featured", 11),
                                    ]
                                ],
                                {},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {"label": "Tiers"}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("description", 2),
                                        ("tiers", 13),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Pricing",
                    ),
                ),
                (
                    "faq",
                    wagtail.fields.StreamField(
                        [("faq", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Question", "max_length": 200},
                            ),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Answer", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 3), ("answer", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.ListBlock",
                                (5,),
                                {"label": "FAQ items"},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("description", 2),
                                        ("items", 6),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="FAQ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home page",
                "verbose_name_plural": "Home pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PricingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero",
                    wagtail.fields.StreamField(
                        [("hero", 11)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The emphasized word rendered with the accent mark (e.g. 'loop').",
                                    "label": "Accent word",
                                    "max_length": 60,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle / lede", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small mono line under the CTAs (e.g. heritage note).",
                                    "label": "Footnote",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title", 1),
                                        ("accent", 2),
                                        ("subtitle", 3),
                                        ("primary_cta", 8),
                                        ("secondary_cta", 9),
                                        ("note", 10),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Hero",
                    ),
                ),
                (
                    "cta",
                    wagtail.fields.StreamField(
                        [("cta", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("primary_cta", 6),
                                        ("secondary_cta", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Call to action",
                    ),
                ),
                (
                    "pricing",
                    wagtail.fields.StreamField(
                        [("pricing", 14)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Name", "max_length": 80},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Price", "max_length": 20},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Period",
                                    "max_length": 40,
                                    "required": False,
                                },
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"max_length": 160}),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"label": "Features"},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "CTA label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "CTA URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page instead of typing a CTA URL.",
                                    "label": "CTA page",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "label": "Featured",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 3),
                                        ("description", 2),
                                        ("price", 4),
                                        ("period", 5),
                                        ("features", 7),
                                        ("cta_label", 8),
                                        ("cta_href", 9),
                                        ("cta_page", 10),
                                        ("featured", 11),
                                    ]
                                ],
                                {},
                            ),
                            13: ("wagtail.blocks.ListBlock", (12,), {"label": "Tiers"}),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("description", 2),
                                        ("tiers", 13),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Pricing",
                    ),
                ),
                (
                    "faq",
                    wagtail.fields.StreamField(
                        [("faq", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Question", "max_length": 200},
                            ),
                            4: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Answer", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 3), ("answer", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.ListBlock",
                                (5,),
                                {"label": "FAQ items"},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 0),
                                        ("title", 1),
                                        ("description", 2),
                                        ("items", 6),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="FAQ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing page",
                "verbose_name_plural": "Pricing pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PrivacyPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero",
                    wagtail.fields.StreamField(
                        [("hero", 11)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The emphasized word rendered with the accent mark (e.g. 'loop').",
                                    "label": "Accent word",
                                    "max_length": 60,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle / lede", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small mono line under the CTAs (e.g. heritage note).",
                                    "label": "Footnote",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title", 1),
                                        ("accent", 2),
                                        ("subtitle", 3),
                                        ("primary_cta", 8),
                                        ("secondary_cta", 9),
                                        ("note", 10),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Hero",
                    ),
                ),
                (
                    "cta",
                    wagtail.fields.StreamField(
                        [("cta", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("primary_cta", 6),
                                        ("secondary_cta", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Call to action",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Policy content — paragraphs, headings, lists.",
                        verbose_name="Body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy page",
                "verbose_name_plural": "Privacy pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TermsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero",
                    wagtail.fields.StreamField(
                        [("hero", 11)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Eyebrow",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The emphasized word rendered with the accent mark (e.g. 'loop').",
                                    "label": "Accent word",
                                    "max_length": 60,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle / lede", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 4),
                                        ("href", 5),
                                        ("page", 6),
                                        ("style", 7),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small mono line under the CTAs (e.g. heritage note).",
                                    "label": "Footnote",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 0),
                                        ("title", 1),
                                        ("accent", 2),
                                        ("subtitle", 3),
                                        ("primary_cta", 8),
                                        ("secondary_cta", 9),
                                        ("note", 10),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Hero",
                    ),
                ),
                (
                    "cta",
                    wagtail.fields.StreamField(
                        [("cta", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 200},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Subtitle", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Leave empty to use the linked page's title.",
                                    "label": "Label",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "External URL (e.g. https://…). Ignored when a page is chosen.",
                                    "label": "URL",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Pick an internal page — its URL wins over the manual URL field.",
                                    "label": "Link to a page",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Primary CTA", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("href", 3),
                                        ("page", 4),
                                        ("style", 5),
                                    ]
                                ],
                                {"label": "Secondary CTA", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("primary_cta", 6),
                                        ("secondary_cta", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Call to action",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Policy content — paragraphs, headings, lists.",
                        verbose_name="Body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terms page",
                "verbose_name_plural": "Terms pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
