# Generated by Django 4.2.30 on 2026-05-20 11:47

from django.db import migrations, models
import django.db.models.deletion
import pages.about.models.snippets.client
import pages.about.models.snippets.testimonial
import pages.home.models.snippets.team
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('bio', wagtail.fields.StreamField([('bio_text', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Bio Text'})}, verbose_name='Bio')),
                ('testimonials', wagtail.fields.StreamField([('testimonial', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (pages.about.models.snippets.testimonial.Testimonial,), {})}, verbose_name='Testimonials')),
                ('clients', wagtail.fields.StreamField([('client', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (pages.about.models.snippets.client.Client,), {})}, verbose_name='Clients')),
                ('team', wagtail.fields.StreamField([('team_member', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (pages.home.models.snippets.team.TeamMember,), {})}, verbose_name='Team Section')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Job Title')),
                ('text', models.TextField(verbose_name='Testimonial Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('url', models.URLField(blank=True, verbose_name='Website URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['order', 'name'],
            },
        ),
    ]
