# Generated by Django 5.2.13 on 2026-08-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='replied_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_content_type',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
        # NOTE: AlterUniqueTogether MUST precede RemoveField('note') and
        # RemoveField('user') — it needs those fields present in the
        # from-state to compute the composed index columns to drop.
        migrations.AlterUniqueTogether(
            name='sharednote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='note',
        ),
        migrations.RemoveField(
            model_name='sharednote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='SharedNote',
        ),
    ]
