# Generated by Django 5.2.16 on 2026-08-07 13:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_update_sitesettings_nav_cta_url'),
        ('pages', '0026_blogpostpage_hero_screenshot_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='The comment text — up to 2000 characters.', verbose_name='comment')),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this comment from the public thread without deleting it.', verbose_name='approved')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.blogpostpage', verbose_name='post')),
            ],
            options={
                'verbose_name': 'blog comment',
                'verbose_name_plural': 'blog comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
