# Generated by Django 5.2.16 on 2026-08-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_postcomment'),
        ('content', '0011_add_fusion_branding_snippet'),
    ]

    operations = [
    ]
