# Generated by Django 5.2.15 on 2026-07-25 03:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_video_videocaption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('instructor', 'Instructors Only'), ('student', 'Students Only')], default='all', max_length=20, verbose_name='Target Audience')),
                ('link', models.URLField(blank=True, default='', help_text="Optional link for 'Learn More' button", verbose_name='Link URL')),
                ('link_label', models.CharField(blank=True, default='', help_text="Button label for the link (e.g., 'View Course')", max_length=100, verbose_name='Link Label')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ['sort_order', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='Instructions')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('max_score', models.IntegerField(default=100, verbose_name='Maximum Score')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['course', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_submission', models.TextField(blank=True, default='', verbose_name='Text Submission')),
                ('file_url', models.URLField(blank=True, default='', verbose_name='File URL')),
                ('file_name', models.CharField(blank=True, default='', max_length=500, verbose_name='File Name')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned for Revision')], default='submitted', max_length=20, verbose_name='Status')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Instructor Feedback')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
            ],
            options={
                'verbose_name': 'assignment submission',
                'verbose_name_plural': 'assignment submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('enrollment', 'Enrollment'), ('course_update', 'Course Update'), ('assignment', 'Assignment'), ('grading', 'Grading'), ('quiz', 'Quiz'), ('review', 'Review'), ('announcement', 'Announcement'), ('system', 'System')], db_index=True, default='system', max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('link', models.CharField(blank=True, default='', max_length=500, verbose_name='Link')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Is Dismissed')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'lms_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='In-App Notifications')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('enrollment_notifications', models.BooleanField(default=True, verbose_name='Enrollment Notifications')),
                ('course_update_notifications', models.BooleanField(default=True, verbose_name='Course Update Notifications')),
                ('assignment_notifications', models.BooleanField(default=True, verbose_name='Assignment Notifications')),
                ('grading_notifications', models.BooleanField(default=True, verbose_name='Grading Notifications')),
                ('quiz_notifications', models.BooleanField(default=True, verbose_name='Quiz Notifications')),
                ('review_notifications', models.BooleanField(default=True, verbose_name='Review Notifications')),
                ('announcement_notifications', models.BooleanField(default=True, verbose_name='Announcement Notifications')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='System Notifications')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='immediate', max_length=10, verbose_name='Digest Frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'lms_notification_preferences',
            },
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='lms_video_lesson__13716d_idx',
            old_name='lms_video_lesson_sort',
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='lms_video_process_c0324b_idx',
            old_name='lms_video_processing',
        ),
        migrations.RenameIndex(
            model_name='video',
            new_name='lms_video_is_acti_6c8d90_idx',
            old_name='lms_video_access',
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
        migrations.AlterModelTable(
            name='videocaption',
            table=None,
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.assignment', verbose_name='Assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Graded By'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='lms_notific_user_id_a00b89_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='lms_notific_user_id_9788f6_idx'),
        ),
    ]
