# Generated by Django 5.2.16 on 2026-08-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_post_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "campaign",
                "verbose_name_plural": "campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-scheduled_at"],
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.AlterModelOptions(
            name="socialchannel",
            options={
                "ordering": ["platform", "account_name"],
                "verbose_name": "social channel",
                "verbose_name_plural": "social channels",
            },
        ),
    ]
