# Generated by Django 5.2.17 on 2026-08-15 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0002_usersettings_fusion_render_mode'),
        ('pos_full', '0005_loyalty_reversal_consent'),
    ]

    operations = [
    ]
