# Generated by Django 5.2.17 on 2026-08-15 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0010_outboxqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('station_type', models.CharField(choices=[('pc', 'PC'), ('console', 'Console'), ('vr', 'VR'), ('sim', 'Simulator')], default='pc', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Billing rate per hour (used to compute session cost).', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'full_gaming_stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GamingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('minutes', models.IntegerField(help_text='Total purchased minutes in this token.')),
                ('remaining_minutes', models.IntegerField(help_text='Minutes still available on this token.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'full_gaming_tokens',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='GamingQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('requested_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('station', models.ForeignKey(blank=True, help_text='Station assigned once a spot frees up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='pos_full.gamingstation')),
            ],
            options={
                'db_table': 'full_gaming_queue',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('last_resume_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_seconds', models.IntegerField(default=0, help_text='Accumulated active (non-paused) seconds.')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Computed cost = active duration × station hourly rate.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gaming_sessions', to='pos_full.customer')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pos_full.gamingstation')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pos_full.gamingtoken')),
            ],
            options={
                'db_table': 'full_gaming_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['station', 'status'], name='full_gaming_station_727988_idx'), models.Index(fields=['status', 'started_at'], name='full_gaming_status_d41c35_idx')],
            },
        ),
    ]
