http:
  routers:
    shared-media-http:
      rule: Host(`media.structa.cloud`)
      entryPoints:
      - web
      middlewares:
      - redirect-to-https
      service: shared-media-service
    shared-media-https:
      rule: Host(`media.structa.cloud`)
      entryPoints:
      - web-secure
      middlewares:
      - compress
      - security-headers
      service: shared-media-service
      tls:
        certResolver: letsencrypt
    ctc-media-http:
      rule: Host(`media.ctc-research.com`)
      entryPoints:
      - web
      middlewares:
      - redirect-to-https
      service: ctc-media-service
    ctc-media-https:
      rule: Host(`media.ctc-research.com`)
      entryPoints:
      - web-secure
      middlewares:
      - compress
      - security-headers
      service: ctc-media-service
      tls:
        certResolver: letsencrypt
    lms-media-http:
      rule: Host(`media.lms-demo.com`)
      entryPoints:
      - web
      middlewares:
      - redirect-to-https
      service: lms-media-service
    lms-media-https:
      rule: Host(`media.lms-demo.com`)
      entryPoints:
      - web-secure
      middlewares:
      - compress
      - security-headers
      service: lms-media-service
      tls:
        certResolver: letsencrypt
    vresume-media-http:
      rule: Host(`media.vresume.structa.cloud`)
      entryPoints:
      - web
      middlewares:
      - redirect-to-https
      service: vresume-media-service
    vresume-media-https:
      rule: Host(`media.vresume.structa.cloud`)
      entryPoints:
      - web-secure
      middlewares:
      - compress
      - security-headers
      service: vresume-media-service
      tls:
        certResolver: letsencrypt
  services:
    shared-media-service:
      loadBalancer:
        servers:
        - url: http://shared-media:80
    ctc-media-service:
      loadBalancer:
        servers:
        - url: http://shared-media:80
    lms-media-service:
      loadBalancer:
        servers:
        - url: http://shared-media:80
    vresume-media-service:
      loadBalancer:
        servers:
        - url: http://shared-media:80
