# Generated by Django 4.2.30 on 2026-05-20 11:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('education', wagtail.fields.StreamField([('timeline_item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Degree, job title, or certification', 'label': 'Title', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Institution or company name', 'label': 'Subtitle', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 2020 – Present', 'label': 'Date Range', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('date', 2), ('description', 3)]], {})}, verbose_name='Education')),
                ('experience', wagtail.fields.StreamField([('timeline_item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Degree, job title, or certification', 'label': 'Title', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Institution or company name', 'label': 'Subtitle', 'max_length': 200, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. 2020 – Present', 'label': 'Date Range', 'max_length': 100, 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('date', 2), ('description', 3)]], {})}, verbose_name='Experience')),
                ('skills', wagtail.fields.StreamField([('skill', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Skill Name', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('ide', 'IDE'), ('agent', 'Agent'), ('tool', 'Tool'), ('language', 'Language'), ('framework', 'Framework'), ('other', 'Other')], 'label': 'Category', 'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'label': 'Proficiency (0–100)', 'max_value': 100, 'min_value': 0}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('category', 1), ('level', 2)]], {})}, verbose_name='Skills')),
            ],
            options={
                'verbose_name': 'Resume Page',
                'verbose_name_plural': 'Resume Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
