services:
  ollama-api:
    image: 'ollama/ollama:latest'
    container_name: ollama-api
    volumes:
      - 'ollama:/root/.ollama'
    ports:
      - '22333:11434'
    environment:
      OLLAMA_HOST: '0.0.0.0:11434'
      SERVICE_NAME_OLLAMA_API: ollama-api
      SERVICE_NAME_OPEN_WEBUI: open-webui
    healthcheck:
      test: [CMD, ollama, list]
      interval: 5s
      timeout: 30s
      retries: 10
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.1.2
      - coolify.serviceId=4
      - coolify.type=service
      - coolify.resourceName=ollama
      - coolify.projectName=websites
      - coolify.serviceName=ollama-api
      - coolify.environmentName=utilities
    networks:
      - ollama-net
    env_file:
      - .env

  open-webui:
    image: 'ghcr.io/open-webui/open-webui:main'
    container_name: open-webui
    volumes:
      - 'open-webui:/app/backend/data'
    ports:
      - '3000:8080'
    depends_on:
      - ollama-api
    environment:
      OLLAMA_BASE_URL: 'http://ollama-api:11434'
      SERVICE_NAME_OLLAMA_API: ollama-api
      SERVICE_NAME_OPEN_WEBUI: open-webui
    healthcheck:
      test: [CMD, curl, '-f', 'http://localhost:8080']
      interval: 5s
      timeout: 30s
      retries: 10
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.1.2
      - coolify.serviceId=4
      - coolify.type=service
      - coolify.resourceName=ollama
      - coolify.projectName=websites
      - coolify.serviceName=open-webui
      - coolify.environmentName=utilities
      - traefik.enable=true
      - traefik.http.routers.open-webui.entryPoints=http
      - traefik.http.routers.open-webui.rule=Host(`open-webui.${SERVER_IP:-72.61.82.167}.sslip.io`)
      - traefik.http.routers.open-webui.service=open-webui
      - traefik.http.services.open-webui.loadbalancer.server.port=8080
    networks:
      - ollama-net
      - coolify
    env_file:
      - .env

volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui

networks:
  ollama-net:
    name: ollama-net
    driver: bridge
  coolify:
    name: coolify
    external: true
