# Generated by Django 5.2.16 on 2026-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_productpage_editions_alter_productpage_gallery'),
        ('pages', '0027_merge_20260808_1005'),
    ]

    operations = [
    ]
