# Generated by Django 5.2.11 on 2026-02-12 07:06

import colorfield.fields
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_background_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Background color for the contact form container', image_field=None, max_length=25, samples=None, verbose_name='Form Background Color'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_button_color',
            field=colorfield.fields.ColorField(default='#0d6efd', help_text='Background color for the submit button', image_field=None, max_length=25, samples=None, verbose_name='Button Background Color'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Text color for the submit button', image_field=None, max_length=25, samples=None, verbose_name='Button Text Color'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Text color for the form labels and inputs', image_field=None, max_length=25, samples=None, verbose_name='Form Text Color'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form',
            field=wagtail.fields.StreamField([('contact_form', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'contact-form', 'help_text': 'Unique ID for this form', 'label': 'Form ID', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Form Title', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Intro Text', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('number', 'Number'), ('url', 'URL'), ('file', 'File Upload'), ('hidden', 'Hidden Field')], 'label': 'Field Type'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display label for the field', 'label': 'Field Label', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML name attribute (no spaces, lowercase)', 'label': 'Field Name', 'max_length': 50}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Placeholder Text', 'max_length': 100, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Help Text', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Required'}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Default Value', 'max_length': 200, 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('half', 'Half Width'), ('third', 'One Third'), ('two-thirds', 'Two Thirds')], 'help_text': 'Control field width in multi-column layouts', 'label': 'Field Width', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "FontAwesome icon class (e.g., 'user', 'envelope')", 'label': 'Field Icon', 'max_length': 50, 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Value', 'max_length': 100}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Display Label', 'max_length': 100}), 14: ('wagtail.blocks.StructBlock', [[('value', 12), ('label', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'For dropdown or radio buttons', 'label': 'Options', 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'label': 'Minimum Length', 'min_value': 0, 'required': False}), 17: ('wagtail.blocks.IntegerBlock', (), {'label': 'Maximum Length', 'min_value': 1, 'required': False}), 18: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'For number fields', 'label': 'Minimum Value', 'required': False}), 19: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'For number fields', 'label': 'Maximum Value', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Regular expression pattern', 'label': 'Validation Pattern', 'max_length': 200, 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Custom Error Message', 'max_length': 200, 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Show this field only when another field has a specific value', 'label': 'Conditional Field', 'max_length': 50, 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Value that triggers this field to show', 'label': 'Conditional Value', 'max_length': 100, 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('field_type', 3), ('label', 4), ('name', 5), ('placeholder', 6), ('help_text', 7), ('required', 8), ('default_value', 9), ('field_width', 10), ('icon', 11), ('choices', 15), ('min_length', 16), ('max_length', 17), ('min_value', 18), ('max_value', 19), ('pattern', 20), ('error_message', 21), ('conditional_field', 22), ('conditional_value', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {'default': [{'field_type': 'text', 'label': 'Full Name', 'name': 'name', 'placeholder': 'Enter your full name', 'required': True}, {'field_type': 'email', 'label': 'Email Address', 'name': 'email', 'placeholder': 'Enter your email address', 'required': True}, {'field_type': 'textarea', 'label': 'Message', 'name': 'message', 'placeholder': 'How can we help you?', 'required': True}], 'label': 'Form Fields'}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Send Message', 'label': 'Submit Button Text', 'max_length': 50}), 27: ('wagtail.blocks.RichTextBlock', (), {'default': "Thank you for your message! We'll get back to you within 24 hours.", 'features': ['bold', 'italic', 'link'], 'label': 'Success Message'}), 28: ('wagtail.blocks.RichTextBlock', (), {'default': 'There was an error submitting your message. Please try again or contact us directly.', 'features': ['bold', 'italic', 'link'], 'label': 'Error Message'}), 29: ('wagtail.blocks.StructBlock', [[('form_id', 0), ('form_title', 1), ('intro_text', 2), ('fields', 25), ('button_text', 26), ('success_message', 27), ('error_message', 28)]], {})}),
        ),
    ]
