# Generated by Django 5.2.11 on 2026-02-18 01:11

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_simplify_contact_form_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='conditional_logic_rules',
            field=models.JSONField(blank=True, help_text='JSON configuration for conditional field display', null=True, verbose_name='Conditional Logic Rules'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='custom_validation_message',
            field=models.CharField(blank=True, help_text='Override default validation error message', max_length=200, verbose_name='Custom Validation Message'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='enable_conditional_fields',
            field=models.BooleanField(default=False, help_text='Show/hide fields based on other field values', verbose_name='Enable Conditional Fields'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='enable_form_validation',
            field=models.BooleanField(default=True, help_text='Validate form fields before submission', verbose_name='Enable Form Validation'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='enable_spam_protection',
            field=models.BooleanField(default=True, help_text='Add honeypot and rate limiting', verbose_name='Enable Spam Protection'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='max_submissions_per_hour',
            field=models.PositiveIntegerField(default=5, help_text='Maximum form submissions allowed per user per hour', verbose_name='Max Submissions Per Hour'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email address to receive form submissions (defaults to site admin)', max_length=254, verbose_name='Notification Email'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='require_email_verification',
            field=models.BooleanField(default=False, help_text='Send verification email before processing submission', verbose_name='Require Email Verification'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=True, help_text='Send confirmation email to submitter', verbose_name='Send Confirmation Email'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form',
            field=wagtail.fields.StreamField([('contact_form', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'contact-form', 'help_text': 'Unique ID for this form (used for DOM identification)', 'label': 'Form ID', 'max_length': 50}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], 'label': 'Field Type'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display label for the field', 'label': 'Field Label', 'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML name attribute (lowercase, no spaces)', 'label': 'Field Name', 'max_length': 50}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Placeholder Text', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Help Text', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Required Field', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Value', 'max_length': 100}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Display Label', 'max_length': 100}), 9: ('wagtail.blocks.StructBlock', [[('value', 7), ('label', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'For dropdown fields only', 'label': 'Options', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('field_type', 1), ('label', 2), ('name', 3), ('placeholder', 4), ('help_text', 5), ('required', 6), ('choices', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'default': [{'field_type': 'text', 'label': 'Full Name', 'name': 'name', 'placeholder': 'Enter your full name', 'required': True}, {'field_type': 'email', 'label': 'Email Address', 'name': 'email', 'placeholder': 'Enter your email address', 'required': True}, {'field_type': 'textarea', 'label': 'Message', 'name': 'message', 'placeholder': 'How can we help you?', 'required': True}], 'help_text': 'Add, remove, or reorder form fields', 'label': 'Form Fields'}), 13: ('wagtail.blocks.StructBlock', [[('form_id', 0), ('fields', 12)]], {})}),
        ),
    ]
