# Generated by Django 5.2.11 on 2026-02-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_homepage_cta_alter_homepage_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='map',
        ),
    ]
