# Generated by Django 5.2.13 on 2026-06-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='page',
            field=models.ForeignKey(blank=True, help_text='The page where the form was submitted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connect_form_submissions', to='wagtailcore.page', verbose_name='Page'),
        ),
    ]
