"""
Management command: generate_ts_schemas

Generates TypeScript type definitions from the schemas/ Pydantic models
using .model_json_schema() and writes to next-lms/src/types/api-schema.d.ts.

Usage:
    python manage.py generate_ts_schemas
    python manage.py generate_ts_schemas --output /custom/path/api.d.ts
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from django.core.management.base import BaseCommand
from django_fusion.site.management.commands.base import BaseCommand

# __file__ = .../ctc-research/www/schemas/management/commands/generate_ts_schemas.py
# parents[5] = websites/
DEFAULT_OUTPUT = Path(__file__).resolve().parents[5] / "next-lms" / "src" / "types" / "api-schema.d.ts"


def _model_to_ts_interface(model_cls: type) -> str:
    """Convert a Pydantic model to a TypeScript interface using .model_json_schema()."""
    schema = model_cls.model_json_schema()
    title = schema.get("title", model_cls.__name__)
    properties = schema.get("properties", {})
    required_fields = set(schema.get("required", []))

    lines = [f"export interface {title} {{"]
    for prop_name, prop_schema in properties.items():
        ts_type = _prop_to_ts(prop_schema)
        optional = "?" if prop_name not in required_fields else ""
        description = prop_schema.get("description", "")
        if description:
            lines.append(f"  /** {description} */")
        lines.append(f"  {prop_name}{optional}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _prop_to_ts(prop_schema: dict) -> str:
    """Map a JSON Schema property definition to its TypeScript type."""
    # Handle $ref (nested model references)
    if "$ref" in prop_schema:
        ref_name = prop_schema["$ref"].split("/")[-1]
        return ref_name

    # Handle anyOf (union types, including nullable)
    if "anyOf" in prop_schema:
        types = []
        for option in prop_schema["anyOf"]:
            if "type" in option:
                types.append(_json_type_to_ts(option["type"]))
            elif "$ref" in option:
                types.append(option["$ref"].split("/")[-1])
        return " | ".join(types)

    # Handle array types
    schema_type = prop_schema.get("type", "string")
    if schema_type == "array":
        items = prop_schema.get("items", {})
        item_type = _prop_to_ts(items) if items else "any"
        return f"Array<{item_type}>"

    return _json_type_to_ts(schema_type)


def _json_type_to_ts(json_type: str | list[str]) -> str:
    """Convert JSON Schema type(s) to TypeScript."""
    if isinstance(json_type, list):
        parts = [_json_type_to_ts(t) for t in json_type]
        return " | ".join(parts)
    mapping = {
        "integer": "number", "number": "number", "string": "string",
        "boolean": "boolean", "object": "Record<string, any>",
        "null": "null", "array": "Array<any>",
    }
    return mapping.get(json_type, "any")


def generate_ts_schemas(output_path: Path) -> str:
    """Generate TypeScript interfaces for all schemas/ Pydantic models."""

    from apps.core.schemas import (
        AuthTokenResponse,
        CategoryResponse,
        ContactRequest,
        ContactResponse,
        CourseResponse,
        ErrorResponse,
        HealthResponse,
        LoginRequest,
        PaginationMeta,
        PublicationResponse,
        RegisterRequest,
        TeamMemberResponse,
        UserResponse,
    )

    schemas = [
        ("Core", [HealthResponse, ErrorResponse, PaginationMeta]),
        ("Courses", [CourseResponse, CategoryResponse]),
        ("Research", [PublicationResponse, TeamMemberResponse]),
        ("Auth", [LoginRequest, RegisterRequest, UserResponse, AuthTokenResponse]),
        ("Contact", [ContactRequest, ContactResponse]),
    ]

    lines = [
        "// Auto-generated by: python manage.py generate_ts_schemas",
        "// Source: www/schemas/ — Pydantic models, single source of truth for API contracts",
        "// Do not edit manually — changes will be overwritten.",
        "",
    ]

    for category, classes in schemas:
        lines.append(f"// ══ {category} ══")
        lines.append("")
        for cls in classes:
            lines.append(_model_to_ts_interface(cls))
            lines.append("")
        lines.append("")

    # Add generic wrappers that Pydantic can't auto-generate
    lines.append("// ══ Generic pagination (hand-written) ══")
    lines.append("")
    lines.append("export interface PaginatedResponse<T> {")
    lines.append("  data: T[];")
    lines.append("  pagination: PaginationMeta;")
    lines.append("}")
    lines.append("")
    lines.append("export interface SingleResponse<T> {")
    lines.append("  data: T;")
    lines.append("}")
    lines.append("")

    content = "\n".join(lines)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)

    return content


class Command(BaseCommand):
    help = "Generate TypeScript type definitions from schemas/ Pydantic models"

    def add_arguments(self, parser):
        parser.add_argument(
            "--output", "-o",
            type=str,
            default=str(DEFAULT_OUTPUT),
            help=f"Output path for .d.ts file (default: {DEFAULT_OUTPUT})",
        )

    def handle(self, *args, **options):
        output_path = Path(options["output"])
        content = generate_ts_schemas(output_path)
        self.stdout.write(self.style.SUCCESS(
            f"Generated {len(content.splitlines())} lines → {output_path}"
        ))
