[project]
name = "libs-workspace"
version = "0.1.0"
requires-python = ">=3.10"

[tool.uv.workspace]
members = ["django-grep", "django-osoul", "django-rseal", "nawaai"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"

[tool.uv.sources]
django-osoul = { workspace = true }
django-rseal = { workspace = true }
django-grep  = { workspace = true }
nawaai       = { workspace = true }
