# Generated by Django 5.2.13 on 2026-07-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handlers', '0002_alter_event_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
