# Generated by Django 5.2.13 on 2026-07-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceptor_ai', '0024_backgroundtasklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundTaskLog',
        ),
    ]
