# Generated by Django 5.2.13 on 2026-07-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceptor_ai', '0058_backgroundtasklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundTaskLog',
        ),
    ]
