# Generated by Django 5.2.13 on 2026-07-04 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceptor_ai', '0059_delete_backgroundtasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('queue_name', models.CharField(default='default', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Background Task Log',
                'verbose_name_plural': 'Background Task Logs',
                'db_table': 'grep_background_task_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
