# Generated by Django 5.2.13 on 2026-07-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceptor_ai', '0122_backgroundtasklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundTaskLog',
        ),
    ]
