# Generated by Django 5.2.11 on 2026-02-18 00:53

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutpage_enable_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='button_text',
            field=models.CharField(default='Send Message', max_length=50, verbose_name='Submit Button Text'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='error_message',
            field=wagtail.fields.RichTextField(blank=True, default="<p>🔄 <strong>A temporary detour...</strong></p><p>Sometimes even the best-laid plans need a second try.<br/>Your message couldn't be sent, but don't let this pause stop you.<br/>Please try again, or reach us directly through the contact details below.</p>", help_text='Message shown when form submission fails', verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text displayed above the form', verbose_name='Form Introduction'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional heading above the form', verbose_name='Form Title'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='success_message',
            field=wagtail.fields.RichTextField(blank=True, default="<p>✨ <strong>Your message has wings!</strong></p><p>Thank you for reaching out. Like a carefully sealed envelope,<br/>your words are now in our hands. We'll respond within 24 hours,<br/>bringing thoughtful answers to your thoughtful questions.</p>", help_text='Message shown after successful form submission', verbose_name='Success Message'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_details',
            field=wagtail.fields.StreamField([('address', 4), ('phone', 9), ('email', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-house', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Our Home', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.ListBlock', (2,), {'default': ['Where innovation anchors deep,', 'And dreams find their address.']}), 4: ('wagtail.blocks.StructBlock', [[('icon_class', 0), ('title', 1), ('lines', 3)]], {'icon': 'home', 'label': 'Address'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-support-1', 'max_length': 50}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Voices Connect', 'max_length': 100}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': ['Every ring, a new possibility', 'Every call, a step closer']}), 9: ('wagtail.blocks.StructBlock', [[('icon_class', 5), ('title', 6), ('lines', 8)]], {'icon': 'phone', 'label': 'Phone'}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-email', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Digital Doorway', 'max_length': 100}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': ['hello@example.com', 'support@example.com']}), 14: ('wagtail.blocks.StructBlock', [[('icon_class', 10), ('title', 11), ('lines', 13)]], {'icon': 'mail', 'label': 'Email'})}),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form',
            field=wagtail.fields.StreamField([('contact_form', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'contact-form', 'help_text': 'Unique ID for this form (used for DOM identification)', 'label': 'Form ID', 'max_length': 50}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('number', 'Number'), ('url', 'URL'), ('file', 'File Upload'), ('hidden', 'Hidden Field')], 'label': 'Field Type'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display label for the field', 'label': 'Field Label', 'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML name attribute (no spaces, lowercase)', 'label': 'Field Name', 'max_length': 50}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Placeholder Text', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Help Text', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Required'}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Default Value', 'max_length': 200, 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('half', 'Half Width'), ('third', 'One Third'), ('two-thirds', 'Two Thirds')], 'help_text': 'Control field width in multi-column layouts', 'label': 'Field Width', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': "FontAwesome icon class (e.g., 'user', 'envelope')", 'label': 'Field Icon', 'max_length': 50, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Value', 'max_length': 100}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Display Label', 'max_length': 100}), 12: ('wagtail.blocks.StructBlock', [[('value', 10), ('label', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'For dropdown or radio buttons', 'label': 'Options', 'required': False}), 14: ('wagtail.blocks.IntegerBlock', (), {'label': 'Minimum Length', 'min_value': 0, 'required': False}), 15: ('wagtail.blocks.IntegerBlock', (), {'label': 'Maximum Length', 'min_value': 1, 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'For number fields', 'label': 'Minimum Value', 'required': False}), 17: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'For number fields', 'label': 'Maximum Value', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Regular expression pattern', 'label': 'Validation Pattern', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Custom Error Message', 'max_length': 200, 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Show this field only when another field has a specific value', 'label': 'Conditional Field', 'max_length': 50, 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Value that triggers this field to show', 'label': 'Conditional Value', 'max_length': 100, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('field_type', 1), ('label', 2), ('name', 3), ('placeholder', 4), ('help_text', 5), ('required', 6), ('default_value', 7), ('field_width', 8), ('icon', 9), ('choices', 13), ('min_length', 14), ('max_length', 15), ('min_value', 16), ('max_value', 17), ('pattern', 18), ('error_message', 19), ('conditional_field', 20), ('conditional_value', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'default': [{'field_type': 'text', 'label': 'Full Name', 'name': 'name', 'placeholder': 'Enter your full name', 'required': True}, {'field_type': 'email', 'label': 'Email Address', 'name': 'email', 'placeholder': 'Enter your email address', 'required': True}, {'field_type': 'textarea', 'label': 'Message', 'name': 'message', 'placeholder': 'How can we help you?', 'required': True}], 'help_text': 'Add, remove, or reorder form fields', 'label': 'Form Fields'}), 24: ('wagtail.blocks.StructBlock', [[('form_id', 0), ('fields', 23)]], {})}),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_info',
            field=wagtail.fields.StreamField([('contact_info', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Reach Out to Us', 'label': 'Subtitle', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Where Questions Find Answers, And Conversations Begin', 'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'In every message sent,\nA bridge is built between us.\nYour words, our compass—\nGuiding us to serve you better.\nTogether we craft solutions,\nWhere vision meets dedication.', 'label': 'Description'}), 3: ('wagtail.blocks.StructBlock', [[('subtitle', 0), ('title', 1), ('description', 2)]], {'icon': 'info', 'label': 'Contact Info'})}),
        ),
    ]
