# Generated by Django 5.2.11 on 2026-02-18 02:08

import colorfield.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_advanced_form_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='button_text',
            field=models.CharField(default='Send Message', max_length=50, verbose_name='Submit Button Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='conditional_logic_rules',
            field=models.JSONField(blank=True, null=True, verbose_name='Conditional Logic Rules'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_form',
            field=wagtail.fields.StreamField([('contact_form', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'contact-form', 'help_text': 'Unique ID for this form (used for DOM identification)', 'label': 'Form ID', 'max_length': 50}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], 'label': 'Field Type'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display label for the field', 'label': 'Field Label', 'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML name attribute (lowercase, no spaces)', 'label': 'Field Name', 'max_length': 50}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Placeholder Text', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Help Text', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Required Field', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Value', 'max_length': 100}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Display Label', 'max_length': 100}), 9: ('wagtail.blocks.StructBlock', [[('value', 7), ('label', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'For dropdown fields only', 'label': 'Options', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('field_type', 1), ('label', 2), ('name', 3), ('placeholder', 4), ('help_text', 5), ('required', 6), ('choices', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'default': [{'field_type': 'text', 'label': 'Full Name', 'name': 'name', 'placeholder': 'Enter your full name', 'required': True}, {'field_type': 'email', 'label': 'Email Address', 'name': 'email', 'placeholder': 'Enter your email address', 'required': True}, {'field_type': 'textarea', 'label': 'Message', 'name': 'message', 'placeholder': 'How can we help you?', 'required': True}], 'help_text': 'Add, remove, or reorder form fields', 'label': 'Form Fields'}), 13: ('wagtail.blocks.StructBlock', [[('form_id', 0), ('fields', 12)]], {})}, verbose_name='Form Block'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_validation_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='Custom Validation Message'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enable_conditional_fields',
            field=models.BooleanField(default=False, verbose_name='Enable Conditional Fields'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enable_form_validation',
            field=models.BooleanField(default=True, verbose_name='Enable Form Validation'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enable_spam_protection',
            field=models.BooleanField(default=True, verbose_name='Enable Spam Protection'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='error_message',
            field=wagtail.fields.RichTextField(blank=True, default="<p>🔄 <strong>A temporary detour...</strong></p><p>Sometimes even the best-laid plans need a second try.<br/>Your message couldn't be sent, but don't let this pause stop you.<br/>Please try again, or reach us directly through the contact details below.</p>", help_text='Message shown when form submission fails', verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_background_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Background color for the contact form container', image_field=None, max_length=25, samples=None, verbose_name='Form Background Color'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_button_color',
            field=colorfield.fields.ColorField(default='#0d6efd', help_text='Background color for the submit button', image_field=None, max_length=25, samples=None, verbose_name='Button Background Color'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_button_text_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Text color for the submit button', image_field=None, max_length=25, samples=None, verbose_name='Button Text Color'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text displayed above the form', verbose_name='Form Introduction'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_text_color',
            field=colorfield.fields.ColorField(default='#000000', help_text='Text color for the form labels and inputs', image_field=None, max_length=25, samples=None, verbose_name='Form Text Color'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='form_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional heading above the form', verbose_name='Form Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='max_submissions_per_hour',
            field=models.PositiveIntegerField(default=5, verbose_name='Max Submissions Per Hour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email address to receive form submissions', max_length=254, verbose_name='Notification Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='require_email_verification',
            field=models.BooleanField(default=False, verbose_name='Require Email Verification'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='send_confirmation_email',
            field=models.BooleanField(default=True, verbose_name='Send Confirmation Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='success_message',
            field=wagtail.fields.RichTextField(blank=True, default="<p>✨ <strong>Your message has wings!</strong></p><p>Thank you for reaching out. Like a carefully sealed envelope,<br/>your words are now in our hands. We'll respond within 24 hours,<br/>bringing thoughtful answers to your thoughtful questions.</p>", help_text='Message shown after successful form submission', verbose_name='Success Message'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='conditional_logic_rules',
            field=models.JSONField(blank=True, null=True, verbose_name='Conditional Logic Rules'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form',
            field=wagtail.fields.StreamField([('contact_form', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'contact-form', 'help_text': 'Unique ID for this form (used for DOM identification)', 'label': 'Form ID', 'max_length': 50}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], 'label': 'Field Type'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Display label for the field', 'label': 'Field Label', 'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'HTML name attribute (lowercase, no spaces)', 'label': 'Field Name', 'max_length': 50}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Placeholder Text', 'max_length': 100, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Help Text', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Required Field', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Value', 'max_length': 100}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Display Label', 'max_length': 100}), 9: ('wagtail.blocks.StructBlock', [[('value', 7), ('label', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'For dropdown fields only', 'label': 'Options', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('field_type', 1), ('label', 2), ('name', 3), ('placeholder', 4), ('help_text', 5), ('required', 6), ('choices', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'default': [{'field_type': 'text', 'label': 'Full Name', 'name': 'name', 'placeholder': 'Enter your full name', 'required': True}, {'field_type': 'email', 'label': 'Email Address', 'name': 'email', 'placeholder': 'Enter your email address', 'required': True}, {'field_type': 'textarea', 'label': 'Message', 'name': 'message', 'placeholder': 'How can we help you?', 'required': True}], 'help_text': 'Add, remove, or reorder form fields', 'label': 'Form Fields'}), 13: ('wagtail.blocks.StructBlock', [[('form_id', 0), ('fields', 12)]], {})}, verbose_name='Form Block'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='custom_validation_message',
            field=models.CharField(blank=True, max_length=200, verbose_name='Custom Validation Message'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='enable_conditional_fields',
            field=models.BooleanField(default=False, verbose_name='Enable Conditional Fields'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='enable_form_validation',
            field=models.BooleanField(default=True, verbose_name='Enable Form Validation'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='enable_spam_protection',
            field=models.BooleanField(default=True, verbose_name='Enable Spam Protection'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='max_submissions_per_hour',
            field=models.PositiveIntegerField(default=5, verbose_name='Max Submissions Per Hour'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email address to receive form submissions', max_length=254, verbose_name='Notification Email'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='require_email_verification',
            field=models.BooleanField(default=False, verbose_name='Require Email Verification'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=True, verbose_name='Send Confirmation Email'),
        ),
    ]
