from django_osoul.comp.blocks.media.image import SimpleImageBlock

# Generated by Django 5.2.11 on 2026-02-18 02:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homepage_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_details',
            field=wagtail.fields.StreamField([('address', 4), ('phone', 9), ('email', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-house', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Our Home', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.ListBlock', (2,), {'default': ['Where innovation anchors deep,', 'And dreams find their address.']}), 4: ('wagtail.blocks.StructBlock', [[('icon_class', 0), ('title', 1), ('lines', 3)]], {'icon': 'home', 'label': 'Address Detail'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-support-1', 'max_length': 50}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Voices Connect', 'max_length': 100}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': ['Every ring, a new possibility', 'Every call, a step closer']}), 9: ('wagtail.blocks.StructBlock', [[('icon_class', 5), ('title', 6), ('lines', 8)]], {'icon': 'phone', 'label': 'Phone Detail'}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-email', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Digital Doorway', 'max_length': 100}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': ['hello@example.com', 'support@example.com']}), 14: ('wagtail.blocks.StructBlock', [[('icon_class', 10), ('title', 11), ('lines', 13)]], {'icon': 'mail', 'label': 'Email Detail'})}, verbose_name='Contact Details'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_info',
            field=wagtail.fields.StreamField([('contact_info', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Reach Out to Us', 'label': 'Subtitle', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Where Questions Find Answers, And Conversations Begin', 'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'In every message sent,\nA bridge is built between us.\nYour words, our compass—\nGuiding us to serve you better.\nTogether we craft solutions,\nWhere vision meets dedication.', 'label': 'Description'}), 3: ('wagtail.blocks.StructBlock', [[('subtitle', 0), ('title', 1), ('description', 2)]], {'icon': 'info', 'label': 'Contact Info Summary'})}, verbose_name='Contact Info Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'help_text': 'Title for the FAQ section', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Optional description for the FAQ section', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('general', 'General Questions'), ('ai_training', 'AI Training & Tools'), ('medical_research', 'Medical Research Hub'), ('technical', 'Technical Support'), ('account', 'Account & Access'), ('data', 'Data & Privacy')], 'help_text': 'Select FAQ category'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the frequently asked question', 'max_length': 200, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Provide a detailed answer', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Add FAQ items to this section', 'min_num': 1}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show contact prompt after FAQ section', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('section_description', 1), ('category', 2), ('faq_items', 6), ('show_contact_prompt', 7)]], {})}, verbose_name='FAQ Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map',
            field=wagtail.fields.StreamField([('map', 2)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'default': 'https://maps.google.com/maps?hl=en&amp;q=Dhaka&amp;t=&amp;z=10&amp;iwloc=B&amp;output=embed', 'help_text': 'Google Maps embed URL.'}), 1: ('wagtail.blocks.CharBlock', (), {'default': '500px', 'help_text': 'Map height in pixels (e.g., 500px).', 'max_length': 20}), 2: ('wagtail.blocks.StructBlock', [[('map_embed_url', 0), ('map_height', 1)]], {'icon': 'place', 'label': 'Map Section'})}, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_details',
            field=wagtail.fields.StreamField([('address', 4), ('phone', 9), ('email', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-house', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Our Home', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.ListBlock', (2,), {'default': ['Where innovation anchors deep,', 'And dreams find their address.']}), 4: ('wagtail.blocks.StructBlock', [[('icon_class', 0), ('title', 1), ('lines', 3)]], {'icon': 'home', 'label': 'Address Detail'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-support-1', 'max_length': 50}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Voices Connect', 'max_length': 100}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 8: ('wagtail.blocks.ListBlock', (7,), {'default': ['Every ring, a new possibility', 'Every call, a step closer']}), 9: ('wagtail.blocks.StructBlock', [[('icon_class', 5), ('title', 6), ('lines', 8)]], {'icon': 'phone', 'label': 'Phone Detail'}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'flaticon-email', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Digital Doorway', 'max_length': 100}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': ['hello@example.com', 'support@example.com']}), 14: ('wagtail.blocks.StructBlock', [[('icon_class', 10), ('title', 11), ('lines', 13)]], {'icon': 'mail', 'label': 'Email Detail'})}, verbose_name='Contact Details'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_info',
            field=wagtail.fields.StreamField([('contact_info', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Reach Out to Us', 'label': 'Subtitle', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Where Questions Find Answers, And Conversations Begin', 'label': 'Title', 'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'default': 'In every message sent,\nA bridge is built between us.\nYour words, our compass—\nGuiding us to serve you better.\nTogether we craft solutions,\nWhere vision meets dedication.', 'label': 'Description'}), 3: ('wagtail.blocks.StructBlock', [[('subtitle', 0), ('title', 1), ('description', 2)]], {'icon': 'info', 'label': 'Contact Info Summary'})}, verbose_name='Contact Info Section'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'help_text': 'Title for the FAQ section', 'max_length': 100, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Optional description for the FAQ section', 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('general', 'General Questions'), ('ai_training', 'AI Training & Tools'), ('medical_research', 'Medical Research Hub'), ('technical', 'Technical Support'), ('account', 'Account & Access'), ('data', 'Data & Privacy')], 'help_text': 'Select FAQ category'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the frequently asked question', 'max_length': 200, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Provide a detailed answer', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('question', 3), ('answer', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Add FAQ items to this section', 'min_num': 1}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show contact prompt after FAQ section', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('section_title', 0), ('section_description', 1), ('category', 2), ('faq_items', 6), ('show_contact_prompt', 7)]], {})}, verbose_name='FAQ Section'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map',
            field=wagtail.fields.StreamField([('map', 2)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'default': 'https://maps.google.com/maps?hl=en&amp;q=Dhaka&amp;t=&amp;z=10&amp;iwloc=B&amp;output=embed', 'help_text': 'Google Maps embed URL.'}), 1: ('wagtail.blocks.CharBlock', (), {'default': '500px', 'help_text': 'Map height in pixels (e.g., 500px).', 'max_length': 20}), 2: ('wagtail.blocks.StructBlock', [[('map_embed_url', 0), ('map_height', 1)]], {'icon': 'place', 'label': 'Map Section'})}, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='summary',
            field=wagtail.fields.StreamField([('about', 9), ('listing_section', 16)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 20}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'required': True}), 7: ('wagtail.blocks.StructBlock', [[('icon_class', 5), ('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('service_item', 7)]], {'label': 'Services Items'}), 9: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('years_experience', 1), ('welcome_text', 2), ('main_title', 3), ('description', 4), ('service_items', 8)]], {'icon': 'info', 'label': 'About Section'}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 12: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Select Index Page', 'required': True}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('index_page', 12), ('icon_class', 10), ('description', 13)]], {'icon': 'folder-open-inverse', 'label': 'Listing Item'}), 15: ('wagtail.blocks.StreamBlock', [[('listing', 14)]], {'label': 'Listings', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('subtitle', 10), ('title', 11), ('listing_pages', 15)]], {'icon': 'folder-open-inverse', 'label': 'Listing Section'})}),
        ),
    ]
