# Generated by Django 5.2.11 on 2026-02-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_aboutpage_facts_alter_aboutpage_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='show_cta_banner',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='conditional_logic_rules',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='custom_validation_message',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='enable_conditional_fields',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='enable_form_validation',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='enable_spam_protection',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='max_submissions_per_hour',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='notification_email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='require_email_verification',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='send_confirmation_email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='show_cta_banner',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='conditional_logic_rules',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='custom_validation_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='enable_conditional_fields',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='enable_form_validation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='enable_spam_protection',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='max_submissions_per_hour',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='notification_email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='require_email_verification',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='send_confirmation_email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_cta_banner',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='enable_dark_mode',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='show_cta_banner',
        ),
    ]
