# Generated by Django 5.2.13 on 2026-07-29 01:05

import apps.core.domain.models.coupon
import colorfield.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import modelsearch.index
import taggit.managers
import uuid
import wagtail.fields
import wagtail.models.preview
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_fusion', '__first__'),
        ('sites', '0006_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.core.domain.models.coupon._generate_code, help_text='Unique alphanumeric code. Auto-generated if blank.', max_length=50, unique=True, verbose_name='Coupon Code')),
                ('name', models.CharField(blank=True, default='', help_text='Internal description for this coupon.', max_length=255, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount depending on type.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage coupons. Leave blank for no cap.', max_digits=10, null=True, verbose_name='Max Discount Cap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiry.', null=True, verbose_name='Valid Until')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum total redemptions. 0 = unlimited.', verbose_name='Max Total Uses')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum times a single user can use this coupon.', verbose_name='Max Uses Per User')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Auto-incremented. Do not edit manually.', verbose_name='Times Used')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart/course price required to apply this coupon.', max_digits=10, verbose_name='Minimum Order Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Name used in templates as {{ variable_name }}', max_length=50, verbose_name='Variable Name')),
                ('description', models.CharField(help_text='What this variable represents', max_length=200, verbose_name='Description')),
                ('default_value', models.CharField(blank=True, help_text='Default value if not provided in context', max_length=200, verbose_name='Default Value')),
                ('is_required', models.BooleanField(default=False, help_text='This variable must be provided in context', verbose_name='Required')),
                ('variable_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('email', 'Email'), ('date', 'Date'), ('number', 'Number'), ('boolean', 'Boolean'), ('color', 'Color'), ('image', 'Image'), ('file', 'File')], default='text', max_length=20, verbose_name='Type')),
                ('validation_regex', models.CharField(blank=True, help_text='Regular expression for validating this variable (optional)', max_length=200, verbose_name='Validation Regex')),
            ],
            options={
                'verbose_name': 'Template Variable',
                'verbose_name_plural': 'Template Variables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this certificate template.', max_length=255, verbose_name='Template Name')),
                ('organization_name', models.CharField(default='STRUCTA RESEARCH HUB', help_text='Displayed at the top of the certificate.', max_length=255, verbose_name='Organization Name')),
                ('certificate_title', models.CharField(default='CERTIFICATE OF ATTENDANCE', max_length=255, verbose_name='Certificate Title')),
                ('footer_text', models.CharField(default='STRUCTA CENTER TEAM', help_text='Text displayed at the bottom of the certificate.', max_length=255, verbose_name='Footer Text')),
                ('body_text', models.CharField(default='has successfully attended and completed the training course titled:', help_text='Text between recipient name and course title.', max_length=500, verbose_name='Body Text')),
                ('certifies_text', models.CharField(default='This certifies that:', max_length=255, verbose_name='Certifies Text')),
                ('border_color', colorfield.fields.ColorField(default='#2c3e50', help_text='Main border and header/footer line color.', image_field=None, max_length=25, samples=None, verbose_name='Border Color')),
                ('accent_color', colorfield.fields.ColorField(default='#3498db', help_text='Organization name and corner decoration color.', image_field=None, max_length=25, samples=None, verbose_name='Accent Color')),
                ('text_color', colorfield.fields.ColorField(default='#333333', help_text='Default text color in the certificate body.', image_field=None, max_length=25, samples=None, verbose_name='Text Color')),
                ('custom_template', models.FileField(blank=True, help_text='Upload a custom HTML template. If blank, uses the default cert.html fallback at BASE_DIR.', null=True, upload_to='certifications/templates/', verbose_name='Custom HTML Template')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Additional CSS injected into the certificate.', verbose_name='Custom CSS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', wagtail.fields.RichTextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_image', models.ForeignKey(blank=True, help_text='Optional logo displayed in the header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo Image')),
                ('signature_image', models.ForeignKey(blank=True, help_text='Optional signature image in the footer area.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Signature Image')),
            ],
            options={
                'verbose_name': 'Certification Template',
                'verbose_name_plural': 'Certification Templates',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('label', models.CharField(blank=True, default='work', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='shared.contact')),
            ],
            options={
                'verbose_name': 'Contact Email',
                'verbose_name_plural': 'Contact Emails',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('label', models.CharField(blank=True, default='work', max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='shared.contact')),
            ],
            options={
                'verbose_name': 'Contact Phone',
                'verbose_name_plural': 'Contact Phones',
            },
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='companies', to='shared.contact')),
            ],
            options={
                'verbose_name': 'Corporate',
                'verbose_name_plural': 'Corporates',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='shared.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_from_email', models.EmailField(default='noreply@example.com', max_length=254, verbose_name='Default From Email')),
                ('default_from_name', models.CharField(default='CTC Hub', max_length=100, verbose_name='Default From Name')),
                ('enable_tracking', models.BooleanField(default=True, help_text='Track email opens and clicks in newsletters.', verbose_name='Enable Tracking')),
                ('use_marketing_consent', models.BooleanField(default=True, help_text='Only send newsletters to users who opted in.', verbose_name='Require Marketing Consent')),
                ('max_daily_emails', models.PositiveIntegerField(default=1000, help_text='Maximum number of emails that can be sent per day.', verbose_name='Max Daily Emails')),
                ('batch_size', models.PositiveIntegerField(default=100, help_text='Emails per sending batch.', verbose_name='Batch Size')),
                ('smtp_server', models.CharField(blank=True, help_text='Optional custom SMTP host for sending.', max_length=255, verbose_name='SMTP Server')),
                ('analytics_provider', models.CharField(blank=True, help_text='Optional service for email analytics (e.g., Mailchimp, Sendgrid).', max_length=255, verbose_name='Analytics Provider')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('ar', 'العربيّة')], default='en', help_text="Language code for these settings (e.g., 'en', 'fr').", max_length=10, verbose_name='Language Code')),
                ('active', models.BooleanField(default=False, help_text='Designates whether these settings are active for this language. Only one active per language.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('language',), name='unique_active_email_settings_per_language')],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('phone_number', models.CharField(blank=True, default='+1 800 123 4567', max_length=24, verbose_name='Phone number')),
                ('whatsapp_number', models.CharField(blank=True, default='+1 800 765 4321', help_text='Optional WhatsApp business contact.', max_length=24, verbose_name='WhatsApp number')),
                ('email', models.EmailField(blank=True, default='info@example.com', max_length=254, verbose_name='Email')),
                ('support_email', models.EmailField(blank=True, default='support@example.com', max_length=254, verbose_name='Support Email')),
                ('address', models.TextField(blank=True, default='123 Innovation Drive, San Francisco, CA 94105', verbose_name='Address')),
                ('google_maps_link', models.URLField(blank=True, help_text='Optional map link for location directions.', verbose_name='Google Maps Link')),
                ('organisation_url', models.URLField(blank=True, default='https://www.ctchub.com', verbose_name='Organisation URL')),
                ('additional_info', models.TextField(blank=True, default='Open Monday – Friday, 9:00am – 6:00pm (PST).', verbose_name='Additional Information')),
                ('social_links', wagtail.fields.StreamField([('link', 10)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('portfolio', 'Portfolio'), ('website', 'Personal Website'), ('other', 'Other Platform')], 'label': 'Platform'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Your username on this platform', 'label': 'Username/Handle', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Full URL to your profile (auto-generated if blank)', 'label': 'Profile URL', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "If 'Other Platform' is selected, specify the platform name", 'label': 'Custom Platform Name', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Auto-generated display name', 'label': 'Platform Display Name', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Mark as primary profile for this platform', 'label': 'Primary Profile', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show this profile publicly', 'label': 'Public Profile', 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Mark as verified if confirmed', 'label': 'Verified', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Optional CSS class for custom icons (e.g., FontAwesome classes).', 'label': 'Icon CSS Class', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Additional notes about this profile', 'label': 'Notes', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('platform', 0), ('username', 1), ('profile_url', 2), ('custom_platform', 3), ('platform_display', 4), ('is_primary', 5), ('is_public', 6), ('verified', 7), ('icon_class', 8), ('notes', 9)]], {})}, help_text='Add links to your social media profiles', verbose_name='Social links')),
                ('favicon', models.ForeignKey(blank=True, help_text='Small icon used in browser tabs and bookmarks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(help_text='Official display name of the company', max_length=200, verbose_name='Company Name')),
                ('legal_name', models.CharField(blank=True, help_text='Official legal name if different from display name', max_length=200, verbose_name='Legal Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of the company name', max_length=200, unique=True, verbose_name='Slug')),
                ('company_type', models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier'), ('partner', 'Partner'), ('vendor', 'Vendor'), ('competitor', 'Competitor'), ('educational', 'Educational Institution'), ('academic', 'Academic Institution'), ('internal', 'Internal Organization'), ('other', 'Other')], default='client', help_text='Primary classification of the company relationship', max_length=20, verbose_name='Company Type')),
                ('website', models.URLField(blank=True, help_text='Primary company website URL', verbose_name='Website')),
                ('email', models.EmailField(blank=True, help_text='General contact email address', max_length=254, verbose_name='General Email')),
                ('phone', models.CharField(blank=True, help_text='Main company phone number', max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Primary business address', verbose_name='Address')),
                ('country', models.CharField(blank=True, help_text='Company headquarters country', max_length=100, verbose_name='Country')),
                ('timezone', models.CharField(blank=True, default='UTC', help_text='Primary business timezone', max_length=50, verbose_name='Timezone')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance & Banking'), ('retail', 'Retail & E-commerce'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('other', 'Other')], default='other', help_text='Primary industry sector', max_length=20, verbose_name='Industry')),
                ('company_size', models.CharField(blank=True, choices=[('micro', 'Micro (1-10)'), ('small', 'Small (11-50)'), ('medium', 'Medium (51-200)'), ('large', 'Large (201-1000)'), ('enterprise', 'Enterprise (1000+)')], help_text='Approximate number of employees', max_length=20, verbose_name='Company Size')),
                ('employee_count', models.PositiveIntegerField(blank=True, help_text='Exact number of employees (if known)', null=True, verbose_name='Employee Count')),
                ('founded_year', models.PositiveIntegerField(blank=True, help_text='Year the company was founded', null=True, verbose_name='Founded Year')),
                ('tax_id', models.CharField(blank=True, help_text='Business tax identification number', max_length=100, verbose_name='Tax ID/VAT Number')),
                ('registration_number', models.CharField(blank=True, help_text='Company registration or business number', max_length=100, verbose_name='Registration Number')),
                ('brand_color', models.CharField(blank=True, help_text='Primary brand color in hex format', max_length=7, verbose_name='Brand Color')),
                ('is_displayed', models.BooleanField(default=False, help_text='Display this company in public directories and partner pages', verbose_name='Display Publicly')),
                ('partnership_level', models.CharField(blank=True, choices=[('strategic', 'Strategic Partner'), ('premium', 'Premium Partner'), ('standard', 'Standard Partner'), ('affiliate', 'Affiliate Partner')], help_text='Level of partnership (for partner companies only)', max_length=20, verbose_name='Partnership Level')),
                ('partnership_start_date', models.DateField(blank=True, help_text='When the partnership began', null=True, verbose_name='Partnership Start Date')),
                ('is_educational', models.BooleanField(default=False, help_text='This company is an educational institution', verbose_name='Educational Institution')),
                ('accreditation', models.TextField(blank=True, help_text='Educational accreditations and certifications', verbose_name='Accreditations')),
                ('institution_type', models.CharField(blank=True, choices=[('university', 'University'), ('college', 'College'), ('school', 'School'), ('training', 'Training Center'), ('online', 'Online Institution')], help_text='Type of educational institution', max_length=50, verbose_name='Institution Type')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Annual revenue in local currency', max_digits=15, null=True, verbose_name='Annual Revenue')),
                ('currency', models.CharField(default='USD', help_text='Primary currency for financial data', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Company is currently active and engaged', verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, help_text='Company information has been verified', verbose_name='Verified')),
                ('notes', models.TextField(blank=True, help_text='Additional internal notes about the company', verbose_name='Internal Notes')),
                ('logo', models.ForeignKey(blank=True, help_text='Official company logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Company Logo')),
                ('parent_company', models.ForeignKey(blank=True, help_text='Parent or holding company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='shared.organization', verbose_name='Parent Company')),
                ('relationship_manager', models.ForeignKey(blank=True, help_text='Primary contact person within our organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Relationship Manager')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('overview', models.CharField(blank=True, help_text='A short tagline or one-sentence summary for the service.', max_length=300, verbose_name='Overview')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the service and its purpose.', verbose_name='Description')),
                ('category', models.CharField(choices=[('lms', 'Learning Management System (LMS)'), ('crm', 'Customer Relationship Management (CRM)'), ('therapy', 'Therapy & Counselling'), ('consulting', 'Consulting Services'), ('support', 'Customer Support'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('icon', models.CharField(blank=True, help_text="Optional icon class (e.g., 'fa-solid fa-laptop').", max_length=100, verbose_name='Icon')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price for this service.', max_digits=10, null=True, verbose_name='Base Price')),
                ('pricing_notes', models.TextField(blank=True, help_text='Optional notes about pricing or subscription tiers.', verbose_name='Pricing Details')),
                ('title', models.CharField(blank=True, help_text='Optional title for the content section.', max_length=200, verbose_name='Section Title')),
                ('content', wagtail.fields.StreamField([('rich_text', 0), ('services_section', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('subtitle', 1), ('title', 2)]], {})}, help_text='Dynamic content sections for the service.', verbose_name='Content')),
                ('is_visible', models.BooleanField(default=True, help_text='Controls whether this section appears on the frontend.', verbose_name='Is Visible')),
                ('is_active', models.BooleanField(default=True, help_text='Determines whether this service is currently available.', verbose_name='Is Active')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this record is active', verbose_name='Is Active')),
                ('live', models.BooleanField(default=True, help_text='Whether this record is publicly accessible', verbose_name='Live')),
                ('first_published_at', models.DateTimeField(blank=True, null=True, verbose_name='First Published At')),
                ('last_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Published At')),
                ('search_description', models.TextField(blank=True, help_text='Description for search engines and social sharing', verbose_name='Search description')),
                ('email', models.EmailField(help_text='Primary contact email for receiving newsletters.', max_length=254, verbose_name='Email Address')),
                ('is_subscribed', models.BooleanField(default=True, help_text='Uncheck to unsubscribe from this newsletter type.', verbose_name='Is Subscribed')),
                ('subscription_type', models.CharField(choices=[('ALL', 'All Newsletters'), ('IMPORTANT', 'Important Announcements Only'), ('COURSE', 'Course-related Updates'), ('DEPARTMENT', 'Department News Only')], default='ALL', max_length=20, verbose_name='Subscription Type')),
                ('preferred_format', models.CharField(choices=[('HTML', 'HTML'), ('TEXT', 'Plain Text')], default='HTML', help_text='Preferred newsletter format.', max_length=10, verbose_name='Preferred Format')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Last Newsletter Sent')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='Date and time when user unsubscribed.', null=True, verbose_name='Unsubscribed At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('person', models.ForeignKey(blank=True, help_text='Linked user account (optional for guest subscribers).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'subscription_type')},
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='companies_slug_e0676c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['company_type'], name='companies_company_b23eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['industry'], name='companies_industr_7891ac_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_displayed'], name='companies_is_disp_2740e2_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_educational'], name='companies_is_educ_dfc6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='companies_is_acti_e9a12b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent_company'], name='companies_parent__ece8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user'], name='profiles_user_id_29277a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='profiles_email_2f292b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_registered'], name='profiles_is_regi_19005b_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status'], name='profiles_status_0dafe7_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['profile_type'], name='profiles_profile_3cdb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_at'], name='profiles_created_cbafd1_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['updated_at'], name='profiles_updated_7c22e2_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['slug'], name='profiles_slug_a9ab23_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['country', 'city'], name='profiles_country_61d005_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_active'], name='profiles_last_ac_8ceaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['profile_completion'], name='profiles_profile_d24a44_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='services_name_a79f61_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_categor_54c742_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_is_acti_b1f5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['slug'], name='departments_slug_b4a8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_c59a45_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company'], name='departments_company_d64605_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['function'], name='departments_functio_b775f8_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department'], name='departments_parent__cf33d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_department_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['slug'], name='teams_slug_cf7c43_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_name_12b53a_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['department'], name='teams_departm_913365_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_type'], name='teams_team_ty_36cd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='teams_status_a555a5_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='teams_is_acti_dd3222_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['display_order'], name='teams_display_6c30fa_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['active_since'], name='teams_active__c32b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['person', 'team'], name='team_member_person__fe3b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['status'], name='team_member_status_8e7cee_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['is_primary_team'], name='team_member_is_prim_1621b5_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['date_joined'], name='team_member_date_jo_1a4d2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('person', 'team')},
        ),
        migrations.AddConstraint(
            model_name='techbridges',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('language',), name='unique_active_brand_settings_per_language'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['name'], name='workspaces_name_f0081f_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['module'], name='workspaces_module_00bdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['template_name'], name='workspaces_templat_660277_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_workspace_name_per_company'),
        ),
    ]
