# Generated by Django 5.2.13 on 2026-08-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_alter_emailsettings_language_alter_person_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Portuguese (Brazil)')], default='en', help_text="Language code for these settings (e.g., 'en', 'fr').", max_length=10, verbose_name='Language Code'),
        ),
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Portuguese (Brazil)')], default='en', help_text='Preferred language for this profile.', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='techbridges',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Portuguese (Brazil)')], default='en', help_text="Language code for these settings (e.g., 'en', 'fr').", max_length=10, verbose_name='Language Code'),
        ),
    ]
