# Generated by Django 5.2.11 on 2026-02-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactpage_form_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, help_text='Use dark color scheme for this page.', verbose_name='Enable Dark Mode'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='has_footer_with_partners',
            field=models.BooleanField(blank=True, default=False, help_text='Display partner logos in the footer section.', null=True, verbose_name='Show Footer Partners'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, help_text='Use dark color scheme for this page.', verbose_name='Enable Dark Mode'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='has_footer_with_partners',
            field=models.BooleanField(blank=True, default=False, help_text='Display partner logos in the footer section.', null=True, verbose_name='Show Footer Partners'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, help_text='Use dark color scheme for this page.', verbose_name='Enable Dark Mode'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='has_footer_with_partners',
            field=models.BooleanField(blank=True, default=False, help_text='Display partner logos in the footer section.', null=True, verbose_name='Show Footer Partners'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='enable_dark_mode',
            field=models.BooleanField(default=False, help_text='Use dark color scheme for this page.', verbose_name='Enable Dark Mode'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='has_footer_with_partners',
            field=models.BooleanField(blank=True, default=False, help_text='Display partner logos in the footer section.', null=True, verbose_name='Show Footer Partners'),
        ),
    ]
