# Generated by Django 5.2.11 on 2026-02-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_aboutpage_facts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='has_footer_with_partners',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='has_footer_with_partners',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='has_footer_with_partners',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='has_footer_with_partners',
        ),
    ]
