# Generated by Django 5.2.11 on 2026-02-22 23:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_aboutpage_facts_alter_homepage_cta'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_page_at_footer', models.BooleanField(default=False, help_text='If enabled, this page will appear as a link in the footer menu.', verbose_name='Show Page at Footer')),
                ('header_section', wagtail.fields.StreamField([('hero', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Intro Text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('subtitle', 1), ('title', 2), ('intro_text', 3)]], {'icon': 'id-card', 'label': 'Header Section'})}, verbose_name='Header Section')),
                ('cta_section', wagtail.fields.StreamField([('cta', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Title', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Subtitle', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Button Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_link', 4)]], {'icon': 'bullhorn', 'label': 'Call To Action'})}, verbose_name='Call To Action')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Short summary or introduction for this page.', verbose_name='Intro Text')),
                ('items_per_page', models.PositiveIntegerField(default=9, help_text='Pagination setting for listed items.', verbose_name='Items per Page')),
            ],
            options={
                'verbose_name': 'Events Page',
                'verbose_name_plural': 'Events Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('show_page_at_footer', models.BooleanField(default=False, help_text='If enabled, this page will appear as a link in the footer menu.', verbose_name='Show Page at Footer')),
                ('header_section', wagtail.fields.StreamField([('hero', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'max_length': 255, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'max_length': 255, 'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Intro Text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('subtitle', 1), ('title', 2), ('intro_text', 3)]], {'icon': 'id-card', 'label': 'Header Section'})}, verbose_name='Header Section')),
                ('cta_section', wagtail.fields.StreamField([('cta', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'django_grep/comp/blocks/media/simple_image.html'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Title', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'CTA Subtitle', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button Text', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Button Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('title', 1), ('subtitle', 2), ('button_text', 3), ('button_link', 4)]], {'icon': 'bullhorn', 'label': 'Call To Action'})}, verbose_name='Call To Action')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Short summary or introduction for this page.', verbose_name='Intro Text')),
                ('items_per_page', models.PositiveIntegerField(default=9, help_text='Pagination setting for listed items.', verbose_name='Items per Page')),
            ],
            options={
                'verbose_name': 'Services Page',
                'verbose_name_plural': 'Services Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
