# Generated by Django 5.2.16 on 2026-08-12 22:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('first_touch', 'First Touch'), ('last_touch', 'Last Touch'), ('linear', 'Linear'), ('time_decay', 'Time Decay'), ('position_based', 'Position Based')], default='linear', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribution_models', to='core.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributionTouchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='post', max_length=50)),
                ('occurred_at', models.DateTimeField()),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='marketing.campaign')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='crm.deal')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='marketing.post')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='core.workspace')),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['workspace', 'deal'], name='attribution_workspa_d651ae_idx'), models.Index(fields=['workspace', 'campaign'], name='attribution_workspa_3b08ac_idx')],
            },
        ),
    ]
