# Generated by Django 6.1 on 2026-08-18 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0001_initial'),
        ('core', '0013_alter_auditlog_options_alter_emailaccount_options_and_more'),
        ('crm', '0004_alter_activity_options_alter_company_options_and_more'),
        ('marketing', '0003_alter_campaign_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributionmodel',
            options={'ordering': ['name'], 'verbose_name': 'attribution model', 'verbose_name_plural': 'attribution models'},
        ),
        migrations.AlterModelOptions(
            name='attributiontouchpoint',
            options={'ordering': ['occurred_at'], 'verbose_name': 'attribution touchpoint', 'verbose_name_plural': 'attribution touchpoints'},
        ),
        migrations.AlterField(
            model_name='attributionmodel',
            name='config',
            field=models.JSONField(default=dict, verbose_name='config'),
        ),
        migrations.AlterField(
            model_name='attributionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='attributionmodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='attributionmodel',
            name='model_type',
            field=models.CharField(choices=[('first_touch', 'First Touch'), ('last_touch', 'Last Touch'), ('linear', 'Linear'), ('time_decay', 'Time Decay'), ('position_based', 'Position Based')], default='linear', max_length=20, verbose_name='model type'),
        ),
        migrations.AlterField(
            model_name='attributionmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='attributionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='marketing.campaign', verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='crm.deal', verbose_name='deal'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='occurred_at',
            field=models.DateTimeField(verbose_name='occurred at'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touchpoints', to='marketing.post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='source',
            field=models.CharField(default='post', max_length=50, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='attributiontouchpoint',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='core.workspace', verbose_name='workspace'),
        ),
    ]
