#!/usr/bin/env node
/**
 * scripts/check-i18n.cjs
 *
 * Audits src/i18n/{en,fr,ar}.json against one another and emits a
 * human-readable Markdown gap report at docs/i18n-gaps.md.
 *
 * Usage:
 *   node scripts/check-i18n.cjs
 *   node scripts/check-i18n.cjs --check   # exit non-zero if any gaps exist (CI-friendly)
 *
 * The runtime already falls back to English via `fallbackLng: 'en'` in
 * src/i18n/index.ts, so missing translations degrade gracefully. This script
 * exists purely to give translators / maintainers a writable backlog.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '../..');
const LOCALES_DIR = path.join(ROOT, 'src', 'i18n');
const REPORT_PATH = path.join(ROOT, 'docs', 'i18n-gaps.md');
const LOCALES = ['en', 'fr', 'ar'];
const REFERENCE = 'en';

/** Recursively flatten a nested object to a sorted array of dot-paths. */
function flatten(obj, prefix = []) {
  return Object.entries(obj || {}).flatMap(([key, value]) => {
    const path = [...prefix, key];
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return flatten(value, path);
    }
    return [path.join('.')];
  });
}

function readLocale(name) {
  const file = path.join(LOCALES_DIR, `${name}.json`);
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (err) {
    console.error(`✗ Failed to read ${file}: ${err.message}`);
    process.exit(1);
  }
}

function buildReport() {
  const ref = flatten(readLocale(REFERENCE));
  const refSet = new Set(ref);
  const data = { [REFERENCE]: ref };

  for (const locale of LOCALES) {
    if (locale === REFERENCE) continue;
    const flat = flatten(readLocale(locale));
    data[locale] = {
      keys: flat,
      missing: ref.filter((k) => !flat.includes(k)),
      extra: flat.filter((k) => !refSet.has(k)),
    };
  }

  const totalMissing =
    (data.fr?.missing.length ?? 0) + (data.ar?.missing.length ?? 0);

  let out = '';
  out += '# Internationalization (i18n) Gap Report\n\n';
  out +=
    'Audit of `src/i18n/{en,fr,ar}.json` — auto-generated by `node scripts/check-i18n.cjs`.\n\n';
  out +=
    'Reference language is **English** (`en`). The app falls back to English at runtime via `fallbackLng: "en"` in [src/i18n/index.ts](../src/i18n/index.ts), so missing translations degrade gracefully — only this report tracks them as a backlog.\n\n';
  out += '## Summary\n\n';
  out += '| Locale | Keys | Missing (vs en) | Extra |\n';
  out += '|--------|------|-----------------|-------|\n';
  for (const locale of LOCALES) {
    if (locale === REFERENCE) {
      out += `| \`${locale}\` | ${data[locale].length} | _(reference)_ | _(reference)_ |\n`;
    } else {
      const { keys, missing, extra } = data[locale];
      out += `| \`${locale}\` | ${keys.length} | ${missing.length} | ${extra.length} |\n`;
    }
  }
  out += '\n';

  for (const locale of LOCALES) {
    if (locale === REFERENCE) continue;
    const { keys, missing, extra } = data[locale];
    out += `## \`${locale}\` — ${keys.length} keys\n\n`;

    if (missing.length === 0) {
      out += `✅ All English keys are translated.\n\n`;
    } else {
      out += `### Missing keys (${missing.length})\n\n`;
      out += 'Translate these in `src/i18n/' +
        locale +
        '.json` so the UI no longer relies on the English fallback.\n\n';
      out += '| Key |\n|-----|\n';
      for (const k of missing) out += `| \`${k}\` |\n`;
      out += '\n';
    }

    if (extra.length > 0) {
      out += `> ⚠️ Extra keys in \`${locale}\` not present in \`en\` (${extra.length}): `;
      out += extra.map((k) => '`' + k + '`').join(', ');
      out += '\n\n';
    }
  }

  out += '## How to translate\n\n';
  out +=
    '1. Pick a key from the missing list above.\n' +
    '2. Add it to `src/i18n/' +
    'fr' +
    '.json` or `src/i18n/' +
    'ar' +
    '.json` under the same namespace.\n' +
    '3. Re-run `node scripts/check-i18n.cjs` to confirm the gap shrank.\n\n';
  out += '### French conventions\n\n';
  out +=
    '- Keep technical terms (`SKU`, `CRM`, `POS`) in Latin script.\n' +
    '- UI strings use **Title Case** for headings, sentence case otherwise.\n' +
    '- Placeholders follow the form `Entrez le nom…`.\n\n';
  out += '### Arabic conventions\n\n';
  out +=
    '- All strings are right-to-left; mirror layout expectations in JSX (`dir="rtl"`, see [LanguageToggle.tsx](../src/components/LanguageToggle.tsx)).\n' +
    '- Numerals: use **Arabic-Indic digits** (\u0660\u2013\u0669) in user-facing counters, keep **Latin digits** in code/IDs.\n' +
    '- Plurals: prefer singular form with explicit noun when possible.\n\n';

  return { report: out, totalMissing };
}

function main() {
  const checkOnly = process.argv.includes('--check');
  const { report, totalMissing } = buildReport();

  fs.mkdirSync(path.dirname(REPORT_PATH), { recursive: true });
  fs.writeFileSync(REPORT_PATH, report);

  console.log(`\u2713 Wrote ${path.relative(ROOT, REPORT_PATH)}`);
  console.log(`  Reference: en (${flatten(readLocale(REFERENCE)).length} keys)`);
  for (const locale of LOCALES) {
    if (locale === REFERENCE) continue;
    const { keys, missing, extra } = {
      keys: flatten(readLocale(locale)),
      missing: flatten(readLocale(REFERENCE)).filter(
        (k) => !flatten(readLocale(locale)).includes(k),
      ),
      extra: flatten(readLocale(locale)).filter(
        (k) => !flatten(readLocale(REFERENCE)).includes(k),
      ),
    };
    console.log(
      `  ${locale}: ${keys.length} keys, ${missing.length} missing, ${extra.length} extra`,
    );
  }

  if (checkOnly && totalMissing > 0) {
    console.error(`\u2717 ${totalMissing} missing translations across locales`);
    process.exit(1);
  }
}

main();
