# Generated by Django 5.2.15 on 2026-07-24 20:20

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact submission',
                'verbose_name_plural': 'contact submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'course category',
                'verbose_name_plural': 'course categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('icon_class', models.CharField(blank=True, default='', max_length=100)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'dashboard counter',
                'verbose_name_plural': 'dashboard counters',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DynamicAboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_description', models.TextField(blank=True, default='', help_text='Meta description for search engines.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body', wagtail.fields.StreamField([('hero', 8), ('stats', 14), ('section_header', 18), ('rich_section', 23), ('cta', 25), ('faq_groups', 32), ('contact_methods', 38), ('form', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': '', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 100}), 4: ('wagtail.blocks.CharBlock', (), {'default': '/', 'max_length': 300}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('link', 'Link')]}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'default': list}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('image', 2), ('ctas', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Students', 'max_length': 100}), 10: ('wagtail.blocks.CharBlock', (), {'default': '0', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': list}), 14: ('wagtail.blocks.StructBlock', [[('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200}), 17: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('key', 15), ('heading', 16), ('intro', 1), ('cta', 17)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {'default': '', 'required': False}), 20: ('wagtail.blocks.TextBlock', (), {'default': ''}), 21: ('wagtail.blocks.StructBlock', [[('heading', 16), ('text', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'default': list}), 23: ('wagtail.blocks.StructBlock', [[('heading', 16), ('html', 19), ('items', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Get Started', 'max_length': 200}), 25: ('wagtail.blocks.StructBlock', [[('heading', 24), ('intro', 1), ('ctas', 7)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'General', 'max_length': 200}), 27: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300}), 28: ('wagtail.blocks.StructBlock', [[('question', 27), ('answer', 20)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'default': list}), 30: ('wagtail.blocks.StructBlock', [[('title', 26), ('items', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'default': list}), 32: ('wagtail.blocks.StructBlock', [[('groups', 31)]], {}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('hours', 'Hours')]}), 34: ('wagtail.blocks.CharBlock', (), {'default': 'Email', 'max_length': 100}), 35: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300, 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('type', 33), ('label', 34), ('value', 27), ('href', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'default': list}), 38: ('wagtail.blocks.StructBlock', [[('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Send us a message', 'max_length': 200}), 40: ('wagtail.blocks.StructBlock', [[('heading', 39)]], {})})),
            ],
            options={
                'verbose_name': 'about page',
                'verbose_name_plural': 'about pages',
                'db_table': 'content_dynamic_aboutpage',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DynamicContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_description', models.TextField(blank=True, default='', help_text='Meta description for search engines.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body', wagtail.fields.StreamField([('hero', 8), ('stats', 14), ('section_header', 18), ('rich_section', 23), ('cta', 25), ('faq_groups', 32), ('contact_methods', 38), ('form', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': '', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 100}), 4: ('wagtail.blocks.CharBlock', (), {'default': '/', 'max_length': 300}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('link', 'Link')]}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'default': list}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('image', 2), ('ctas', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Students', 'max_length': 100}), 10: ('wagtail.blocks.CharBlock', (), {'default': '0', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': list}), 14: ('wagtail.blocks.StructBlock', [[('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200}), 17: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('key', 15), ('heading', 16), ('intro', 1), ('cta', 17)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {'default': '', 'required': False}), 20: ('wagtail.blocks.TextBlock', (), {'default': ''}), 21: ('wagtail.blocks.StructBlock', [[('heading', 16), ('text', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'default': list}), 23: ('wagtail.blocks.StructBlock', [[('heading', 16), ('html', 19), ('items', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Get Started', 'max_length': 200}), 25: ('wagtail.blocks.StructBlock', [[('heading', 24), ('intro', 1), ('ctas', 7)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'General', 'max_length': 200}), 27: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300}), 28: ('wagtail.blocks.StructBlock', [[('question', 27), ('answer', 20)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'default': list}), 30: ('wagtail.blocks.StructBlock', [[('title', 26), ('items', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'default': list}), 32: ('wagtail.blocks.StructBlock', [[('groups', 31)]], {}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('hours', 'Hours')]}), 34: ('wagtail.blocks.CharBlock', (), {'default': 'Email', 'max_length': 100}), 35: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300, 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('type', 33), ('label', 34), ('value', 27), ('href', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'default': list}), 38: ('wagtail.blocks.StructBlock', [[('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Send us a message', 'max_length': 200}), 40: ('wagtail.blocks.StructBlock', [[('heading', 39)]], {})})),
            ],
            options={
                'verbose_name': 'contact page',
                'verbose_name_plural': 'contact pages',
                'db_table': 'content_dynamic_contactpage',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DynamicFaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_description', models.TextField(blank=True, default='', help_text='Meta description for search engines.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body', wagtail.fields.StreamField([('hero', 8), ('stats', 14), ('section_header', 18), ('rich_section', 23), ('cta', 25), ('faq_groups', 32), ('contact_methods', 38), ('form', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': '', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 100}), 4: ('wagtail.blocks.CharBlock', (), {'default': '/', 'max_length': 300}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('link', 'Link')]}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'default': list}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('image', 2), ('ctas', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Students', 'max_length': 100}), 10: ('wagtail.blocks.CharBlock', (), {'default': '0', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': list}), 14: ('wagtail.blocks.StructBlock', [[('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200}), 17: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('key', 15), ('heading', 16), ('intro', 1), ('cta', 17)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {'default': '', 'required': False}), 20: ('wagtail.blocks.TextBlock', (), {'default': ''}), 21: ('wagtail.blocks.StructBlock', [[('heading', 16), ('text', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'default': list}), 23: ('wagtail.blocks.StructBlock', [[('heading', 16), ('html', 19), ('items', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Get Started', 'max_length': 200}), 25: ('wagtail.blocks.StructBlock', [[('heading', 24), ('intro', 1), ('ctas', 7)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'General', 'max_length': 200}), 27: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300}), 28: ('wagtail.blocks.StructBlock', [[('question', 27), ('answer', 20)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'default': list}), 30: ('wagtail.blocks.StructBlock', [[('title', 26), ('items', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'default': list}), 32: ('wagtail.blocks.StructBlock', [[('groups', 31)]], {}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('hours', 'Hours')]}), 34: ('wagtail.blocks.CharBlock', (), {'default': 'Email', 'max_length': 100}), 35: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300, 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('type', 33), ('label', 34), ('value', 27), ('href', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'default': list}), 38: ('wagtail.blocks.StructBlock', [[('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Send us a message', 'max_length': 200}), 40: ('wagtail.blocks.StructBlock', [[('heading', 39)]], {})})),
            ],
            options={
                'verbose_name': 'FAQ page',
                'verbose_name_plural': 'FAQ pages',
                'db_table': 'content_dynamic_faqpage',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DynamicHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_description', models.TextField(blank=True, default='', help_text='Meta description for search engines.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body', wagtail.fields.StreamField([('hero', 8), ('stats', 14), ('section_header', 18), ('rich_section', 23), ('cta', 25), ('faq_groups', 32), ('contact_methods', 38), ('form', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': '', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 100}), 4: ('wagtail.blocks.CharBlock', (), {'default': '/', 'max_length': 300}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('link', 'Link')]}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'default': list}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('image', 2), ('ctas', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Students', 'max_length': 100}), 10: ('wagtail.blocks.CharBlock', (), {'default': '0', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': list}), 14: ('wagtail.blocks.StructBlock', [[('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200}), 17: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('key', 15), ('heading', 16), ('intro', 1), ('cta', 17)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {'default': '', 'required': False}), 20: ('wagtail.blocks.TextBlock', (), {'default': ''}), 21: ('wagtail.blocks.StructBlock', [[('heading', 16), ('text', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'default': list}), 23: ('wagtail.blocks.StructBlock', [[('heading', 16), ('html', 19), ('items', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Get Started', 'max_length': 200}), 25: ('wagtail.blocks.StructBlock', [[('heading', 24), ('intro', 1), ('ctas', 7)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'General', 'max_length': 200}), 27: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300}), 28: ('wagtail.blocks.StructBlock', [[('question', 27), ('answer', 20)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'default': list}), 30: ('wagtail.blocks.StructBlock', [[('title', 26), ('items', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'default': list}), 32: ('wagtail.blocks.StructBlock', [[('groups', 31)]], {}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('hours', 'Hours')]}), 34: ('wagtail.blocks.CharBlock', (), {'default': 'Email', 'max_length': 100}), 35: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300, 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('type', 33), ('label', 34), ('value', 27), ('href', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'default': list}), 38: ('wagtail.blocks.StructBlock', [[('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Send us a message', 'max_length': 200}), 40: ('wagtail.blocks.StructBlock', [[('heading', 39)]], {})})),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home pages',
                'db_table': 'content_dynamic_homepage',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DynamicPrivacyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('seo_description', models.TextField(blank=True, default='', help_text='Meta description for search engines.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body', wagtail.fields.StreamField([('hero', 8), ('stats', 14), ('section_header', 18), ('rich_section', 23), ('cta', 25), ('faq_groups', 32), ('contact_methods', 38), ('form', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Welcome', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'default': '', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 100}), 4: ('wagtail.blocks.CharBlock', (), {'default': '/', 'max_length': 300}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('link', 'Link')]}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'default': list}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('intro', 1), ('image', 2), ('ctas', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Students', 'max_length': 100}), 10: ('wagtail.blocks.CharBlock', (), {'default': '0', 'max_length': 50}), 11: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('value', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'default': list}), 14: ('wagtail.blocks.StructBlock', [[('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 100}), 16: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 200}), 17: ('wagtail.blocks.StructBlock', [[('label', 3), ('href', 4), ('variant', 5)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('key', 15), ('heading', 16), ('intro', 1), ('cta', 17)]], {}), 19: ('wagtail.blocks.RichTextBlock', (), {'default': '', 'required': False}), 20: ('wagtail.blocks.TextBlock', (), {'default': ''}), 21: ('wagtail.blocks.StructBlock', [[('heading', 16), ('text', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'default': list}), 23: ('wagtail.blocks.StructBlock', [[('heading', 16), ('html', 19), ('items', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Get Started', 'max_length': 200}), 25: ('wagtail.blocks.StructBlock', [[('heading', 24), ('intro', 1), ('ctas', 7)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'General', 'max_length': 200}), 27: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300}), 28: ('wagtail.blocks.StructBlock', [[('question', 27), ('answer', 20)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'default': list}), 30: ('wagtail.blocks.StructBlock', [[('title', 26), ('items', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'default': list}), 32: ('wagtail.blocks.StructBlock', [[('groups', 31)]], {}), 33: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('email', 'Email'), ('phone', 'Phone'), ('address', 'Address'), ('hours', 'Hours')]}), 34: ('wagtail.blocks.CharBlock', (), {'default': 'Email', 'max_length': 100}), 35: ('wagtail.blocks.CharBlock', (), {'default': '', 'max_length': 300, 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('type', 33), ('label', 34), ('value', 27), ('href', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {'default': list}), 38: ('wagtail.blocks.StructBlock', [[('items', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Send us a message', 'max_length': 200}), 40: ('wagtail.blocks.StructBlock', [[('heading', 39)]], {})})),
            ],
            options={
                'verbose_name': 'privacy page',
                'verbose_name_plural': 'privacy pages',
                'db_table': 'content_dynamic_privacypage',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='home_1', help_text='Which home page version this FAQ belongs to', max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['page', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Useful Links', 'Our Company'", max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'publication category',
                'verbose_name_plural': 'publication categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('github', 'GitHub'), ('discord', 'Discord'), ('other', 'Other')], default='facebook', max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text="Display name (e.g., 'Follow us on Facebook')", max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('icon_svg', models.CharField(blank=True, default='', help_text="Path to SVG icon (e.g., '/assets/img/icons/facebook.svg')", max_length=200)),
                ('icon_class', models.CharField(blank=True, default='', help_text="CSS class for icon font (e.g., 'fab fa-facebook')", max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'social link',
                'verbose_name_plural': 'social links',
                'ordering': ['sort_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'ordering': ['-published_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True, default='')),
                ('short_description', models.CharField(blank=True, default='', max_length=255)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='beginner', max_length=20)),
                ('language', models.CharField(default='English', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('instructor', models.CharField(blank=True, default='', max_length=200)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='content.coursecategory')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['event_date'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='home_1', help_text='Which home page version this feature belongs to', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_class', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ['page', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.footerlinkgroup')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('course_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'instructor',
                'verbose_name_plural': 'instructors',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, default='#', max_length=500)),
                ('menu_class', models.CharField(blank=True, default='', help_text='CSS class for mega-menu container', max_length=100)),
                ('badge', models.CharField(blank=True, default='', help_text="Badge text like 'Hot' or 'New'", max_length=100)),
                ('badge_class', models.CharField(blank=True, default='', help_text="Badge color variant like 'tg-badge'", max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item for nested menus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menuitem')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('abstract', wagtail.fields.RichTextField(blank=True, default='')),
                ('authors', models.CharField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('external_url', models.URLField(blank=True, default='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='content.publicationcategory')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ['-published_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('coming_soon', 'Coming Soon')], default='in_stock', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'shop product',
                'verbose_name_plural': 'shop products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TharaaEdu', help_text='Site name displayed in footer/titles', max_length=200)),
                ('site_tagline', models.CharField(blank=True, default='', help_text='Short tagline', max_length=300)),
                ('footer_description', models.TextField(blank=True, default='', help_text='Company description in footer')),
                ('footer_address', models.CharField(blank=True, default='', help_text='Physical address', max_length=300)),
                ('footer_phone', models.CharField(blank=True, default='', help_text='Contact phone number', max_length=50)),
                ('footer_email', models.EmailField(blank=True, default='', help_text='Contact email', max_length=254)),
                ('footer_copyright', models.CharField(default='© 2025 TharaaEdu. All rights reserved.', help_text='Copyright text in footer bottom', max_length=200)),
                ('google_play_url', models.URLField(blank=True, default='', help_text='Google Play store link')),
                ('apple_store_url', models.URLField(blank=True, default='', help_text='Apple App Store link')),
                ('privacy_policy_url', models.CharField(blank=True, default='/contact', help_text='Link to privacy policy page', max_length=300)),
                ('terms_of_use_url', models.CharField(blank=True, default='/contact', help_text='Link to terms of use page', max_length=300)),
                ('logo', models.ForeignKey(blank=True, help_text='Site logo for footer/header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.AddField(
            model_name='footerlinkgroup',
            name='setting',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_link_groups', to='content.sitesettings'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='{"twitter": "...", "linkedin": "...", "github": "..."}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'team member',
                'verbose_name_plural': 'team members',
                'ordering': ['sort_order', 'name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('quote', models.TextField(blank=True, default='')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 chars of raw token for display', max_length=8)),
                ('token_type', models.CharField(choices=[('access', 'Access'), ('api', 'API'), ('sync', 'Sync'), ('refresh', 'Refresh')], db_index=True, default='access', max_length=10)),
                ('category', models.CharField(blank=True, db_index=True, default='', help_text='Freeform grouping label', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Optional serialized snapshot for offline sync replay')),
                ('is_sync', models.BooleanField(db_index=True, default=False, help_text='Whether this data has been synced')),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_tokens', to='content.token')),
            ],
            options={
                'verbose_name': 'data token',
                'verbose_name_plural': 'data tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['token_hash'], name='content_tok_token_h_3b04f2_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['user', 'token_type', 'created_at'], name='content_tok_user_id_2b4441_idx'),
        ),
        migrations.AddIndex(
            model_name='datatoken',
            index=models.Index(fields=['token', 'is_sync'], name='content_dat_token_i_6814e7_idx'),
        ),
        migrations.AddIndex(
            model_name='datatoken',
            index=models.Index(fields=['content_type', 'object_id'], name='content_dat_content_945494_idx'),
        ),
    ]
