# Generated by Django 6.1 on 2026-08-18 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_alter_auditlog_options_alter_emailaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('price_cents', models.PositiveIntegerField(default=0, verbose_name='price (cents)')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20, verbose_name='period')),
                ('seat_limit', models.PositiveIntegerField(default=1, verbose_name='seat limit')),
                ('feature_flags', models.JSONField(blank=True, default=dict, verbose_name='feature flags')),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe price id')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['price_cents', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='trial', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to='core.workspace')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='billing.plan')),
            ],
            options={
                'verbose_name': 'billing account',
                'verbose_name_plural': 'billing accounts',
                'ordering': ['workspace'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_seats', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.workspace')),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
                'ordering': ['workspace', 'user'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_seat_workspace_user')],
            },
        ),
    ]
