# Generated by Django 5.2.16 on 2026-07-26 17:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('layout', models.CharField(choices=[('default', 'Default (Header + Content + Footer)'), ('full_width', 'Full Width (No sidebar, edge-to-edge)'), ('sidebar', 'Sidebar (Content + Sidebar)'), ('blank', 'Blank (Content only, no chrome)')], default='default', help_text='Which fusion layout template to render this page with.', max_length=20)),
                ('fusion_render_first', models.BooleanField(default=False, help_text='When enabled, Django renders the full HTML server-side before Next.js hydration. The frontend FusionProxy detects this and injects the HTML directly instead of fetching JSON.')),
                ('fragment_name', models.CharField(blank=True, default='', help_text="Dotted fragment identifier (e.g. 'pages.about'). Auto-derived from the slug if left blank.", max_length=255)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Include this page in the main navigation menu.')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Optional inline CSS applied only to this page.')),
                ('hero_heading', models.CharField(blank=True, default='Welcome to Fusion', help_text='Main hero heading displayed on the home page.', max_length=255)),
                ('hero_subheading', models.TextField(blank=True, default='A modern platform powered by django-fusion and django-bolt.', help_text='Supporting text below the hero heading.')),
            ],
            options={
                'verbose_name': 'Fusion Home Page',
                'verbose_name_plural': 'Fusion Home Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FusionContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('layout', models.CharField(choices=[('default', 'Default (Header + Content + Footer)'), ('full_width', 'Full Width (No sidebar, edge-to-edge)'), ('sidebar', 'Sidebar (Content + Sidebar)'), ('blank', 'Blank (Content only, no chrome)')], default='default', help_text='Which fusion layout template to render this page with.', max_length=20)),
                ('fusion_render_first', models.BooleanField(default=False, help_text='When enabled, Django renders the full HTML server-side before Next.js hydration. The frontend FusionProxy detects this and injects the HTML directly instead of fetching JSON.')),
                ('fragment_name', models.CharField(blank=True, default='', help_text="Dotted fragment identifier (e.g. 'pages.about'). Auto-derived from the slug if left blank.", max_length=255)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Include this page in the main navigation menu.')),
                ('custom_css', models.TextField(blank=True, default='', help_text='Optional inline CSS applied only to this page.')),
                ('body', wagtail.fields.RichTextField(blank=True, default='', help_text='Main page content.')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Optional featured image for the page header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Fusion Content Page',
                'verbose_name_plural': 'Fusion Content Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
