# Generated by Django 5.2.16 on 2026-08-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_pagetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetranslation',
            name='body',
            field=models.TextField(blank=True, help_text='Translated rich-text HTML. Empty uses the canonical body.'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Partial API content overrides, for example hero, cta, faq, or features.'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='search_description',
            field=models.TextField(blank=True, help_text='Translated SEO description.'),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='title',
            field=models.CharField(blank=True, help_text='Translated page title. Empty uses the canonical page title.', max_length=255),
        ),
    ]
