# Generated by Django 5.2.16 on 2026-08-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_pagetranslation_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='BCP-47 language tag, for example en, ar, sv.', max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='English display name, for example English, Arabic.', max_length=60, verbose_name='Name')),
                ('native_name', models.CharField(blank=True, default='', help_text='Name in the language itself, for example Svenska, العربية.', max_length=60, verbose_name='Native name')),
                ('direction', models.CharField(choices=[('ltr', 'Left to right'), ('rtl', 'Right to left')], default='ltr', max_length=3, verbose_name='Direction')),
                ('flag', models.CharField(blank=True, default='', help_text='Emoji flag shown in the switcher, for example 🇸🇪.', max_length=8, verbose_name='Flag emoji')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive languages are hidden from the switcher.', verbose_name='Active')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first in the switcher.', verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'site language',
                'verbose_name_plural': 'site languages',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
