# Generated by Django 5.2.16 on 2026-08-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workspace_external_ref_workspace_source'),
        ('crm', '0002_custom_field_definitions'),
        ('finance', '0002_rename_indexes'),
        ('marketing', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueevent',
            name='external_ref',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='revenueevent',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_events', to='crm.deal'),
        ),
        migrations.AlterField(
            model_name='revenueevent',
            name='kind',
            field=models.CharField(choices=[('deal_won', 'Deal won'), ('expansion', 'Expansion'), ('renewal', 'Renewal'), ('refund', 'Refund'), ('pos_sale', 'POS sale'), ('pos_refund', 'POS refund')], default='deal_won', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='revenueevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('workspace', 'external_ref'), name='uniq_revenue_event_external_ref'),
        ),
    ]
