# Generated by Django 5.2.16 on 2026-08-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_revenueevent_external_ref_alter_revenueevent_deal_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issued_on", "-created_at"],
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-paid_on", "-created_at"],
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
            },
        ),
        migrations.AlterModelOptions(
            name="revenueevent",
            options={
                "ordering": ["-recognized_on", "-created_at"],
                "verbose_name": "revenue event",
                "verbose_name_plural": "revenue events",
            },
        ),
    ]
