# Generated by Django 5.2.13 on 2026-07-04 01:27

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='date', unique=True)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('customer_name', models.CharField(max_length=80, verbose_name='Customer Name')),
                ('contact_number', models.CharField(max_length=30, verbose_name='Contact Number')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Item')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quantity')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shipping')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Total')),
                ('grand_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Grand Total')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm_inventory.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-date'],
            },
        ),
    ]
