services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - '1025:1025'
    volumes:
      - 'mailpit-data:/data'
      - './htpasswd:/data/htpasswd'
    environment:
      SERVICE_URL_MAILPIT_8025: 'http://mailpit.${SERVER_IP:-72.61.82.167}.sslip.io:8025'
      MP_MAX_MESSAGES: '5000'
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: '1'
      MP_SMTP_AUTH_ALLOW_INSECURE: '1'
      MP_UI_AUTH_FILE: /data/htpasswd
      SERVICE_NAME_MAILPIT: mailpit
    healthcheck:
      test: [CMD, /mailpit, readyz]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.1.2
      - coolify.serviceId=5
      - coolify.type=service
      - coolify.resourceName=mailpit
      - coolify.projectName=websites
      - coolify.serviceName=mailpit
      - coolify.environmentName=utilities
      - traefik.enable=true
      - traefik.http.routers.mailpit.entryPoints=http
      - traefik.http.routers.mailpit.rule=Host(`mailpit.${SERVER_IP:-72.61.82.167}.sslip.io`)
      - traefik.http.routers.mailpit.service=mailpit
      - traefik.http.services.mailpit.loadbalancer.server.port=8025
    networks:
      - coolify
    env_file:
      - .env

volumes:
  mailpit-data:
    name: mailpit-data

networks:
  coolify:
    name: coolify
    external: true
