# Generated by Django 6.0.7 on 2026-07-22 15:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the integration (e.g. Twilio Messaging).', max_length=100, verbose_name='Integration Name')),
                ('external_id', models.CharField(blank=True, help_text='Unique identifier from the external system (if available).', max_length=255, verbose_name='External ID')),
                ('integration_type', models.CharField(choices=[('twilio', 'Twilio (Messaging API)'), ('stripe', 'Stripe (Payment Processor)'), ('paypal', 'PayPal (Payment Gateway)'), ('google', 'Google (OAuth / APIs)'), ('aws', 'Amazon Web Services (S3, SNS, etc.)'), ('slack', 'Slack (Messaging / Webhooks)'), ('zoho', 'Zoho (CRM / Accounting)'), ('hubspot', 'HubSpot (CRM / Marketing)'), ('quickbooks', 'QuickBooks (Accounting)'), ('custom', 'Custom Integration')], default='custom', help_text='Select which platform or service this integration connects to.', max_length=20, verbose_name='Integration Type')),
                ('endpoint_type', models.CharField(choices=[('sms', 'Messaging / SMS'), ('voice', 'Voice / Calls'), ('whatsapp', 'WhatsApp Messaging'), ('video', 'Video API'), ('payments', 'Payments / Charges'), ('invoices', 'Invoices / Billing'), ('customers', 'Customer Profiles'), ('subscriptions', 'Subscriptions / Plans'), ('auth', 'Authentication / OAuth'), ('webhook', 'Webhook Endpoint'), ('sync', 'Data Synchronization'), ('reports', 'Analytics / Reports'), ('callback', 'Callback or Redirect'), ('health', 'Health Check / Ping'), ('custom', 'Custom Endpoint')], default='custom', help_text='Type of endpoint or API section this configuration handles.', max_length=20, verbose_name='Endpoint Type')),
                ('api_endpoint', models.URLField(blank=True, help_text='Base URL for the endpoint, e.g., https://api.twilio.com/v1/messages', verbose_name='API Endpoint')),
                ('api_key', models.CharField(blank=True, help_text='API key or authentication token used for access.', max_length=255, verbose_name='API Key / Token')),
                ('metadata', models.JSONField(blank=True, help_text='Additional configuration or credentials as JSON.', null=True, verbose_name='Metadata')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this integration is currently enabled.', verbose_name='Is Active')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When the last synchronization or update occurred.', null=True, verbose_name='Last Sync At')),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending'), ('never', 'Never Synced')], default='never', help_text='The current synchronization status.', max_length=20, verbose_name='Sync Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['-updated_at', 'name'],
                'indexes': [models.Index(fields=['integration_type', 'is_active'], name='CI_integrat_integra_d2ac79_idx'), models.Index(fields=['name'], name='CI_integrat_name_c381ce_idx'), models.Index(fields=['sync_status'], name='CI_integrat_sync_st_2783a9_idx')],
                'unique_together': {('name', 'integration_type', 'endpoint_type')},
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=255, unique=True, verbose_name='Call SID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='initiated', help_text='Call status such as initiated, in-progress, or completed.', max_length=50, verbose_name='Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(blank=True, help_text='Reference to the integration used (e.g., Twilio Voice API).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='CI.integration', verbose_name='Integration')),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS Message'), ('email', 'Email Notification'), ('voice', 'Voice Call'), ('push', 'Push Notification')], default='sms', max_length=20)),
                ('message', models.TextField(verbose_name='Message Content')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', help_text='Status of the notification: pending, sent, failed.', max_length=20, verbose_name='Status')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(blank=True, help_text='The integration used to send this notification (e.g., Twilio, SendGrid).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='CI.integration', verbose_name='Integration')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique human-readable sync-token (primary lookup key).', max_length=255, unique=True)),
                ('node_id', models.CharField(db_index=True, help_text='Node/device identifier that owns this row.', max_length=100)),
                ('object_id', models.CharField(help_text='Primary key of the tagged row (supports int, UUID, slug).', max_length=255)),
                ('sync_order', models.IntegerField(db_index=True, default=0, help_text='Order within a sync batch. Lower = synced first.')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current sync state of this row.', max_length=20)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times this row has been retried.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Last error message if sync failed.')),
                ('synced_at', models.DateTimeField(blank=True, help_text='When the row was confirmed synced upstream.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra data (e.g. invoice total, customer name).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Model type of the tagged row.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent token for tree-structured sync (invoice → items).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='CI.datatoken')),
            ],
            options={
                'verbose_name': 'Data Token',
                'verbose_name_plural': 'Data Tokens',
                'ordering': ['sync_order', 'created_at'],
                'indexes': [models.Index(fields=['node_id', 'sync_status', 'sync_order'], name='CI_datatoke_node_id_21a169_idx'), models.Index(fields=['content_type', 'object_id'], name='CI_datatoke_content_c04185_idx'), models.Index(fields=['sync_status', 'created_at'], name='CI_datatoke_sync_st_bf8a7e_idx')],
            },
        ),
    ]
