# Generated by Django 6.0.7 on 2026-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CI', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatoken',
            name='app_type',
            field=models.CharField(choices=[('pos-solo', 'POS Solo'), ('pos-full', 'POS Full'), ('pos-mini', 'POS Mini'), ('cloud', 'Cloud Server')], db_index=True, default='pos-solo', help_text='Application type flag for DataToken sync scoping.', max_length=20),
        ),
        migrations.AlterField(
            model_name='datatoken',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current sync state of this row/token.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='datatoken',
            index=models.Index(fields=['app_type', 'sync_status'], name='CI_datatoke_app_typ_2d9b2c_idx'),
        ),
    ]
