# Generated by Django 5.2.16 on 2026-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='first_published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='last_published_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last published at'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='live',
            field=models.BooleanField(default=True, editable=False, verbose_name='live'),
        ),
    ]
