# Generated by Django 5.2.16 (manual — local makemigrations blocked by a
# pre-existing shared/django_fusion migration-history inconsistency on the dev
# database; deployed stacks apply migrations in dependency order).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_course_image_alter_review_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], max_length=10, verbose_name='Language')),
                ('title', models.CharField(blank=True, help_text='Translated course title. Empty uses the canonical title.', max_length=200)),
                ('short_description', models.TextField(blank=True, help_text='Translated catalog short description.')),
                ('description', models.TextField(blank=True, help_text='Translated rich-text HTML description. Empty uses the canonical body.')),
                ('objectives', models.TextField(blank=True, help_text='Translated learning objectives — one per line.')),
                ('requirements', models.TextField(blank=True, help_text='Translated prerequisites — one per line.')),
                ('target_audience', models.TextField(blank=True, help_text='Translated target audience — one per line.')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Partial module/lesson overrides keyed by order.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course translation',
                'verbose_name_plural': 'Course translations',
                'ordering': ['course_id', 'language'],
            },
        ),
        migrations.AddConstraint(
            model_name='coursetranslation',
            constraint=models.UniqueConstraint(fields=('course', 'language'), name='unique_learning_course_translation'),
        ),
    ]
