# Generated by Django 5.2.16 on 2026-08-22 17:46

import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], max_length=20, unique=True, verbose_name='slug')),
                ('max_courses', models.PositiveSmallIntegerField(default=5, help_text='Maximum published courses (0 = unlimited).', verbose_name='max courses')),
                ('max_instructors', models.PositiveSmallIntegerField(default=1, help_text='Maximum instructor accounts (0 = unlimited).', verbose_name='max instructors')),
                ('max_students', models.PositiveSmallIntegerField(default=50, help_text='Maximum enrolled students (0 = unlimited).', verbose_name='max students')),
                ('custom_domain', models.BooleanField(default=False, help_text='Can the center use its own domain?', verbose_name='custom domain')),
                ('custom_branding', models.BooleanField(default=False, help_text='Can the center customize logo/colors/landing page?', verbose_name='custom branding')),
                ('analytics', models.BooleanField(default=False, help_text='Student progress & enrollment analytics dashboard?', verbose_name='analytics')),
                ('trial_days', models.PositiveSmallIntegerField(default=14, verbose_name='trial days')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Display metadata: icon, description, highlights.', verbose_name='features')),
            ],
            options={
                'verbose_name': 'center plan',
                'verbose_name_plural': 'center plans',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CenterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('organization_name', models.CharField(max_length=200, verbose_name='organization name')),
                ('subdomain', models.SlugField(help_text='Desired URL slug (checked for uniqueness).', max_length=63, verbose_name='subdomain')),
                ('tagline', models.CharField(blank=True, help_text='What courses will this center offer?', max_length=255, verbose_name='tagline')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('verification_token', models.UUIDField(blank=True, null=True, unique=True, verbose_name='verification token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='tenants.centerplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'center registration',
                'verbose_name_plural': 'center registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('organization_name', models.CharField(db_index=True, max_length=200, verbose_name='organization name')),
                ('slug', models.SlugField(help_text='URL-safe center identifier (also the schema name).', max_length=63, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('tagline', models.CharField(blank=True, help_text="One-line description for the center's landing page.", max_length=255, verbose_name='tagline')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Per-center overrides: site_name, primary_color, logo_url, smtp_*, social_providers, allow_self_signup, require_mfa.', verbose_name='settings')),
                ('subscription_id', models.CharField(blank=True, help_text='External billing reference (deferred to Loop-CRM).', max_length=255, verbose_name='subscription ID')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='trial ends')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='tenants.centerplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'course center',
                'verbose_name_plural': 'course centers',
                'ordering': ['organization_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Canonical domain for this center.', verbose_name='primary')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.coursecenter')),
            ],
            options={
                'verbose_name': 'course domain',
                'verbose_name_plural': 'course domains',
            },
        ),
    ]
