# Generated by Django 5.2.17 on 2026-08-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0007_apikey_company_coupon_deliverytype_deliveryzone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='rate_limit_per_minute',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Max requests per minute (null = unlimited)', null=True),
        ),
    ]
