# Generated by Django 5.2.17 on 2026-08-15 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_full', '0014_deliveryprovider_deliveryorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeClockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Accumulated break time in minutes for this shift.')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeclock_entries', to='pos_full.employee')),
                ('schedule', models.ForeignKey(blank=True, help_text='The planned shift this punch corresponds to (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeclock_entries', to='pos_full.employeeschedule')),
            ],
            options={
                'db_table': 'full_timeclock_entries',
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['employee', 'clock_in'], name='full_timecl_employe_a56f1d_idx'), models.Index(fields=['clock_out'], name='full_timecl_clock_o_d04ff4_idx')],
            },
        ),
    ]
