# Generated by Django 5.2.16 on 2026-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_channel_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='YouTube channel name'),
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_channel_url',
            field=models.URLField(blank=True, verbose_name='YouTube channel'),
        ),
    ]
