# Generated by Django 5.2.16 on 2026-08-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_course_youtube_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('sv', 'Swedish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('pt', 'Portuguese')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
